getlago/lago-front

src/pages/developpers/Debugger.tsx
Link to https://github.com/getlago/lago-product/issues/25
=> fix: ✨ Add bottom space in event list

ditto/base.json, ditto/config.yml, src/components/addOns/AddOnItem.tsx, src/components/coupons/CouponItem.tsx, src/components/customers/AddAddOnToCustomerDialog.tsx, src/components/customers/AddCouponToCustomerDialog.tsx, src/components/customers/CustomerAddOns.tsx, src/components/customers/CustomerCoupons.tsx, src/components/customers/CustomerInvoicesList.tsx, src/components/plans/ChargeAccordion.tsx, src/components/plans/ChargePercentage.tsx, src/components/plans/GraduatedChargeTable.tsx, src/components/plans/PackageCharge.tsx, src/components/plans/PlanForm.tsx, src/core/__tests__/intlFormatNumber.ts, src/core/intlFormatNumber.ts, src/generated/graphql.tsx, src/hooks/plans/useCreateEditPlan.ts, src/styles/globalStyle.tsx
Linked issue https://github.com/getlago/lago-product/issues/20
=> feat: 💘 Charge percentage pricing

ditto/base.json, src/components/plans/ChargePercentage.tsx
Original discussion : https://getlago.slack.com/archives/C03B4D0AANS/p1655804775928309
=> feat: 👀 Use 100 unit for percentage charge calculation

ditto/base.json, ditto/config.yml, src/components/plans/PlanForm.tsx
https://github.com/getlago/lago-product/issues/30
=> feat: 📆 Add weekly billing

ditto/base.json
=> chore: Fix translation

src/components/form/ComboBox/ComboBoxVirtualizedList.tsx
=> fix: 🛀 Remove double scrollbar on Combobox

src/components/form/ButtonSelector/ButtonSelectorField.tsx, src/components/form/ComboBox/ComboBoxField.tsx, src/components/form/ComboBox/ComboBoxInput.tsx, src/components/form/Radio/RadioField.tsx, src/components/form/Switch/SwitchField.tsx, src/components/form/TextInput/TextInput.tsx, src/components/form/TextInput/TextInputField.tsx, src/components/plans/GraduatedChargeTable.tsx, src/pages/auth/Login.tsx
https://www.notion.so/getlago/Delivery-cockpit-d3511c278d574a3aa82986b0d7caf8e1?v=7ba2f0f62ed5477c9931d02c2fe62427&p=3afb3ab133544b698e7289bf5a26e387
=> fix : ⌨️ Text input debounce create glitches

src/components/plans/PlanForm.tsx
https://github.com/getlago/lago-product/issues/34
=> feat: 🪣 Enable add charge if subscription

src/components/form/Switch/Switch.tsx
https://www.notion.so/getlago/Toggle-switch-on-off-in-edition-mode-34f006502ff84d2e9f65ef012166301c
=> fix: 🎛 Switch can't be disabled

ditto/base.json, ditto/config.yml, ditto/index.js, src/generated/graphql.tsx, src/layouts/SideNavLayout.tsx
This MR prompts the app version in side menu popper, bellow logout button.
=> feat: 🏷 display app version in side nav

package.json, yarn.lock
https://github.com/getlago/lago-front/security/dependabot/11
=> chore: 🚨 Fix risky dependencies

src/stories/Alert.stories.tsx
This MR adds the story for the Alert component
<div style="display: inline">
</div>
=> chore: 💅 Add story for the Alert component

src/components/form/DatePicker/DatePicker.tsx
DatePicker component can now update it's placement attribute with corresponding props
=> improvement: 📍allow DatePicker to receive it's placement as props

src/components/designSystem/Button.tsx, src/components/designSystem/ButtonLink.tsx, src/components/designSystem/Popper.tsx, src/components/designSystem/Tabs/NavigationTab.tsx, src/components/designSystem/Tabs/index.ts, src/components/designSystem/index.ts, src/components/plans/ChargeAccordion.tsx, src/core/router/index.tsx, src/layouts/Developpers.tsx, src/layouts/Settings.tsx, src/layouts/SideNavLayout.tsx, src/pages/__devOnly/DesignSystem.tsx, src/pages/settings/StripeIntegration.tsx
Fix the bug [CMD + Click does not open link in a new tab](https://www.notion.so/getlago/Delivery-cockpit-d3511c278d574a3aa82986b0d7caf8e1?p=6c4deec62b4f4d8695a45fa104363a81)
=> fix: 🔥 ButtonsLink + NavigationLink

globals.d.ts, jest.config.js, src/core/router/index.tsx, src/hooks/core/useInternationalization.ts, src/layouts/SideNavLayout.tsx, webpack.common.js
=> chore: 🐹 Differentiate APP_ENV staging and qa

src/components/addOns/AddOnItem.tsx, src/components/billableMetrics/BillableMetricItem.tsx, src/components/coupons/CouponItem.tsx, src/components/customers/CustomerAddOns.tsx, src/components/customers/CustomerInvoicesList.tsx, src/components/customers/CustomerItem.tsx, src/components/customers/CustomerSubscriptionsList.tsx, src/components/customers/CustomerUsage.tsx, src/components/plans/PlanItem.tsx, src/pages/developpers/Debugger.tsx
Apply same format `LLL. dd, yyyy` to all dates in the app
https://www.notion.so/getlago/Delivery-cockpit-d3511c278d574a3aa82986b0d7caf8e1?p=49ee789002bb477a817332aba7c3e354
=> feat: 📅 Update date format

src/components/ConditionalWrapper.tsx, src/components/addOns/AddOnItem.tsx, src/components/billableMetrics/BillableMetricItem.tsx, src/components/coupons/CouponItem.tsx, src/components/customers/CustomerItem.tsx, src/components/designSystem/ButtonLink.tsx, src/components/plans/PlanItem.tsx, src/pages/__devOnly/DesignSystem.tsx, src/styles/designSystem/List.tsx
Closes https://github.com/getlago/lago-front/issues/273
=> chore: 🔗 List items are links

src/components/coupons/CouponItem.tsx, src/pages/CouponsList.tsx
Original notion : https://www.notion.so/getlago/Delivery-cockpit-d3511c278d574a3aa82986b0d7caf8e1?p=f3caa273ad714b50a283bbb6d1613f20&pm=s
=> fix: 😬 Coupon date should be on one line

src/components/billableMetrics/BillableMetricCodeSnippet.tsx
https://www.notion.so/getlago/Update-event-snippet-2185e764943c4bfdae7d60838fd9acb3
=> fix: 🎹 Code snippet billable metric

.release-it.js, package.json, yarn.lock
This PR aims to improve the release process by adding `release-it` package and enabling it's `lerna-changelog` plugin.
You need to setup GITHUB_AUTH in your local rc config (e.g. bashrc or zshrc) in order to be able to use this command
- Go to [https://github.com/settings/tokens/new](https://github.com/settings/tokens/new)
- You can call it `lerna-public-repo-auth-token` or whatever you want
- Set no expiration date (this is for your personal use only)
- Check `public_repo` option
- Generate token and place it in your local `rc` config `GITHUB_AUTH=<YOUR_TOKEN>`
=> deps: 🗄️ add release-it package

src/components/designSystem/Avatar.tsx, src/components/designSystem/Icon/index.tsx, src/components/designSystem/ShowMoreText.tsx, src/components/designSystem/Skeleton.tsx, src/components/designSystem/Status.tsx, src/components/designSystem/Table/Table.tsx, src/components/form/ComboBox/ComboBoxField.tsx, src/components/form/Radio/Radio.tsx, src/components/form/Radio/RadioField.tsx, src/pages/__devOnly/DesignSystem.tsx, src/public/icons/forms/radio-checked.svg, src/public/icons/forms/radio.svg, src/styles/muiTheme.ts
=> Add component to design system page

.eslintrc, src/components/form/TextInput/TextInput.tsx, src/components/plans/PlanForm.tsx
Enable [eqeqeq](https://eslint.org/docs/latest/rules/eqeqeq) rule in our repo
=> chore: Add linter rule eqeqeq and fix errors

src/core/router/index.tsx, src/hooks/core/useInternationalization.ts, src/index.js, src/layouts/SideNavLayout.tsx
This PR makes the app use the window.app_env instead of the process.APP_ENV
=> breaking: use window env

src/core/router/index.tsx, src/hooks/core/useInternationalization.ts, src/layouts/SideNavLayout.tsx
Just a little refactor to not instantiate a variable if result is used once
=> chore: remove environment variable if used once

src/hooks/ui/__tests__/useListKeyNavigation.test.tsx, src/hooks/ui/useListKeyNavigation.tsx
Adds a test for useListKeyNavigation hook
=> chore: 🗺 add test for useListKeyNavigation hook

src/hooks/core/__tests__/useInternationalization.test.ts, src/hooks/core/useInternationalization.ts
This PR adds tests for internal methods of useInternationalization only
=> chore: 🪐 test useInternationalization internal methods

src/hooks/core/__tests__/useInternationalization.test.tsx
Adds a last test for the useInternationalization hook
Closes https://github.com/getlago/lago-front/issues/334
=> test: add test for translate method

.env.template, .github/workflows/codegen.yml, .github/workflows/cypress.yml, cypress.config.ts, cypress/cypress.config.js, cypress/e2e/auth/t0-signup.cy.ts, cypress/e2e/auth/t1-login.cy.ts, cypress/support/commands.ts, cypress/support/e2e.ts, cypress/tsconfig.json, docker-compose.ci.yml, package.json, src/components/designSystem/Alert.tsx, src/components/designSystem/Avatar.tsx, src/components/designSystem/Button.tsx, src/components/designSystem/Icon/Icon.tsx, src/components/designSystem/Status.tsx, src/components/designSystem/Toasts/Toast.tsx, src/components/designSystem/Typography.tsx, src/components/form/TextInput/TextInput.tsx, src/layouts/SideNavLayout.tsx, src/pages/auth/Login.tsx, src/pages/auth/SignUp.tsx, tsconfig.json, yarn.lock
=> [Chore]: Cypress setup + first tests

src/components/designSystem/ButtonLink.tsx
=> fix: 🆑 Prevent double focus on button link

src/components/plans/ChargePercentage.tsx
This MR updates the alert display logic to fit with other app usages.
=> Update charge percent alert display logic + display currency symbol

src/components/customers/usage/UsageItem.tsx
https://www.notion.so/getlago/Delivery-cockpit-d3511c278d574a3aa82986b0d7caf8e1?p=49d2bb9436f9481dadab9651bd1ae1c6&pm=s
=> fix: 😬 Make sure there is not more than 3 charges

src/components/form/ComboBox/ComboBox.tsx
**PLEASE REMOVE THIS TEMPLATE BEFORE SUBMITTING**
Please, go through these steps before you submit a PR.
1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:
a. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.
b. You have a descriptive commit message with a short title (first line), named by the [Conventional commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
c. You have only one commit (if not, squash them into one commit).
d. Make sure to always use `rebase`, we do not accept merge commits.
3. **After** these steps, you're ready to open a pull request.
a. Give a descriptive title to …
=> fix: 🚨 Compobox should not be open

src/layouts/SideNavLayout.tsx
https://www.notion.so/getlago/Delivery-cockpit-d3511c278d574a3aa82986b0d7caf8e1?p=e66b1a5e2df14888bd2a4f01e8749450&pm=s
=> fix: 🎬 Truncate company name if too long

Dockerfile.arm64
- Add ARM64 Architecture Dockerfile
=> misc(docker): Add ARM64 DockerFile

.github/workflows/release.yml
=> misc(docker): Build ARM64 Image with CI

.github/workflows/manual-release.yml, .github/workflows/release.yml, Dockerfile.arm64
- Add QEMU and Buildx setup to support ARM64 build
=> misc(gh): fix arm64 auto build

src/components/form/DatePicker/DatePicker.tsx
=> fix(linter): returns should be outside of else condition

src/components/form/Checkbox/Checkbox.tsx, src/components/form/Checkbox/CheckboxField.tsx, src/components/form/Checkbox/index.ts, src/components/form/index.ts, src/pages/__devOnly/DesignSystem.tsx, src/stories/Checkbox.stories.tsx
Adds a new component to the design system.
Will be used in the % coupon feature released later this week
=> feat: ✅ add Checkbox component

src/components/plans/ChargeAccordion.tsx, src/components/plans/ChargePercentage.tsx, src/components/plans/GraduatedChargeTable.tsx, src/components/plans/PackageCharge.tsx, src/generated/graphql.tsx, src/hooks/plans/usePlanForm.tsx, src/pages/CreatePlan.tsx
Closes https://github.com/getlago/lago-front/issues/354
=> chore: 🫢 Clean editPlan fragment

src/hooks/plans/__tests__/useGraduatedChargeForm.test.tsx, src/hooks/plans/useGraduatedChargeForm.ts
Closes https://github.com/getlago/lago-front/issues/332
=> chore: 🧪 Test useGraduatedChargeForm

ditto/base.json
=> chore(translation): update with last ditto version

cypress/e2e/t4-create-plan.cy.ts, cypress/e2e/t6-edit-plan.cy.ts, src/components/plans/ChargeAccordion.tsx, src/components/plans/ChargePercentage.tsx, src/components/plans/GraduatedChargeTable.tsx, src/components/plans/PackageCharge.tsx, src/components/plans/VolumeChargeTable.tsx, src/core/serializers/serializePlanInput.ts, src/formValidationSchemas/chargeSchema.ts, src/generated/graphql.tsx, src/hooks/plans/__tests__/useGraduatedChargeForm.test.tsx, src/hooks/plans/__tests__/useVolumeChargeForm.test.tsx, src/hooks/plans/useGraduatedChargeForm.ts, src/hooks/plans/useVolumeChargeForm.ts, src/pages/CreatePlan.tsx
In order to prepare grouped billable metric (BM), we need to perform a first change on BM structure.
All charge related data are now grouped in a `properties` object.
=> feat(charge): group all charge data in a properties object

ditto/base.json, src/core/apolloClient/reactiveVars/currentUserInfosVar.ts, src/layouts/SideNavLayout.tsx
[Figma](https://www.figma.com/file/Pyhpgv1CAy6nGkl3X9aqy0/%E2%9B%B5%EF%B8%8FDocumentation-asset?node-id=1141%3A22495&viewport=115%2C-728%2C0.43)
[Spec](https://www.notion.so/getlago/Side-navigation-ea426d6a815e4edea9dd27936079921d#67e29cb0cfa94a09b1e33d53b54849e7)
=> [Feat] Allow user to switch organizations

src/components/plans/ChargeAccordion.tsx, src/pages/CreateBillableMetric.tsx
This OR performs some simple adjustment about inconsistencies found in the app after latest releases
Better review without whitespaces
=> fix(qa) 👀handle simple style QA returns

ditto/base.json, ditto/config.yml, ditto/index.js, src/components/coupons/CouponCaption.tsx, src/components/customers/AddCouponToCustomerDialog.tsx, src/components/customers/CustomerCoupons.tsx, src/generated/graphql.tsx, src/pages/CustomerDetails.tsx
It’s impossible to apply several coupon at the same moment on a customer
This PR adapts the code on the Frontend side to allow a customer to have multiple coupons
- Make the "Apply coupon" action never disabled
- Add a button in the coupon list to trigger the addCoupon action
=> feat: 🏷 Allow to apply multiple coupons on customer

src/pages/developers/Webhook.tsx
We display the first orga webhook url even if user belongs to many orga
This PR find the user's current organization to retrieve the webhook url
=> bug: display current orga webhook url

PULL_REQUEST_TEMPLATE.md
=> linter: fix extra space in pull request template

src/generated/graphql.tsx
=> chore: update currency enum from graph

src/hooks/customer/useAddSubscription.tsx
👉 https://github.com/getlago/lago/issues/{{NUMBER}}
Include relevant motivation and context.
=> fix: 😵‍💫 Allow to fetch 1000 plans to add subscription

src/layouts/CustomerInvoiceDetails.tsx
Credit note feature is not fully available yet
This PR hides the CTA redirecting to credit notes creation (form)
=> chore: hide credit note cta

src/core/router/AuthRoutes.tsx, src/core/router/CustomerRoutes.tsx, src/core/router/DevelopperRoutes.tsx, src/core/router/ObjectsRoutes.tsx, src/core/router/SettingRoutes.tsx, src/core/router/index.tsx, src/core/router/types.ts
Refactor to reorganize the routes and have a more maintainable code
=> chore: ⛑ Reorganize routes

src/components/designSystem/Status.tsx
=> bug: fix status label

.github/workflows/codegen.yml
- Add Manual codegen workflow capability
=> misc(gha): Add manual launch for codegen

ditto/base.json, src/components/invoices/InvoiceDetailsTableFooter.tsx
Make some adjustment in total display for draft invoices
=> feat: hide Coupon / Prepaid Credit in draft invoice totals and display alert info

.github/workflows/tests.yml
Skip test in CI if PR is in draft
=> chore: 🏂 Skip tests in Draft PR

ditto/base.json, src/components/customers/CustomerInvoicesList.tsx, src/components/customers/CustomerInvoicesTab.tsx, src/components/customers/CustomerSettings.tsx, src/components/customers/EditCustomerInvoiceGracePeriodDialog.tsx, src/components/customers/creditNotes/CreditNotesList.tsx, src/components/settings/EditOrganizationGracePeriodDialog.tsx
Fix for Grace Period QA returns
=> fix: 🫥 QA Grace Period

src/components/coupons/CouponCodeSnippet.tsx, src/components/creditNote/CreditNoteFormCalculation.tsx, src/components/form/DatePicker/DatePicker.tsx, src/layouts/CustomerInvoiceDetails.tsx, src/pages/InvoiceOverview.tsx
+ Bug on DatePicker (page crash if we remove the date)
=> feat: 🦷 Fix post massive QA

src/components/invoices/InvoiceListItem.tsx, src/pages/InvoicesList.tsx
👉 https://github.com/getlago/lago/issues/{{NUMBER}}
Include relevant motivation and context.
=> feat: 🤐 Display resend recollection button

src/components/plans/AddChargeDialog.tsx
Waiting for the search in this component, we increase the fetch limit
=> fix: increase BM fetch limit in add dialog

ditto/base.json
=> chore: get last translations

src/public/icons/filter.svg, src/public/icons/pulse.svg, src/public/icons/wallet.svg
Some SVG were wrongly defined, This PR fixes them
=> chore: fix some svg wrong syntax

src/core/formats/__tests__/formatCreditNotesItems.test.ts, src/core/formats/__tests__/intlFormatNumber.test.ts
This PR does:
- move an existing test to it's correct folder
- add a test for formatCreditNotesItems.ts hook
=> Formats tests

src/core/serializers/__tests__/serializeAmount.test.ts, src/core/serializers/__tests__/serializePlanInput.test.ts
=> chore: add test for serializePlanInput hook

cypress/e2e/auth/t1-login.cy.ts, cypress/e2e/t2-create-customer.cy.ts, cypress/e2e/t3-create-bm.cy.ts, cypress/e2e/t4-create-plan.cy.ts, cypress/e2e/t6-edit-plan.cy.ts, cypress/support/e2e.ts
Before each test the session will be called (created if not existed, reused otherwise)
There is a twick to not call the session on auth file (ie no login before the login & signup test
Any test with ::preventLogin in its name also will prevent the login (ie if we ever need to test a public page etc...)
=> chore: 🫣 Create session for E2E tests

ditto/base.json
=> chore: get last translation update

ditto/base.json, src/components/plans/DeletePlanDialog.tsx
when terminating plan copy, we display some copy listing how many subscription or draft invoice are linked
This PR unify copy usage and handle all cases
=> chore: unify terminate plan copy

src/components/customers/CustomerInvoicesTab.tsx
Invoice loading was showing finalized invoices list even tho no invoices were presents.
We prefer to hide this, also because the empty state have not been planned to this this state
This PR fixes the loading states handling in the invoice list page
=> bug: fix invoice loading state behaviour

src/components/wallets/CustomerWalletList.tsx, src/generated/graphql.tsx
PR to remove an unused mutation.
=> chore: remove unused mutation

cypress/e2e/t4-create-plan.cy.ts, src/components/plans/ChargePercentage.tsx
related to this fix https://github.com/getlago/lago-front/pull/792
=> test: add anti-regression test scenario

src/components/customers/CustomerInvoicesList.tsx, src/pages/InvoicesList.tsx, src/pages/developers/Debugger.tsx
We cannot shorten location.reload invocation, it's leading to an illegal method invocation.
=> bug: fix location reload invocation

src/hooks/useCreateEditCustomer.ts
Manually update the cache after creating a customer to avoid glitch on list
=> chore: 👓 Manually update cache on customer creation

src/components/customers/subscriptions/TerminateCustomerSubscriptionDialog.tsx, src/hooks/useCreateEditCustomer.ts, src/pages/AddOnsList.tsx, src/pages/BillableMetricsList.tsx, src/pages/CouponsList.tsx, src/pages/CustomerDetails.tsx, src/pages/CustomersList.tsx, src/pages/InvoicesList.tsx, src/pages/PlansList.tsx
=> chore: Cache update

src/pages/CreateBillableMetric.tsx
Improve UX in BM form when editing one with dimension
=> feat: initially open group dimension accordion on condition

src/generated/graphql.tsx
Get last graph version
Related to https://github.com/getlago/lago-api/pull/880
=> chore(graph): update graph to last version

src/components/designSystem/Accordion.tsx
https://mui.com/material-ui/react-accordion/#performance
=> chore(accordion): prevent rendering content when closed

src/components/plans/ChargePercentage.tsx
Simple translation order changed in an Alert component
=> chore(ChargePercentage): reorder translations

src/generated/graphql.tsx, src/pages/CreateBillableMetric.tsx
=> bug: 💊 Prevent BM update if used in plan

src/components/plans/ChargeAccordion.tsx
Accordion does not render children when closed
This PR moves the modal invocation that used to be inside the accordion and not rendered when it's closed, leading to have the button not doing anything on click
=> bug(charge-accordion): fix button not clickable when closed

src/components/wallets/WalletAccordion.tsx, src/generated/graphql.tsx
Two wallet attributes are switching from string to number
This PR adapts the front to handle this change
=> chore(wallet): turn balance and amount into cents

package.json, yarn.lock
This package seems to not be used in the app
=> chore(package): remove unused add package

src/components/customers/AddCustomerDrawer.tsx, src/components/customers/CustomerItem.tsx, src/pages/CustomerDetails.tsx, src/pages/CustomersList.tsx
We have a drawer rendered in every customer item in list, hammering the DOM perf as the network ones 
This extract the drawer to only render in parent dom, leading to only render it once
=> chore(CustomerList): extract edit drawer from looped element dom

src/components/creditNote/CreditNoteFormCalculation.tsx, src/pages/CreateCreditNote.tsx
I've made a wrong fix yesterday. Leading to worse behaviour in the form calculation
This PR reverts the commit from yesterday and fixes the "real" issue that is related to form validation and one value that was wrongly udpated
=> fix(creditNote): better payback validation

src/components/customers/AddCouponToCustomerDialog.tsx, src/formValidation/feesSchema.ts, src/hooks/useCreateEditAddOn.ts, src/pages/CreateAddOn.tsx, src/pages/CreatePlan.tsx, src/pages/InvoiceOverview.tsx
Some type ignore comments were not necessary in the code. 
Let's remove them
=> chore(Type): remove some unnecessary @ts-ignore

src/styles/globalStyle.tsx
Add a micro-interaction on button click, reducing it's scale of 0.01.
=> chore(button): lower scale on click

src/styles/globalStyle.tsx, src/styles/muiTheme.ts
Bring more granularity on button scale on click
=> chore(button): better scale on click

ditto/base.json, src/components/form/AmountInput/AmountInput.tsx, src/components/form/TextInput/TextInput.tsx, src/components/wallets/AddWalletToCustomerDialog.tsx, src/core/serializers/serializeAmount.ts
We now support 4 decimal precision.
So bugging behaviour for CLF is now fixed
=> feat(decimal): Support 4 decimal precision hence supporting CLF

src/components/addOns/AddOnCodeSnippet.tsx, src/pages/CreateAddOn.tsx
Forgot to update the AddOn form code snippet to remove the applied_add_ons context and replace with the new one
=> bug(addon): update snippet in form

package.json, yarn.lock
This package resolution can be removed now
=> chore(deps) remove package resolutions

src/core/router/CustomerRoutes.tsx, src/core/router/DevelopperRoutes.tsx, src/core/router/ObjectsRoutes.tsx, src/core/router/index.tsx
chunk names should be uniq to reduce chunk size
=> chore(router): fix non-uniq chunk names

src/core/router/AuthRoutes.tsx, src/core/router/CustomerPortalRoutes.tsx, src/core/router/CustomerRoutes.tsx, src/core/router/DevelopperRoutes.tsx, src/core/router/ObjectsRoutes.tsx, src/core/router/SettingRoutes.tsx, src/core/router/index.tsx, src/core/router/utils.tsx
Will fix the chunk loading error users might face when fetching a not-anymore existing chunk of the app
=> chore: better component lazy loading

src/components/ErrorBoundary.tsx, src/components/RouteWrapper.tsx, src/components/form/ComboBox/ComboBoxPopperFactory.tsx, src/hooks/core/useLocationHistory.ts
Would save us some sentry alerts
=> chore: prevent accessing an object value that could be undefined

src/hooks/customer/useAddSubscription.tsx
=> chore: prevent destructuring raising error on read

src/components/invoices/InvoiceCustomerInfos.tsx, src/pages/CreateInvoice.tsx, src/pages/CustomerDetails.tsx
Improves the display in some specific situations
=> chore(customer) better header display

src/components/developers/EditWebhookDialog.tsx, src/pages/developers/WebhookLogs.tsx
Small improvement for the webhook logs page
=> feat(webhooks): redirect to logs page on creation

src/components/customers/subscriptions/AddSubscriptionDrawer.tsx, src/components/designSystem/Dialog.tsx, src/components/designSystem/Drawer.tsx
Fix some remaining places in the app that could break if the displayed text is too long.
=> bug(copy) fix some copy overflow behaviour

src/core/router/utils.tsx
Just a last adjustment before I can peacefully silence this error
=> chore(router) make sure retried call is catched

ditto/config.yml, ditto/index.js
Had an issue with the current project list, due to a recent rebase
=> chore(ditto) fix project config

ditto/base.json, src/components/plans/PlanSettingsSection.tsx, src/generated/graphql.tsx, src/hooks/useCreateEditCoupon.ts, src/pages/CreateCoupon.tsx, src/pages/CreateTax.tsx
👉 https://getlago.canny.io/feature-requests/p/add-optional-description-for-coupons
Add a description field to the coupon
=> feat(coupon) add description

cypress/e2e/t4-create-plan.cy.ts, cypress/e2e/t6-edit-plan.cy.ts, src/components/plans/ChargesSection.tsx, src/components/plans/PlanSettingsSection.tsx, src/core/constants/form.ts, src/hooks/plans/usePlanForm.tsx, src/hooks/useCreateEditAddOn.ts, src/hooks/useCreateEditBillableMetric.ts, src/hooks/useCreateEditCoupon.ts, src/hooks/useCreateEditTax.ts, src/pages/CreateAddOn.tsx, src/pages/CreateBillableMetric.tsx, src/pages/CreateCoupon.tsx, src/pages/CreateInvoice.tsx, src/pages/CreatePlan.tsx, src/pages/CreateTax.tsx
We want to improve the UX in the app. We now
- open the charge dropdown when we want to "Add a charge" in the create plan page
- open the addon dropdown when we want to "add an addon" in the create invoice page
=> feat: open combobox on input focus

ditto/base.json
Legal links below the signup flow are broken. Website links have been changed.
Fix deadlinks
=> fix(deadlinks): fix deadlinks for signup flow

src/components/invoices/InvoiceDetailsTable.tsx
We want to align with the backend so changing this value to 0
=> chore(invoice) fix empty invoice units value

src/components/customers/AddCustomerDrawer.tsx, src/generated/graphql.tsx
=> chore(graph) get last version

src/pages/InvoiceOverview.tsx
padding-top should only have one value set to work.
=> bug(draft-invoice) fix alert padding top value

ditto/base.json, src/components/plans/GraduatedChargeTable.tsx, src/core/constants/form.ts, src/formValidation/chargeSchema.ts, src/hooks/plans/__tests__/useGraduatedChargeForm.test.tsx, src/hooks/plans/__tests__/useVolumeChargeForm.test.tsx, src/hooks/plans/useGraduatedChargeForm.ts, src/hooks/plans/useVolumeChargeForm.ts
We want to allow having minimum 1 tier on volume and graduated charge models
=> feat: allow delete 1 more tier

Dockerfile
- CVE-2023-3138 (libx11)
- CVE-2023-35945 (nghttp2)
- CVE-2023-2975 (openssl)
- CVE-2023-3446 (openssl)
- CVE-2023-3316 (tiff)
- CVE-2023-3817 (openssl)
=> misc(cves): Fix some CVEs

cypress/e2e/t30-create-one-off-invoice.cy.ts, src/components/customers/CustomerInvoicesList.tsx, src/components/invoices/EditInvoiceItemTaxDialog.tsx, src/components/invoices/InvoiceDetailsTableFooter.tsx, src/components/invoices/InvoiceListItem.tsx, src/core/constants/form.ts, src/pages/CreateInvoice.tsx, src/pages/CustomerDetails.tsx
This PR adds one e2e test for the one-off invoice creation
=> chore(test) create one-off invoice with taxes

.github/workflows/translation-update.yml
I think we need to install deps to use glob
=> chore: fix Translation Update action

.github/workflows/translation-update.yml
=> chore(action) use local script in translation-update action

.github/workflows/codegen.yml, .github/workflows/cypress.yml, .github/workflows/linter.yml, .github/workflows/tests.yml, .github/workflows/translation-check.yml, .github/workflows/translation-update.yml, .github/workflows/typescript.yml, Dockerfile, Dockerfile.dev, package.json
See https://nodejs.dev/fr/about/releases/
=> chore(node) update version to LTS (v18)

src/components/plans/ChargesSection.tsx, src/hooks/plans/usePlanForm.tsx, src/pages/CreatePlan.tsx, src/pages/CreditNoteDetails.tsx, yarn.lock
We plan to have a new override experience in the app.
This new page will reuse most of the plan form parts.
This PR makes it more easy to use the same form component outside of the plan form page.
=> chore(plan) make plan form more modular, to ease re-usage

src/components/addOns/AddOnItem.tsx, src/components/coupons/CouponItem.tsx, src/components/customers/CustomerItem.tsx, src/components/customers/subscriptions/TerminateCustomerSubscriptionDialog.tsx, src/components/plans/PlanItem.tsx, src/generated/graphql.tsx, src/hooks/customer/useAddSubscription.tsx, src/pages/CustomerDetails.tsx
=> chore(graph) rename customerCount attribute to customersCount

src/components/billableMetrics/BillableMetricCodeSnippet.tsx, src/core/utils/BMGroupUtils.ts
2 things
1. Weighted sum does not have a code snippet shown when data is valid (in the BM form)
2. All BM code snippet were not displaying the group values when a valid group was defined
This PR does implement and fix the two points above
=> feat: add weighted sum BM code snippet

src/pages/developers/Webhooks.tsx
Simple UI fix for long url to not overflow their parent container
=> bug(webhook) prevent long url to overflow

src/components/plans/ChargeAccordion.tsx
It used to be there, been removed, and added again finally
=> feat(charge) display code in the charge accordion summary

src/components/plans/ChargeAccordion.tsx
Conditionally shown Alert is not spaced correctly with the rest of the Card content
This PR fixes this spacing
=> bug(ChargeAccordion) fix spacing with the Alert and content

src/components/plans/ChargeAccordion.tsx, src/hooks/__tests__/fixtures.ts
Currently it is not possible to use graduated charge model with prorated charges
This PR unlocks this possibility from the UI
=> feat (graduated-prorated): Unlock graduated prorated combo from the UI

src/components/plans/ChargeAccordion.tsx
👉  https://getlago.canny.io/feature-requests/p/{{FEATURE_SLUG}}
Include relevant motivation and context.
=> misc(beta): remove graduated percentage beta badge

ditto/base.json, src/pages/developers/Webhooks.tsx
This link is not working and should not exists
This PR removed the link by updating the translations.
The translation does not need to be in an unsafe HTML parsing now.
=> bug(webhook) remove broken link

src/components/coupons/AddBillableMetricToCouponDialog.tsx, src/components/coupons/AddPlanToCouponDialog.tsx, src/components/customers/AddCouponToCustomerDialog.tsx, src/components/customers/EditCustomerDocumentLocaleDialog.tsx, src/components/customers/EditCustomerInvoiceGracePeriodDialog.tsx, src/components/customers/EditCustomerVatRateDialog.tsx, src/components/designSystem/Dialog.tsx, src/components/developers/CreateWebhookDialog.tsx, src/components/invoices/EditInvoiceDisplayName.tsx, src/components/invoices/EditInvoiceItemDescriptionDialog.tsx, src/components/invoices/EditInvoiceItemTaxDialog.tsx, src/components/invoices/EditInvoicePaymentStatusDialog.tsx, src/components/settings/AddOrganizationVatRateDialog.tsx, src/components/settings/EditDefaultCurrencyDialog.tsx, src/components/settings/EditNetPaymentTermDialog.tsx, src/components/settings/EditOrganizationDocumentLocaleDialog.tsx, src/components/settings/EditOrganizationGracePeriodDialog.tsx, src/components/settings/EditOrganizationInformationsDialog.tsx, src/components/settings/EditOrganizationInvoiceTemplateDialog.tsx, src/components/settings/EditOrganizationTimezoneDialog.tsx, src/components/settings/emails/UpdateOrganizationLogoDialog.tsx, src/components/settings/integrations/AddAdyenDialog.tsx, src/components/settings/integrations/AddEditDeleteSuccessRedirectUrlDialog.tsx, src/components/settings/integrations/AddStripeDialog.tsx, src/components/settings/members/CreateInviteDialog.tsx, src/components/wallets/AddWalletToCustomerDialog.tsx, src/components/wallets/TopupWalletDialog.tsx, src/components/wallets/UpdateCustomerWalletDialog.tsx, src/pages/__devOnly/DesignSystem.tsx
Update modal for future refactor.
I aim to make further refactor and improve accessibility of the modals in the app
Like first element focus and submit on Enter press.
Those changes are somehow needed to have a better / more clear API interaction and ease future changes
=> chore(Dialog) Refactor API and attributes 

src/components/designSystem/Dialog.tsx
This PR simplify the internal Dialog exported method JSX
=> chore(dialog) simplify exported method jsx

src/components/designSystem/NavigationTab.tsx, src/layouts/SideNavLayout.tsx
=> misc(beta) add beta chip on new menu item

src/components/graphs/Invoices.tsx, src/components/graphs/__tests__/Invoices.test.ts
This amount should be pending + failed invoices amounts, excluding successes ones
=> bug(analytics) fix outstanding invoice amount displayed

src/components/designSystem/NavigationTab.tsx
Add external icon on navbar external link.
=> misc(nav) add icon if link is external

src/components/graphs/Invoices.tsx, src/components/graphs/__tests__/Gross.test.ts, src/components/graphs/__tests__/Invoices.test.ts, src/components/graphs/__tests__/Mrr.test.ts, src/components/graphs/__tests__/Usage.test.ts, src/components/graphs/__tests__/utils.test.ts, src/components/graphs/utils.ts
Change all date to be displayed as `LLL. yyyy`
=> misc(analytics) change date display format

cypress/e2e/10-resources/t20-create-customer.cy.ts, cypress/e2e/10-resources/t50-edit-plan.cy.ts, cypress/e2e/10-resources/t60-coupons-create-edit-apply.cy.ts, cypress/e2e/t10-add-subscription.cy.ts, cypress/e2e/t30-create-one-off-invoice.cy.ts
E2e tests are setting up a front and api apps to run tests against.
We currently add many structural change to the Lago project that, for now, breaks the apps setup in this CI job.
Leading to have many failing tests.
The short answer to it, even if unfortunate, is to comment those failing tests. When the source of those problems will be found we will be able to uncomment them all
=> mics(tests) comment failing e2e tests

src/components/wallets/WalletCodeSnippet.tsx
Removing some extra coma, quotation marks and fix the calls method
=> bug(wallet) fix snippet typos

src/components/addOns/AddOnCodeSnippet.tsx
Fixes https://github.com/getlago/lago/issues/303
=> bug(addon) make currency dynamic in code snippet

src/components/addOns/AddOnItem.tsx, src/components/billableMetrics/BillableMetricItem.tsx, src/components/coupons/CouponItem.tsx, src/components/customers/CustomerCreditNotesList.tsx, src/components/customers/CustomerItem.tsx, src/components/customers/subscriptions/SubscriptionItem.tsx, src/components/customers/subscriptions/SubscriptionLine.tsx, src/components/customers/usage/UsageItem.tsx, src/components/designSystem/Avatar.tsx, src/components/designSystem/Selector.tsx, src/components/developers/WebhookLogItem.tsx, src/components/plans/PlanItem.tsx, src/components/settings/emails/EmailSettingItem.tsx, src/components/settings/members/InviteItem.tsx, src/components/settings/members/MembershipItem.tsx, src/components/wallets/WalletAccordion.tsx, src/components/wallets/WalletTransactionList.tsx, src/layouts/CustomerInvoiceDetails.tsx, src/pages/CreateCoupon.tsx, src/pages/CreateCreditNote.tsx, src/pages/CreateInvoice.tsx, src/pages/CreditNoteDetails.tsx, src/pages/customerPortal/CustomerPortal.tsx, src/pages/developers/Webhooks.tsx, src/pages/settings/Integrations.tsx, src/pages/settings/OrganizationInformations.tsx
Switching from 32x32 to 40x40 by default.
Also adjust many places in the app
=> misc(Avatar) unify sizes to big

src/pages/WalletForm.tsx
=> bug(wallet-form) fix validation logic

src/components/invoices/details/InvoiceDetailsTable.tsx, src/generated/graphql.tsx
I'll have another system very soon. In a rush right now so made this ugly fix
=> bug(invoice-details) handle up to 28 sub per invoice

src/generated/graphql.tsx
This PR adds missing KWD currency
=> misc: add missing KWD currency

ditto/base.json, src/components/designSystem/BetaChip.tsx, src/components/designSystem/Chip.tsx, src/components/designSystem/NavigationTab.tsx, src/components/designSystem/Tooltip.tsx, src/components/designSystem/Typography.tsx, src/components/developers/WebhookLogDetails.tsx, src/components/plans/ChargeAccordion.tsx, src/components/plans/PlanSettingsSection.tsx, src/pages/CreateAddOn.tsx, src/pages/CreateBillableMetric.tsx, src/pages/__devOnly/DesignSystem.tsx, src/styles/muiTheme.ts
Goal of this PR is to refactor the Chip component.
It does have a new API but mainly, relies almost completely on the MUI chip component.
Objective was to fit more with MUI implementation, so we can pass props easily and integrate it better with other components.
=> misc(component) Refactor chip component

src/components/designSystem/Chip.tsx, src/components/form/MultipleComboBox/MultipleComboBox.tsx, src/components/form/MultipleComboBox/MultipleComboBoxField.tsx, src/components/form/MultipleComboBox/MultipleComboBoxItem.tsx, src/components/form/MultipleComboBox/MultipleComboBoxList.tsx, src/components/form/MultipleComboBox/MultipleComboBoxPopperFactory.tsx, src/components/form/MultipleComboBox/MultipleComboBoxVirtualizedList.tsx, src/components/form/MultipleComboBox/index.tsx, src/components/form/MultipleComboBox/types.ts, src/pages/__devOnly/DesignSystem.tsx, src/styles/muiTheme.ts
The current combobox's implementation is too complex and custom, making it very hard to work with multiple values.
This new component is created to handle this specific use case and has its own settings and inner components
=> mics: Add new multiple combobox component

src/pages/CreateInvoice.tsx
Instead of fixing the decimal display, make it automatic depending on the currency's precision
=> bug(createInvoice) automatic decimal display

src/generated/graphql.tsx
Adding the JOD (Jordanian dinar) currency as available currency
=> misc(currency) add JOD

src/components/form/MultipleComboBox/MultipleComboBox.tsx, src/components/form/MultipleComboBox/MultipleComboBoxPopperFactory.tsx, src/components/form/MultipleComboBox/types.ts, src/pages/__devOnly/DesignSystem.tsx
Will be used in future feature and to refactor existing parts of the app.
=> misc(multiple-combobox): add free solo mode

ditto/base.json, src/components/plans/CommitmentsSection.tsx, src/components/plans/details/PlanDetailsCommitmentsSection.tsx
Use the same copy as in plan details
=> bug: fix min commitment copy with intervals

CONTRIBUTING.md, src/layouts/Settings.tsx
Closes https://github.com/getlago/lago-front/pull/1452 & https://github.com/getlago/lago-front/pull/1453
=> External contribution

.github/workflows/codegen.yml, .github/workflows/cypress.old, .github/workflows/lago-internal.yml, .github/workflows/translation-update.yml
This should allow external contributions to have GH actions running
=> chore(workflow) update GH token to GITHUB_TOKEN

.github/workflows/codegen.yml, .github/workflows/cypress.old, .github/workflows/lago-internal.yml, .github/workflows/translation-update.yml
Reverts getlago/lago-front#1468
=> Revert "chore(workflow) update GH token to GITHUB_TOKEN"

src/core/serializers/__tests__/serializePlanInput.test.ts, src/core/serializers/serializePlanInput.ts
=> bug(plans): send empty array when removing all filters

src/components/invoices/InvoiceCreditNotesTable.tsx, src/components/invoices/InvoiceListItem.tsx, src/components/invoices/details/InvoiceDetailsTable.tsx, src/components/invoices/details/InvoiceDetailsTableBodyLinePercentage.tsx, src/pages/CreditNoteDetails.tsx
=> Fixed amount

src/components/invoices/InvoiceCustomerInfos.tsx
=> bug: fix invoice items aligments

src/components/designSystem/NavigationTab.tsx, src/components/plans/PlanItem.tsx, src/core/router/ObjectsRoutes.tsx, src/hooks/core/__tests__/useLocationHistory.test.ts, src/hooks/core/useLocationHistory.ts, src/layouts/SideNavLayout.tsx, src/pages/Home.tsx, src/pages/PlanDetails.tsx, src/pages/PlansList.tsx
This PR is part of the RBAC feature. 
Add route and action permission logic for the Plan views of the app.
Also, some adjustment needed to be performed to have a smoother role handling
Fixes DLVRY-322
=> feat: add plan route and actions role guard

src/components/coupons/CouponItem.tsx, src/core/router/ObjectsRoutes.tsx, src/pages/CouponsList.tsx
This PR is part of the RBAC feature. 
Add route and action permission logic for the Addons views of the app.
It only contains the list, I'll implement the details page in a following PR
Fixes DLVRY-324
=> feat: add coupons route and actions role guard

src/components/CodeSnippet.tsx, src/core/utils/__tests__/copyToClipboard.test.ts, src/core/utils/__tests__/snippetBuilder.test.ts, src/core/utils/copyToClipboard.ts, src/core/utils/snippetBuilder.ts
👉  https://getlago.canny.io/feature-requests/p/{{FEATURE_SLUG}}
While working on screens where we need to update the code snippets, it can sometimes be hard to make sure the code rendered is valid with all the conditions that applies to our forms. 
This PR should create a new snippet builder tool that would help us write our code snippets. 
This is still WIP but lmk you think!
=> refactor: use builder to write our code snippets

ditto/base.json, src/components/form/DatePicker/DatePicker.tsx
Bug introduced with v6 update. This PR fixes the label display and allow to pass a string or a dom element
=> bug: restore date picker label display

src/components/invoices/InvoicesList.tsx
=> bug: make invoice switcher button use caption text

src/index.js
This make sure we can use the Feature Flag logic in all environment that are not production
=> misc: enable FF for all non-prod env

src/core/apolloClient/init.ts
We can see an error toast when being ejected from the app, when the JWT expires.
This is due to ongoing potential queries being fired, with an invalid JWT then, returning a forbidden error.
Also, the app received a JTW expiration error first.
This PR make sure all auth (JWT expiration included) and forbidden error are silent and don't trigger an error toast
Fixes ISSUE-351
=> misc: silent auth and permissions related errors by default

src/generated/graphql.tsx
=> misc: codegen

src/hooks/plans/usePlanForm.tsx
Enable submit button on subscription plan by default
=> fix: assign plan submit button

src/components/designSystem/Alert.tsx, src/components/settings/integrations/AnrokIntegrationItemsListBillableMetrics.tsx, src/components/settings/integrations/AnrokIntegrationItemsListDefault.tsx, src/components/settings/integrations/NetsuiteIntegrationItemsListBillableMetrics.tsx
Few fixes to perform. 
You can review commit by commit
=> misc: add different fix and improvements

src/components/creditNote/CreditNoteFormItem.tsx, src/components/form/Checkbox/Checkbox.tsx, src/components/form/ComboBox/ComboBox.tsx, src/components/form/ComboBox/ComboBoxItem.tsx, src/components/form/MultipleComboBox/MultipleComboBoxItem.tsx, src/components/form/Radio/Radio.tsx, src/pages/__devOnly/DesignSystem.tsx, src/styles/muiTheme.ts
This PR contains 3 improvements and prepare for a combobox option improvement: possibility to add a sublabel
Better review commit by commit
=> misc: radio, checkbox and combobox improvements

src/components/form/ComboBox/ComboBox.tsx, src/components/form/ComboBox/ComboBoxItem.tsx, src/components/form/ComboBox/ComboBoxVirtualizedList.tsx, src/components/form/MultipleComboBox/MultipleComboBoxItem.tsx, src/components/form/MultipleComboBox/MultipleComboBoxVirtualizedList.tsx, src/components/form/MultipleComboBox/types.ts, src/components/settings/integrations/XeroIntegrationMapItemDialog.tsx, src/pages/__devOnly/DesignSystem.tsx
Combobox and Multiple combobox values can now contain descriptions!
Also added a commit where I fix the xero integration mapping that requires this description to be well displayed
=> misc: autocomplete with description

src/components/customers/CustomerMainInfos.tsx
Display `Show More` button if there is more than 5 items in the list using pure css.
------------
=> fix: display show more on customer details

src/components/form/ComboBox/ComboboxList.tsx, src/components/form/MultipleComboBox/MultipleComboBoxList.tsx
Order alphabetically grouped data in (multi)combobox by header value
=> misc: order alphabetically combobox group values

src/components/form/Radio/Radio.tsx
=> bug: prevent padding in radio focus ring

src/generated/graphql.tsx
Adding IRR (Iranian Rial) currency
Originally from https://github.com/getlago/lago-front/pull/1575 but re-opened to fix CI unreachable GH token issue.
Thanks for the contribution @AnonC0DER
=> misc(currency) add IRR

src/components/customers/addDrawer/AddCustomerDrawer.tsx, src/styles/muiTheme.ts
Button spacing is needed for the export feature.
The warning silent is just a fix on the path
=> misc: few app improvements

src/pages/CustomerDetails.tsx
ISSUE-367
Grid issue in mobile
| Before | After |
| ------ | ----- |
| <img width="801" alt="Capture d’écran 2024-07-04 à 14 35 00" src="https://github.com/getlago/lago-front/assets/17253055/8e1e0719-6ab5-4f80-ab78-423717b20b32"> | <img width="801" alt="Capture d’écran 2024-07-04 à 14 35 15" src="https://github.com/getlago/lago-front/assets/17253055/0a2e9ab4-32d3-46f8-872e-7880a3a40744"> |
=> fix: customer details grid layout

ditto/base.json, ditto/config.yml, ditto/index.js, src/components/customers/CustomerMainInfos.tsx, src/components/customers/addDrawer/AddCustomerDrawer.tsx, src/components/customers/addDrawer/ExternalAppsAccordion.tsx, src/generated/graphql.tsx
We add a new option in the Stripe PSP config in the customer drawer: Link!
It can only be selected if card is already selected.
=> feat: add link as Stripe method

src/pages/CreatePlan.tsx, src/styles/settingsPage.tsx
=> bug: set correct z-index for nav elements

src/components/customers/addDrawer/ExternalAppsAccordion.tsx
=> misc: fix copy used for PP section

src/components/CodeSnippet.tsx, src/components/designSystem/graphs/AreaChart.tsx, src/pages/settings/EmailScenarioConfig.tsx, src/styles/globalStyle.tsx, src/styles/muiTheme.ts
=> feat: implement new font system

src/components/settings/integrations/XeroIntegrationMapItemDialog.tsx, src/generated/graphql.tsx
This PR simply change a query for Xero, but it's hidden behind a FF anyway
=> bug(xero): fetch accounts in payment mapping modal

src/components/customers/addDrawer/ExternalAppsAccordion.tsx
=> bug: prevent chain form update

src/components/designSystem/NavigationTab.tsx
=> bug: fix tab extra width

src/components/plans/ChargeAccordion.tsx, src/components/plans/ChargeBillingRadioGroup.tsx, src/hooks/customer/useAddSubscription.tsx
ISSUE-400
Field should be disabled if it's used in subscription
=> fix: disabled field and clean form before submitting

src/components/customerPortal/PortalOverview.tsx, src/components/customers/overview/CustomerOverview.tsx, src/generated/graphql.tsx
LAGO-132
Use lazy query for reloading only needed queries and force clear cache 
**QA app:** https://lago-132-app.staging.getlago.com/
=> fix: refresh overdue balance query and invalidate cache

src/components/customers/overview/CustomerOverview.tsx
LAGO-144
We use USD by default if customer does not have a currency set.
We now use organization currency as fallback first.
=> fix: use organization currency as fallback

ditto/base.json, ditto/de.json, ditto/es.json, ditto/fr.json, ditto/it.json, ditto/nb.json, ditto/sv.json, src/components/customerPortal/PortalInvoiceListItem.tsx, src/components/designSystem/Status.tsx, src/generated/graphql.tsx
LAGO-112
Add new Disputed status in portal invoice item
=> feat: add disputed status in customer portal invoice item

src/pages/CreditNoteDetails.tsx
Simply enable something that now works on BE side.
Also apply a minor UI fix
=> feat: allow to sync CN with Xero

src/pages/__devOnly/DesignSystem.tsx
Wanted to have an overview of all DS component to check recent typo change on the same page
=> chore: Simple DS improvement

src/components/designSystem/Filters/QuickFilters.tsx
=> misc: make the quick filters wrap on resize

src/components/GenericPlaceholder.tsx, src/components/designSystem/Table/Table.tsx, src/components/designSystem/Table/index.ts, src/core/utils/responsiveProps.ts, src/pages/__devOnly/DesignSystem.tsx, src/pages/__devOnly/fixtures.ts
LAGO-145
New table component that is not used in the app for the moment
=> feat: new table component

src/components/invoices/InvoicesList.tsx
Missmatch between discussions, we remove the link on customer name.
=> fix: remove link for customer name

src/components/customers/CustomerInvoicesTab.tsx, src/components/customers/overview/CustomerCoupons.tsx, src/components/customers/overview/CustomerOverview.tsx, src/components/customers/overview/CustomerSubscriptionsList.tsx, src/pages/CustomerDetails.tsx
LAGO-146
ISSUE-398
ISSUE-406
- Move Coupons under billing overview
- Apply margin-bottom to customer page
=> fix: multiple fixes on customer pages

.github/workflows/codegen.yml
Change the deprecated command to use the new one for docker compose
=> misc: change docker compose run command in CI

src/components/plans/ChargePercentage.tsx, src/components/plans/StandardCharge.tsx
=> misc: fix some button alignment in plan form

src/components/plans/ChargeAccordion.tsx
This condition should be the same as the above attributes
Fixes ISSUE-407
=> bug: change wrong disabled condition for charge option

src/components/customerPortal/PortalInvoicesList.tsx, src/generated/graphql.tsx
issue-413
we used the wrong attribute to determine if the payment was disputed or not
use paymentDisputeLostAt instead of paymentDisputeLosable
=> fix: use paymentDisputeLostAt instead of paymentDisputeLosable

src/styles/muiTheme.ts
=> misc: small buttons should have caption style

src/components/designSystem/Table/Table.tsx
**Default height**
**New variation height**
=> feat: row height variation

src/components/designSystem/Filters/filtersElements/FiltersItemInvoiceType.tsx, src/components/designSystem/Filters/filtersElements/FiltersItemPaymentStatus.tsx, src/components/designSystem/Filters/filtersElements/FiltersItemStatus.tsx, src/styles/muiTheme.ts
=> bug(filters): display picker on top and filter multiple values

src/pages/CustomersList.tsx
There could be 1 or 2 elements here, so better using gap spacing
Fixes ISSUE-415
=> misc: use gap spacing

src/core/apolloClient/reactiveVars/locationHistoryVar.ts, src/hooks/core/useLocationHistory.ts, src/hooks/customer/useAddSubscription.tsx, src/hooks/useSalesForceConfig.ts, src/pages/CreateInvoice.tsx, src/pages/CreateSubscription.tsx, src/pages/InvitationInit.tsx, src/pages/auth/Login.tsx
This PR aims to adapt the application for users navigating through the salesforce iframe.
When they do, they add to the url `?sfdc=true` and some parts of the app will change accordingly
- login will hide some elements
- on invoice and subscription creation, we'll emit an event to tell salesforce to close the iframe, no navigation will be triggered
=> feat: Salesforce iframe navigation

src/pages/CreateInvoice.tsx, src/styles/mainObjectsForm.tsx
For incoming feature, we need the submit to be part of a sticky bar.
=> misc: sticky bar for one-off form

src/components/plans/details/PlanDetailsAdvancedSettingsSection.tsx
=> bug(plan details) fix minimum commitment display condition

src/components/customers/addDrawer/ExternalAppsAccordion.tsx, src/pages/settings/Integrations.tsx
I don't remove the flag in the enum in case I need it later for other parts to be merged incrementally
=> misc: remove anrok ff usage

src/core/constants/form.ts, src/generated/graphql.tsx, translations/base.json
👉  https://getlago.canny.io/feature-requests/p/{{FEATURE_SLUG}}
Include relevant motivation and context.
=> feat: add missing translations

src/generated/graphql.tsx, src/pages/CreateInvoice.tsx
=> chore(createInvoice): nicely display Anrok tax error

src/components/subscriptions/SubscriptionInformations.tsx, src/pages/PlanDetails.tsx
Could fix some [Sentries](https://lago.sentry.io/issues/5775514762/?alert_rule_id=14434893&alert_type=issue&environment=production&notification_uuid=1d61d9b0-a40e-4ca7-9106-2b2814f617d8&project=6458937&referrer=slack)
=> misc: prevent rendering broken links

src/pages/CreateInvoice.tsx
=> bug(oneOffInvoice) fix tax display from provider

src/components/billableMetrics/BillableMetricCodeSnippet.tsx, src/core/utils/snippetBuilder.ts
Should fix issue-429
Migrate to snippet builder to avoid any extra comma
=> fix: migrate to snippet builder

src/components/plans/ProgressiveBillingSection.tsx, src/generated/graphql.tsx, src/pages/settings/Authentication/Authentication.tsx, src/pages/settings/Integrations.tsx
=> misc(integrations): Anrok hidden behind premium flag

src/generated/graphql.tsx, src/pages/InvoicesPage.tsx
=> misc: request smaller amount of data on retryAllInvoicePayments

src/components/plans/VolumeChargeTable.tsx
=> fix: Fix validation not showing up in the Volume table

src/components/designSystem/Table/Table.tsx, src/pages/__devOnly/DesignSystem.tsx, src/pages/__devOnly/fixtures.ts
=> chore: change default table rowSize

yarn.lock
Fixes https://github.com/getlago/lago-front/security/dependabot/77
=> misc(deps): make sure we use the fixed CVE for micromatch

src/generated/graphql.tsx
Just wanted to have the latest graph update on main, mainly because of the optional name on user even tho it's already handled on our side!
=> misc: update generated graph with last BE version

.github/workflows/release.yml
Runs the release process on the github provided ARM runner. Github released this 7 days ago.
=> chore(Release) - Run release on github actions runner

src/components/addOns/AddOnCodeSnippet.tsx, src/components/coupons/CouponCodeSnippet.tsx, src/components/plans/PlanCodeSnippet.tsx, src/components/taxes/TaxCodeSnippet.tsx, src/pages/CreateAddOn.tsx, src/pages/CreateTax.tsx
We were still using hard coded snippet in the app, this PR aims to migrate them and use the snippet builder instead. 
It also fixes the add-on one, as we were displaying an incorrect snippet.
FIXES ISSUE-433
=> fix: add-on snippet and usage or snippet builder

src/components/customers/overview/CustomerOverview.tsx, src/generated/graphql.tsx, src/pages/CustomerRequestOverduePayment/index.tsx
Updates manual dunning feature to be a premium feature (and no longer premium add-on)
=> fix: remove premium add-on check

src/components/customers/overview/CustomerOverview.tsx, src/pages/CustomerRequestOverduePayment/index.tsx
Disable eslint warning for missing deps as I don't want to include them in the array
=> fix: disable exhaustive dep

yarn.lock
We have some security deps and many long running updated to perform
This PR makes a fresh install and updates the yarn.lock
=> deps: general reinstall of all dependencies using yarn

.eslintrc, package.json, src/components/CodeSnippet.tsx, src/components/customers/usage/CustomerUsage.tsx, src/components/designSystem/Avatar.tsx, src/components/designSystem/Filters/FiltersPanelPoper.tsx, src/components/designSystem/Filters/filtersElements/FiltersItemIssuingDate.tsx, src/components/designSystem/NavigationTab.tsx, src/components/designSystem/graphs/InlineBarsChart.tsx, src/components/form/Checkbox/Checkbox.tsx, src/components/form/DatePicker/DatePicker.tsx, src/components/form/JsonEditor/JsonEditor.tsx, src/components/form/Radio/Radio.tsx, src/components/invoices/details/InvoiceDetailsTableBodyLine.tsx, src/components/invoices/details/InvoiceDetailsTableBodyLineGraduated.tsx, src/components/invoices/details/InvoiceDetailsTableBodyLineGraduatedPercentage.tsx, src/components/invoices/details/InvoiceDetailsTableBodyLinePackage.tsx, src/components/invoices/details/InvoiceDetailsTableBodyLinePercentage.tsx, src/components/invoices/details/InvoiceDetailsTableBodyLineVolume.tsx, src/components/invoices/details/InvoiceFeeAdvanceDetailsTable.tsx, src/components/invoices/details/InvoiceFeeArrearsDetailsTable.tsx, src/components/plans/details/PlanDetailsAdvancedSettingsSection.tsx, src/components/plans/details/PlanSubscriptionList.tsx, src/components/settings/EditOrganizationInvoiceNumberingDialog.tsx, src/layouts/SideNavLayout.tsx, src/pages/Analytics.tsx, src/pages/CreateInvoice.tsx, src/pages/CreditNoteDetails.tsx, src/pages/WalletForm/components/TopUpCard.tsx, yarn.lock
Add eslint plugin for tailwind to prevent adding unknown classes
I've disabled warnings that is related to old code that needs to be migrated.
Related to LAGO-328
=> misc: tailwind eslint

src/components/wallets/WalletAccordion.tsx
=> bug: fix icon alignment in wallet details

src/pages/CustomerRequestOverduePayment/index.tsx
=> bug: request payment footer button width

src/components/invoices/details/InvoiceDetailsTable.tsx, src/components/invoices/details/InvoiceFeeAdvanceDetailsTable.tsx, src/components/invoices/details/InvoiceFeeArrearsDetailsTable.tsx
=> fix: overlapping tailwind classes and custom one

src/components/customers/AddCouponToCustomerDialog.tsx, src/components/form/TextInput/TextInput.tsx, src/components/invoices/details/InvoiceDetailsTable.tsx, src/components/plans/FixedFeeSection.tsx, src/components/settings/EditOrganizationInvoiceNumberingDialog.tsx, src/styles/mainObjectsForm.tsx
Recent tailwind implementation brought some UI glitch.
This PR make sure some are fixed, even tho it's not the perfect way
=> bug: fix few css glitch

src/styles/muiTheme.ts
=> fix: combobox virtualized list not entirely visible

src/components/OverviewCard.tsx, src/components/creditNote/CreditNoteFormCalculation.tsx, src/components/designSystem/graphs/ChartHeader.tsx, src/components/developers/DebuggerEventDetails.tsx, src/components/form/ButtonSelector/ButtonSelector.tsx, src/components/form/JsonEditor/JsonEditor.tsx, src/components/form/Radio/RadioGroupField.tsx, src/components/plans/GraduatedPercentageChargeTable.tsx, src/components/wallets/WalletAccordion.tsx
Tooltip placement was off in some pages
=> fix: tooltip placement

src/styles/muiTheme.ts
This rules breaks the buttons' size in poppers
=> bug: revert breaking css change

src/components/designSystem/ButtonLink.tsx, src/components/designSystem/ShowMoreText.tsx, src/components/designSystem/Status.tsx, src/components/designSystem/Table/ChargeTable.tsx, src/components/designSystem/VerticalMenu.tsx, src/components/designSystem/__tests__/ButtonLink.test.tsx, src/pages/BillableMetricsList.tsx
Includes migration of :
- ButtonLink
- ShowMoreText
- Status
- VerticalMenu
- ChargeTable
Better to review commit by commit
Related to LAGO-329
=> refactor: tailwind migration

src/components/invoices/details/InvoiceDetailsTableBodyLine.tsx, src/components/plans/ChargeAccordion.tsx, src/components/plans/ChargeWrapperSwitch.tsx, src/components/plans/DynamicCharge.tsx, src/components/plans/details/PlanDetailsChargeWrapperSwitch.tsx, src/components/plans/details/PlanDetailsChargesSection.tsx, src/components/subscriptions/SubscriptionCurrentUsageTable.tsx, src/core/constants/form.ts, src/core/formats/intlFormatNumber.ts, src/core/serializers/serializePlanInput.ts, src/generated/graphql.tsx, src/hooks/plans/__tests__/fixture.ts, src/hooks/plans/useChargeForm.tsx, translations/base.json
Some event when received needs to be calculated on the flight, to make pricing more dynamic for complex billing situations.
This PR mostly makes the app handle this new charge model.
Also bring some improvements and adjustments.
Better review commit by commit
Fixes LAGO-163
=> feat: add new Dynamic charge model

src/components/designSystem/graphs/ChartHeader.tsx
Just a bugfix, didn't had time to switch to Tailwind
=> bug: correct chart header text allignment

translations/base.json
=> chore: copy adjustment

src/components/layouts/Settings.tsx
Full width instead of fixed width
=> fix(loading): remove fixed width

src/components/designSystem/Filters/ActiveFiltersList.tsx, src/components/designSystem/Filters/Filters.tsx, src/components/designSystem/Filters/FiltersPanelItemTypeSwitch.tsx, src/components/designSystem/Filters/FiltersPanelPoper.tsx, src/components/designSystem/Filters/InvoiceStatusQuickFilter.tsx, src/components/designSystem/Filters/QuickFilters.tsx, src/components/designSystem/Filters/filtersElements/FiltersItemIssuingDate.tsx, src/components/invoices/InvoicesList.tsx
Main takeaway: I've updated the API of `<QuickFilters>` and `<Filters>` API as some attributes were not used at all. It helped making the implementation easier and if needed we can update them later to add that back
=> misc: update all filters related components to use tailwind

translations/base.json
=> chore: copy update

src/components/customers/addDrawer/ExternalAppsAccordion.tsx
=> bug: apply correct payment provider icon size if default

src/components/designSystem/Typography.tsx, src/pages/__devOnly/DesignSystem.tsx
=> misc(Typography): use tailwind

translations/base.json
=> misc: adjust wording for more clarity

src/components/designSystem/Tooltip.tsx
Tailwind migration
Fixes LAGO-420
=> feat: add tw merge

translations/base.json
=> misc: fix misleading copy

src/components/developers/DebuggerEventDetails.tsx, src/components/developers/EventItem.tsx, src/generated/graphql.tsx, src/pages/developers/Debugger.tsx, translations/base.json
Clickhouse brings some change and made us realise we needed to adapt a bit our events list and details
=> misc: improve events list and details

src/pages/developers/Debugger.tsx, src/pages/developers/WebhookLogs.tsx
=> bug(logs): refetch should use the last args as default query

src/components/settings/integrations/NetsuiteIntegrationMapItemDialog.tsx
Fix data not sent for tax mapping
=> bug: manual payload forge for tax mapping

src/components/developers/DebuggerEventDetails.tsx, src/components/developers/EventItem.tsx, src/components/developers/WebhookLogItem.tsx
I was fixing a bug around those places earlier, so now I take time to switch them to TW
=> misc: some TW migration around events and webhooks

package.json, yarn.lock
Fixes https://github.com/getlago/lago-front/security/dependabot/87
=> deps: upgrade webpack-dev-server

src/components/designSystem/Popper.tsx
Related to tailwind initiative
Migrate popper to tailwind
Fixes LAGO-419
=> feat(popper): migrate to tailwind

src/components/subscriptions/SubscriptionCurrentUsageTable.tsx
=> bug: current usage period uses wrong dateTime

src/core/apolloClient/cacheUtils.ts
=> bug(cache): make sure to no re-fetch active queries on orga switch

package.json, yarn.lock
Fix dependabot alert https://github.com/getlago/lago-front/security/dependabot/88
Fixes ISSUE-557
=> secu: bump eslint for CVE-2024-21539

package.json
Morgane left the company few years ago now, pretty sure she would get annoyed if anyone ask her questions about Lago 😄 
This PR adds the Lago tech email in package's author section
=> misc: update package author section

src/components/RouteWrapper.tsx
While investigating about new routing system, was just turning this component to TW
=> misc(RouteWrapper): use tailwind

src/components/designSystem/Chip.tsx
Rewrite the styled component to tailwind. 
Small change. Tried to remove the important, but it seems like the UI is impacted, so decided to keep it.
=> refactor(Chip): rewrite styled component to tailwind

src/components/designSystem/Button.tsx
Use tailwind instead of styled-component
| Before | After |
| --- | --- |
| <img width="2326" alt="Capture d’écran 2024-11-27 à 16 28 56" src="https://github.com/user-attachments/assets/df01bdd0-1a0b-490c-bb59-7b7f78cebe78"> | <img width="2326" alt="Capture d’écran 2024-11-27 à 16 31 59" src="https://github.com/user-attachments/assets/18f877f7-26b1-48ec-b8c3-66f1cf88b4f9"> |
Fixes LAGO-417
=> feat: migrate button to tailwind

src/components/settings/dunnings/DeleteCampaignDialog.tsx, src/core/router/SettingRoutes.tsx, src/generated/graphql.tsx, src/hooks/useCreateEditDunningCampaign.ts, src/layouts/Settings.tsx, src/pages/settings/Dunnings/CreateDunning.tsx, src/pages/settings/Dunnings/Dunnings.tsx, translations/base.json
Related to automatic dunning feature
Introduce the edit/delete part of the dunning feature.
I have extracted the create/edit logic into a custom hook. 
Fixes LAGO-552
=> feat: edit/delete dunnings

src/components/designSystem/Skeleton.tsx
also fixes combobox loading state
=> bug(Skeleton): prevent non text loading to take full width

src/styles/muiTheme.ts
=> misc: remove MUI warning

src/styles/muiTheme.ts
I merged recently some style of the accordion in the MUI config, and wrote some incorrectly
This PR fixes the interractions styles
=> bug: wrong interaction style definition

src/components/form/ButtonSelector/TabButton.tsx, src/components/form/Switch/Switch.tsx
https://styled-components.com/docs/faqs#nested-syntax-handling
=> bug: adjust styles that been broken after recent package bump

src/components/designSystem/Drawer.tsx
As part of our ongoing journey to migrate from styled components to tailwind, the Drawer component also needed refactoring.
This was done on a commit-per-component basis in order to aid the code reviewer (so the reviewer can easily spot any obvious differences or missing styles).
Fixes LAGO-424
=> (refactor): Refactor drawer to tailwind

src/components/OrganizationLogoPicker.tsx, src/components/PremiumWarningDialog.tsx, src/components/form/ComboBox/ComboBoxInput.tsx, src/components/form/DatePicker/DatePicker.tsx, src/components/invoices/EditInvoiceItemTaxDialog.tsx, src/components/plans/ChargePercentage.tsx, src/components/plans/GraduatedChargeTable.tsx, src/components/plans/GraduatedPercentageChargeTable.tsx, src/components/plans/ProgressiveBillingSection.tsx, src/components/plans/VolumeChargeTable.tsx, src/layouts/CustomerInvoiceDetails.tsx, src/layouts/Settings.tsx, src/layouts/SideNavLayout.tsx, src/pages/CustomerDetails.tsx, src/pages/WalletForm/WalletForm.tsx, src/pages/auth/ResetPassword.tsx, tailwind.config.ts
Migrate styled(Button) into tailwind classes
=> fix: migrate styled(Button)

src/components/coupons/AddBillableMetricToCouponDialog.tsx, src/components/coupons/AddPlanToCouponDialog.tsx, src/components/invoices/EditInvoiceDisplayName.tsx, src/components/invoices/EditInvoiceItemDescriptionDialog.tsx, src/pages/CreateCreditNote.tsx
We recently updated TS in our app and some new linter are configured to show some warnings.
Those are to be solved along the way, and this is just a small attempt for few of them.
Gonna be a long road.
=> misc: fix some ts warnings

src/components/plans/ChargeAccordion.tsx, translations/base.json
We allow to remove the default pricing in a subscription even tho it should not happen
This PR disables the button in that specific case and shows a specific message on hover's tooltip
Fixes ISSUE-571
=> bug: prevent deletion of default filter price in subscription form

src/components/form/ButtonSelector/ButtonSelector.tsx
Took the opportunity to remove weird margin bottom rule
Fixes LAGO-435
=> misc(ButtonSelector): migrate to tailwind

src/components/customers/AddCouponToCustomerDialog.tsx, src/components/customers/CustomerInvoicesList.tsx, src/components/customers/CustomerInvoicesTab.tsx
Just random component migration
=> misc: migrate some components to tailwind

src/components/form/AmountInput/AmountInput.tsx, src/components/form/AmountInput/AmountInputField.tsx
=> misc(AmountInput): migrate to Tailwind

src/components/designSystem/Dialog.tsx
Migrate Dialog to tailwind by removing the styled components.
Fixes LAGO-423
=> [tailwind] Refactor Dialog to tailwind

src/components/form/Switch/Switch.tsx, tailwind.config.ts
Tailwind migration
Migrate Switch component
Fixes LAGO-428
=> refactor: migrate switch to tailwind

nginx/nginx.conf
Whitelist Store Commander's domains to enable access to customer portal
=> chore: extend frame-ancestors list

package.json, yarn.lock
Fixes https://github.com/getlago/lago-front/security/dependabot/90
=> deps: fix CVE path-to-regexp

src/components/auth/GoogleAuthButton.tsx, src/components/designSystem/Avatar.tsx, src/components/designSystem/Popper.tsx, src/components/designSystem/Toasts/Toast.tsx, src/components/plans/ChargeAccordion.tsx, src/core/serializers/serializePlanInput.ts, src/generated/graphql.tsx
We have bunch or linter warning. While looking into two files I just removed the ones there
=> misc: remove some lint warnings

src/components/layouts/Pages.tsx, src/pages/developers/ApiKeysForm.tsx, src/pages/settings/Dunnings/CreateDunning.tsx, src/styles/mainObjectsForm.tsx
In order to stay consistent in the code
This PR should use global layout instead of recreating the same custom layout for dunnings
=> refactor: use centered layout for dunnings

src/components/settings/invoices/PreviewCustomSectionDrawer.tsx, src/generated/graphql.tsx, src/pages/settings/Invoices/CreateCustomSection.tsx, translations/base.json
Related to bank details initiative
This PR handles the drawer to preview invoice custom section
Fixes LAGO-538
=> feat: preview custom section

src/components/customers/CustomerMainInfos.tsx, src/components/customers/subscriptions/SubscriptionLine.tsx, src/components/designSystem/Alert.tsx, src/components/developers/CreateWebhookDialog.tsx, src/components/developers/WebhookLogDetails.tsx, src/components/form/ButtonSelector/TabButton.tsx, src/components/invoices/EditInvoiceItemTaxDialog.tsx, src/components/plans/ChargePercentage.tsx, src/components/plans/CommitmentsSection.tsx, src/components/plans/GraduatedChargeTable.tsx, src/components/plans/GraduatedPercentageChargeTable.tsx, src/components/plans/PlanItem.tsx, src/components/plans/PlanSettingsSection.tsx, src/components/plans/ProgressiveBillingSection.tsx, src/components/plans/VolumeChargeTable.tsx, src/components/settings/members/CreateInviteDialog.tsx, src/components/wallets/WalletAccordion.tsx, src/components/wallets/WalletTransactionListItem/ListItem.tsx, src/layouts/CustomerInvoiceDetails.tsx, src/layouts/SideNavLayout.tsx, src/pages/AddOnsList.tsx, tailwind.config.ts
Still migrating our components to tailwind to get rd rid of styled components.
This PR is the first part of moving all the `styled(Typography)` to use Tailwind classes instead
I'll open a second PR very soon
=> misc: migrate styled typography to tailwind part I

src/components/designSystem/Table/Table.tsx
Apply row size to tbody rows only (and not thead)
=> fix: table thead row size

src/components/customers/addDrawer/AddCustomerDrawer.tsx, src/components/customers/addDrawer/CustomerInformation.tsx
To prepare the refactoring of create customer drawer into a specific page. I'll extract the customer information into a specific component.
=> refactor: extract customer information

src/pages/CreatePlan.tsx, tailwind.config.ts
Migrate the styled components from the Create plan page to tailwind.
=> refactor(tailwind): CreatePlan page

src/components/customers/CustomerInvoicesList.tsx, src/components/designSystem/Table/Table.tsx, src/components/invoices/InvoicesList.tsx, src/generated/graphql.tsx
A customer mentioned it would be great to have this action "issue a credit note" from the invoice item actions directly
Fixes ISSUE-616
=> misc(invoice-list-item): add issue a credit note action

src/pages/AddOnsList.tsx, src/pages/CouponsList.tsx
Making sure the same data is displayed the same in all lists
=> misc: align customersCount display in lists

src/pages/AddOnsList.tsx, src/pages/BillableMetricsList.tsx, src/pages/CouponsList.tsx, src/pages/CustomersList.tsx, src/pages/PlansList.tsx
QA feedback after I replaces the list component there.
Not having the icon (or avatar) next to the item makes all pages look the same and lead to confusion.
QAed by product
=> misc: restore list item icon

src/components/form/MultipleComboBox/MultipleComboBox.tsx
Regression of MultipleCombobox component
=> fix(MultipleCombobox): regression chevron and clear icon wrong size

src/components/customers/CustomerInvoicesList.tsx, src/components/invoices/InvoicesList.tsx, src/pages/InvoicesPage.tsx, translations/base.json
Update copy & severity for the payment processor toast
=> refactor(paymentProcessorToast): Update payment handling toast

src/components/customers/createCustomer/CustomerInformation.tsx, src/pages/CreateCustomer.tsx
Feels very laggy to type in here. It does not fixes everything but improves it a bit
=> misc: slightly improve customer info perf

translations/base.json
Well, last improvement needed some improvement too
=> misc: improve improved Okta setup copy

src/components/designSystem/Icon/mapping.tsx, src/public/icons/partially-filled.svg
Related to partial payment
New icon
Fixes LAGO-671
=> feat: add new partially filled icon

src/generated/graphql.tsx
Needed cause we add new flag on orga level and some orga already use it
=> misc: get last codegen

src/components/invoices/details/InvoiceDetailsTable.tsx
Adding fee should only be possible on draft invoices
=> bug: add fee only available on draft invoices

src/generated/graphql.tsx
Backend added needed properties to some inputs so exporting will work again
=> chore(graphql): generate types

src/components/designSystem/Table/HorizontalDataTable.tsx
This component is not used on production yet.
It's built for the new analytics section of the app.
This component will have some click interactions that needs to be passed by props.
I also updated the style used to place virtualised elements in the DOM, using `absolute` `left` position rather than `transform` `translateX`
=> misc: HorizontalDataTable can interact with given data index state

src/components/subscriptions/SubscriptionUsageLifetimeGraph.tsx, translations/base.json
Issue reported about 404 error on lifetime usage
The PR handles warnings and remove stack usage 
Fixes ISSUE-686
=> fix: handle not found error for lifetime usage

src/components/designSystem/Table/HorizontalDataTable.tsx
We're building a new analytics page and we're at the step of creating the few components that will be used there
HorizontalDataTable was already merged even tho it's not used. I realised during revenus streams page implementation that it has to be updated to fit our needs.
Mostly affect some loading, hover and UI stuffs.
=> misc: adjust HorizontalDataTable behaviors

src/components/PaymentProviderChip.tsx, src/components/customers/CustomerMainInfos.tsx, src/components/customers/createCustomer/ExternalAppsAccordion/PaymentProvidersAccordion.tsx, src/generated/graphql.tsx, translations/base.json
- Add crypto support
- Refactor a bit the file to avoid repeating `onPaymentSet` function 
- Removing eslint warnings and Stack usage
Status: QA review in progress
=> feat: add stripe crypto payment method

package.json, yarn.lock
Should fix https://github.com/getlago/lago-front/security/dependabot/93
=> secu: fix CVE #93

src/components/billableMetrics/CustomExpressionDrawer.tsx, src/components/designSystem/Filters/utils.ts, src/components/wallets/WalletAccordion.tsx, src/components/wallets/WalletTransactionListItem/__tests__/index.test.tsx, src/core/timezone/utils.ts
Remove usage of Date api in favour of luxon
Fixes ISSUE-691
=> fix: remove usage of Date api in favour of DateTime 

src/components/customers/CustomerMainInfos.tsx, src/components/customers/createCustomer/ExternalAppsAccordion/PaymentProvidersAccordion.tsx, src/components/designSystem/Status.tsx, src/core/constants/statusInvoiceMapping.ts, src/generated/graphql.tsx, translations/base.json
Add support for stripe bank transfers
QA approved
=> feat: add support for stripe bank transfers

src/components/designSystem/Filters/filtersElements/FiltersItemStatus.tsx, src/components/invoices/details/InvoiceDetailsTableFooter.tsx
- Display a placeholder when invoice has status : `pending`
- Add pending filter 
Fixes issue-699
=> fix: pending invoices details page + filters

src/layouts/SideNavLayout.tsx, src/styles/designSystem/MenuPopper.tsx, tailwind.config.ts
Styling changes
Related to issue-703
=> fix: extra padding on menu popper in side nav

package.json, yarn.lock
Fixes https://github.com/getlago/lago-front/security/dependabot/93
=> chore: fix CVE #93

src/generated/graphql.tsx, src/pages/settings/EmailSettings.tsx
Back-end have updated and merge the schema and the FE is no longer in sync.
This PR should fix the issue until an engineer jump on the feature.
=> fix: support payment receipt created type on emails

src/components/customers/subscriptions/SubscriptionDatesOffsetHelperComponent.tsx, src/pages/CreateAddOn.tsx, src/pages/CreateBillableMetric.tsx, src/pages/CreateCoupon.tsx, src/pages/CreateInvoice.tsx, src/pages/CreateSubscription.tsx, src/pages/CustomerRequestOverduePayment/components/FreemiumAlert.tsx, src/pages/CustomerRequestOverduePayment/components/RequestPaymentForm.tsx, src/pages/CustomerRequestOverduePayment/index.tsx, src/pages/Error404.tsx, src/pages/Forbidden.tsx, src/pages/Invitation.tsx, src/pages/WalletForm/WalletForm.tsx, src/pages/WalletForm/components/TopUpCard.tsx, src/pages/auth/GoogleAuthCallback.tsx, src/pages/auth/Login.tsx, src/pages/auth/OktaAuthCallback.tsx, src/pages/auth/ResetPassword.tsx, src/pages/auth/SignUp.tsx, src/pages/developers/Debugger.tsx, src/pages/developers/WebhookLogs.tsx, src/pages/settings/EmailScenarioConfig.tsx, src/pages/settings/Members.tsx, src/styles/designSystem/PageHeader.tsx
Part of the Tailwind Migration
Migrate files in `pages` folder
=> refactor: pages migration

src/components/analytics/RevenueStreamsOverviewSection.tsx, src/components/designSystem/Filters/FiltersPanelItemTypeSwitch.tsx, src/components/designSystem/Filters/__tests__/utils.test.ts, src/components/designSystem/Filters/filtersElements/FiltersItemCountry.tsx, src/components/designSystem/Filters/filtersElements/FiltersItemCustomerType.tsx, src/components/designSystem/Filters/filtersElements/FiltersItemDate.tsx, src/components/designSystem/Filters/filtersElements/FiltersItemPlanCode.tsx, src/components/designSystem/Filters/filtersElements/FiltersItemSubscription.tsx, src/components/designSystem/Filters/types.ts, src/components/designSystem/Filters/utils.ts, src/components/designSystem/graphs/MultipleLineChart.tsx, src/generated/graphql.tsx, translations/base.json
We're building the new analytics section of the app. This section is not accessible yet and we're pushing code piece by piece.
This PR adds the new filters needed for the revenue streams query. It makes sure it's correctly implemented with the existing filters system and has proper tests for formating
=> misc: add new filters for revenue streams

src/components/analytics/RevenueStreamsOverviewSection.tsx, src/components/designSystem/Filters/__tests__/utils.test.ts, src/components/designSystem/Filters/utils.ts, src/components/designSystem/graphs/MultipleLineChart.tsx, src/components/designSystem/graphs/__tests__/utils.test.ts, src/components/designSystem/graphs/utils.ts, src/generated/graphql.tsx
Add tests to some to existing methods for revenue streams
Also had to adapt the graph name and collection with the new schema
=> misc: extract revenue sreams methods for testing

src/components/designSystem/Avatar.tsx, src/components/designSystem/Icon/Icon.tsx, src/pages/__devOnly/DesignSystem.tsx
Related to wallet improvement 
Add new avatar badge
=> feat: add new avatar badge component

src/core/apolloClient/cache.ts
Broken payment list due to cache issue
Forgot to add the query in the cache file to merge items in infinite list
Fixes issue-723
=> fix(paymentList): merge cache issue

src/components/analytics/RevenueStreamsOverviewSection.tsx, src/components/designSystem/Filters/__tests__/utils.test.ts, src/components/designSystem/Filters/utils.ts
This PR makes sure the date format is correct according to the selected filter.
This introduces a new filter util with it's corresponding tests.
| Format | Display |
|--------|---------|
| Daily | ![image](https://github.com/user-attachments/assets/eb4ffc06-a190-4e30-a100-188dcf1d8a25) |
| Weekly | ![image](https://github.com/user-attachments/assets/da531f54-998a-40dc-a3d9-ecbe9540f7df) |
| Monthly | ![image](https://github.com/user-attachments/assets/3b3c6864-e6b0-4ce3-9157-a940a7e0951c) |
=> misc: format date correctly in table's header

src/components/form/DatePicker/DatePicker.tsx
Add red color if the helper text is an error
=> fix(datepicker): error message color

src/components/designSystem/NavigationTab.tsx
This is an improvement needed for the new analytics page. 
There is the need to have 2 navigation tab system in the same page.
This PR allows the navigation tab to be run without relying on the page URL but rather on the tabs index number.
pretty easy as internally it relies on a `value` that correspond to the selected tab index.
Doing so, we prevent any URL search params update and make it seamless to add any numbers of tabs in the same page.
The only inconvenience is that the url cannot be shared on those index-based tabs.
This was found as a quick win rather than having to update the whole filters and tab url management system
=> misc(NavigationTab): allow to rely on tab index rather than url link

src/components/wallets/CustomerWalletList.tsx, src/components/wallets/WalletAccordion.tsx, src/components/wallets/WalletDetailsDrawer.tsx, src/components/wallets/WalletTransactionList.tsx, src/components/wallets/WalletTransactionListItem/ListItem.tsx, src/components/wallets/WalletTransactionListItem/__tests__/index.test.tsx, src/components/wallets/WalletTransactionListItem/index.tsx, src/generated/graphql.tsx, src/main.css, tailwind.config.ts, translations/base.json
Related to wallet improvements
- We are displaying a new drawer to display wallet details
- We are updating the layout a bit
- We handle a new failed status
Fixes LAGO-774
**Note: Needs QA to be performed**
=> feat: wallet details

src/components/analytics/mrr/useMrrAnalyticsOverview.ts, src/components/analytics/revenueStreams/useRevenueAnalyticsOverview.ts, src/generated/graphql.tsx
Might cause some infinite loading stage
=> misc: make sure we notify change on query invocation

src/components/customerPortal/usage/UsagePage.tsx, src/components/customers/usage/SubscriptionUsageDetailDrawer.tsx, src/components/subscriptions/SubscriptionCurrentUsageTable.tsx
=> feat: add refresh button on usage drawer

src/components/analytics/mrr/__tests__/utils.test.ts, src/components/analytics/mrr/utils.ts, src/components/designSystem/NavigationTab.tsx, src/core/utils/featureFlags.ts, src/pages/analytics/NewAnalytics.tsx
MRR new graph is made visible for those who have the correct premium addon (only lago ppl for now)
This PR remove the FE feature flag to show the new MRR page in the UI.
It also takes care of fixing some navigation gaps we had.
Better reviewed commit by commit
=> misc: release analytics and improve navigation

src/components/creditNote/CreditNotesTable.tsx
useless cause the table component is handling the loading state internally, and the styled-component style was only used for the loading here.
The loading state is already given to the Table invocation here.
=> misc(CreditNoteTable): remove warnings and styled components

package.json, src/components/ErrorBoundary.tsx, src/core/apolloClient/init.ts, src/main.tsx, yarn.lock
Make it more aggressive and reduce occurrences later
Fixes ISSUE-717
=> misc: improve our Sentry setup

src/components/developers/CreateWebhookDialog.tsx, src/components/developers/WebhookLogDetails.tsx
=> refactor: developers pages

src/components/customers/CustomerPaymentsList.tsx, src/components/invoices/InvoicePaymentList.tsx, src/components/invoices/PaymentsList.tsx, src/generated/graphql.tsx, src/hooks/paymentReceipts/useDownloadPaymentReceipts.ts, src/pages/PaymentDetails.tsx, src/pages/settings/EmailScenarioConfig.tsx, src/pages/settings/EmailSettings.tsx, translations/base.json
Since now we create payment receipts, added buttons for downloading them.
- Created a reusable hook since this will be added to multiple places in the future (invoices tables / lists)
- Added the button to existing Payments tables
- Create a new email template for payment receipts
=> feat: Download payment receipts

src/components/customers/CustomerSettings.tsx, src/components/customers/EditCustomerInvoiceCustomSectionsDialog.tsx, src/generated/graphql.tsx
Backend has renamed an attributes so we need to reflect changes on our side.
Related back-end PR: https://github.com/getlago/lago-api/pull/3439
=> fix(InvoiceCustomSection): rename applicable into configurable 

src/components/creditNote/CreditNoteEstimationLine.tsx
=> misc: fix credit note calculation loading state

src/components/subscriptions/SubscriptionUsageTabContent.tsx, src/generated/graphql.tsx
Issue when displaying customer usage from the plan url, because on this route, customerId was not provided.
Fixes issue-840
=> fix(issue-840): fetch customerId

src/components/designSystem/graphs/StackedBarChart.tsx, src/components/designSystem/graphs/fixtures.ts
Fixes after first round of QA.
- Improved the loading state
- Removed double 0$ when the chart didn't have positive / negative values
=> fix(AnalyticsPrepaidCredits): improve loading state / remove double 0$

src/components/customers/overview/CustomerSubscriptionsList.tsx, src/generated/graphql.tsx
Display all subscriptions
Fixes issue-842
=> feat: display all subscriptions

src/pages/CreateCustomer.tsx
=> bug: make sure avalara data is populated in form if present

src/core/utils/__tests__/copyToClipboard.test.ts, src/core/utils/copyToClipboard.ts, translations/base.json
Attempt to fix copy to clipboard function that sometimes fails
Fixes issue-844
=> fix: improve copy to clipboard function

src/pages/developers/ApiKeys.tsx
Display dates with timezone
Fixes issue-830
=> fix: dates with timezones

src/components/form/Radio/RadioGroupField.tsx, src/components/graphs/Gross.tsx, src/components/graphs/Invoices.tsx, src/components/graphs/Mrr.tsx, src/components/graphs/Overview.tsx, src/components/graphs/Usage.tsx, src/components/invoices/EditInvoiceItemDescriptionDialog.tsx, src/components/invoices/EditInvoiceItemTaxDialog.tsx, src/components/invoices/InvoiceCreditNoteList.tsx, src/components/plans/ChargeFilter.tsx, src/components/wallets/VoidWalletDialog.tsx, src/hooks/plans/useChargeForm.tsx
Some TW migration and template adjustments
=> misc: Some TW migration and template adjustments

src/components/customers/overview/CustomerSubscriptionsList.tsx, src/generated/graphql.tsx
It can happen a subscription has no `startedAt` in some specific cases. mostly when it's a next sub attached to a parent one that have been terminated. There is ongoing discussions about if those kind of sub should be removed or not but this Pr at least fixed the "invalid datetime" displayed in UI
Related to ISSUE-866 but does not entirely fix
=> misc: display dash if no sub startedAt

packages/configs/tailwind.config.ts, src/components/plans/ChargeBillingRadioGroup.tsx, src/components/plans/ChargePercentage.tsx, src/components/plans/ChargesSection.tsx, src/components/plans/CommitmentsSection.tsx, src/components/plans/CustomCharge.tsx, src/components/plans/DynamicCharge.tsx, src/components/plans/FixedFeeSection.tsx, src/components/plans/GraduatedChargeTable.tsx, src/components/plans/GraduatedPercentageChargeTable.tsx, src/components/plans/PackageCharge.tsx, src/components/plans/PlanSettingsSection.tsx, src/components/plans/ProgressiveBillingSection.tsx, src/components/plans/StandardCharge.tsx, src/components/plans/VolumeChargeTable.tsx
More tailwind migration. Focusing on some plan form components. More to come
=> misc: migrate some plan component to TW and fix warnings

src/components/customers/overview/CustomerSubscriptionsList.tsx
Table is handling the loading state but was never shown
=> misc: show subscription table on loading

src/components/graphs/Invoices.tsx
I recently rewrite this component to use TW and messed up with the loading state. This fixes it
=> bug: better invoice graph loading

.vscode/lago.code-snippets, packages/configs/tailwind.config.ts, src/components/invoices/InvoiceCustomerInfos.tsx, src/components/invoices/Metadatas.tsx, src/components/invoices/details/InvoiceDetailsTableBodyLine.tsx, src/components/invoices/details/InvoiceDetailsTableFooter.tsx, src/pages/CustomerDraftInvoicesList.tsx, src/pages/CustomerInvoiceDetails.tsx, src/pages/InvoiceOverview.tsx
Some TW migration and warning removal.
Some TW changes are not ISO cause I fix the style while migrating
=> misc: migrate some styled components to tailwind

src/components/plans/ChargeAccordion.tsx, src/components/plans/ChargeOptionsAccordion.tsx
Checked all UI to make sure it's not broken.
Also removed some style that was a duplicate of the theme override.
=> misc: use TW in charge components

src/components/subscriptions/SubscriptionCurrentUsageTable.tsx
Make sure to check on length as boolean or it shows a 0 in the UI
Reported by a customer
Fixes ISSUE-887
=> bug: make sure to check on array lenght as boolean

src/layouts/SideNavLayout.tsx, src/pages/AddOnsList.tsx, src/pages/BillableMetricsList.tsx, src/pages/CouponsList.tsx, src/pages/CustomersList.tsx, src/pages/PlansList.tsx
Fixing the layout because sometimes we had multiple scrollbars.
**Before**
With the audit-log feature, we sometimes had 3 scrollbars.
**After:**
=> fix: update layout due to multiple scrollbars

src/components/analytics/usage/UsageBreakdownIndividualSection.tsx, src/components/analytics/usage/useUsageAnalyticsBreakdown.ts
- Fix amount cents display
- Pass granularity filter to breakdown sections
=> feat(Analytics): Usage - fixes

src/components/developers/events/Events.tsx, src/components/developers/webhooks/WebhookLogs.tsx
New developer console
Fixed event selection behavior by automatically selecting the first event/log item after data refetch in both Events and WebhookLogs components. 
This ensures users always have a selected item to view after refreshing the data.
=> fix: select first event on refetch

src/components/customers/CustomerInvoicesList.tsx, src/components/customers/CustomerInvoicesTab.tsx
We want the finalised and draft invoices list in customer details view to have the same data prompted.
This PR fixes it.
Fixes ISSUE-901
=> misc: unify finalised and draft customer invoice list

cypress/e2e/10-resources/t30-create-bm.cy.ts, src/components/billableMetrics/BillableMetricDetailsOverview.tsx, src/core/constants/tabsOptions.ts, src/core/formats/formatBillableMetricsItems.ts, src/core/router/ObjectsRoutes.tsx, src/generated/graphql.tsx, src/hooks/useCreateEditBillableMetric.ts, src/pages/BillableMetricDetails.tsx, src/pages/BillableMetricsList.tsx, src/pages/CreateBillableMetric.tsx, translations/base.json
For activity logs, we want to introduce a new billable metric details page
This PR :
- Adds a new details page
- Extract some formatting function to display the same label for enums
- Update the creation form to handle new duplicate feature
=> feat: new billable metric details page

src/pages/CreateInvoice.tsx
After a one-off invoice creation, let's redirect the user to the invoice details page!
Fixes ISSUE-900
=> misc: redirect to invoice details after creation

src/components/developers/DevtoolsRouter.tsx, src/components/developers/DevtoolsView.tsx, src/core/utils/featureFlags.ts
Remove activity log feature flag
=> fix: remove activity logs FF

src/components/settings/integrations/AddAvalaraDialog.tsx, src/components/settings/integrations/AddHubspotDialog.tsx, src/components/settings/integrations/AddNetsuiteDialog.tsx, src/components/settings/integrations/AddSalesforceDialog.tsx, src/components/settings/integrations/AddXeroDialog.tsx, translations/base.json
We are not handling auth error during avalara integration creation.
This PR catch the auth error in this form and unify error messages for other integrations
Fixes ISSUE-923
=> bug(Avalara): catch auth error and display correct message

src/components/graphs/Usage.tsx
Fix loading for this graph
Fixes ISSUE-924
=> bug: fix usage graph loading

packages/configs/package.json, pnpm-lock.yaml
Noticed we have a gap between declared and installed version across packages, and specifically in the config package.
Fixing them
=> deps: unify versions in config package

cypress/support/e2e.ts, src/components/TimezoneDate.tsx, src/components/coupons/DeleteCouponDialog.tsx, src/components/designSystem/ButtonLink.tsx, src/components/designSystem/Toasts/ToastContainer.tsx, src/components/designSystem/graphs/StackedBarChart.tsx, src/components/form/AmountInput/AmountInput.tsx, src/components/form/ComboBox/ComboBox.tsx, src/components/form/DatePicker/DatePicker.tsx, src/components/form/MultipleComboBox/MultipleComboBox.tsx, src/components/plans/ChargePercentage.tsx, src/core/formats/__tests__/formatCreditNotesItems.test.ts, src/pages/CreateBillableMetric.tsx, src/pages/CreateTax.tsx
Fixing some eslint warnings, nothing crazy
=> misc: remove some linter warnings

src/components/activityLogs/utils.tsx, src/components/developers/activityLogs/ActivityLogDetails.tsx, src/generated/graphql.tsx
Missing invoiceId Params in URL
=> fix: use invoiceId on url params

src/components/activityLogs/utils.tsx, src/components/developers/activityLogs/ActivityLogDetails.tsx
Related to: https://lago.sentry.io/issues/6581756497/?referrer=slack&notification_uuid=537ffab5-b092-431b-80ca-0d56fce68978&environment=production&alert_rule_id=14434893&alert_type=issue
=> fix: no hyperlinks for deleted activity type

src/components/customers/overview/CustomerSubscriptionsList.tsx, src/components/designSystem/Filters/FiltersPanelItemTypeSwitch.tsx, src/components/designSystem/Filters/filtersElements/FiltersItemHttpMethods.tsx, src/components/designSystem/Filters/filtersElements/FiltersItemHttpStatuses.tsx, src/components/designSystem/Filters/filtersElements/FiltersItemRequestPath.tsx, src/components/designSystem/Filters/types.ts, src/components/designSystem/Filters/utils.ts, src/components/designSystem/Status.tsx, src/components/developers/DevtoolsRouter.tsx, src/components/developers/apiLogs/ApiLogDetails.tsx, src/components/developers/apiLogs/ApiLogs.tsx, src/components/developers/apiLogs/ApiLogsTable.tsx, src/components/developers/apiLogs/mapping.tsx, src/components/developers/views.ts, src/core/apolloClient/cache.ts, src/core/constants/filters.ts, src/generated/graphql.tsx, translations/base.json
This PR should introduce API log in the developer console
- It adds new filters
- New route in the console
Status: QA approved
=> feat: API logs in developer console

packages/design-system/src/components/Tooltip.tsx
Initially opened here: https://github.com/getlago/lago-front/pull/2293
=> refactor(design-system): 🔨 add more accessibility to tooltip

translations/base.json
=> misc: adjust recent copy addition

src/components/customers/overview/CustomerCoupons.tsx, src/generated/graphql.tsx
We don't display display coupon code in customer coupon list, that can lead to unclear data display.
Added the code as a new column
Fixes ISSUE-981
=> misc: display coupon code in customer coupon list

src/pages/settings/Members.tsx
Rollback until we find the root cause of some issues we're encountering
=> fix: remove rule to delete member

.dockerignore, Dockerfile
Related to https://github.com/getlago/lago-front/pull/2317
Reopening the PR to run the CI
Thanks @Harbinder04 for your contrib 🙏
=> bug: added .dockerignore file

package.json, pnpm-lock.yaml
Bump `@nangohq/frontend` version to solve [CRITICAL CVE](https://github.com/getlago/lago-front/security/dependabot/111) related to `form-data`
|Before | After |
|-|-|
|<img width="366" height="309" alt="image" src="https://github.com/user-attachments/assets/d72119ac-af1a-4a68-af52-09bc426dab27" /> |<img width="348" height="322" alt="image" src="https://github.com/user-attachments/assets/937f5fa3-551a-4c33-90f4-11ccaa92c8ca" /> |
=> deps: bump @nangohq/frontend

src/components/customers/CustomerInvoicesList.tsx, src/components/customers/CustomerInvoicesTab.tsx
Just a few improvement in the customer invoice list.
Loading was a bit erratic depending on some conditions. It now rely more in the `<Table />` inner loading stage
Fixes ISSUE-1001
=> misc: improve the customer invoice loading experience

src/components/TimezoneDate.tsx, src/components/customers/overview/CustomerSubscriptionsList.tsx, src/pages/SubscriptionsPage.tsx
Make sure the 2 subscriptions list uses the same copy pattern for the same informations.
Fixes ISSUE-1000
=> misc: unify subscriptions list typos

src/components/designSystem/InfiniteScroll.tsx, src/components/settings/integrations/IntegrationItemLine.tsx, src/pages/SubscriptionDetails.tsx, src/pages/SubscriptionsPage.tsx, src/pages/features/FeaturesList.tsx
**Fix InfiniteScroll sequential loading by using div wrapper instead of React Fragment**
The InfiniteScroll component requires a proper DOM element wrapper (`<div>`) instead of a React Fragment (`<>`) to function correctly. 
React Fragments don't create actual DOM elements, which breaks the `IntersectionObserver` used for detecting scroll position. 
Without a real scroll container, the infinite scroll triggers multiple times simultaneously instead of sequentially, causing race conditions in data loading. 
```typescript 
<div className="overflow-y-auto">
``` 
wrapper provides the necessary scroll context and DOM reference for the observer to work properly.
Fixes issue-1014
=> fix: infinite list fetch all items

src/components/layouts/Settings.tsx, src/pages/settings/BillingEntity/sections/BillingEntityMain.tsx
Simple spacing improvement, noticed during navigation
=> misc: few spacing adjustments

src/components/invoices/details/InvoiceDetailsTable.tsx
Fixes a regenerate issue introduced after a rebase
=> fix: add missing fees param after rebase

src/components/designSystem/Filters/utils.ts
=> fix(Analytics Usage): map filters

src/components/designSystem/Filters/FiltersPanelItemTypeSwitch.tsx, src/components/designSystem/Filters/__tests__/utils.test.ts, src/components/designSystem/Filters/filtersElements/FiltersItemActiveSubscriptions.tsx, src/components/designSystem/Filters/filtersElements/FiltersItemAmount.tsx, src/components/designSystem/Filters/types.ts, src/components/designSystem/Filters/utils.ts, src/generated/graphql.tsx, src/pages/CustomersList.tsx, translations/base.json
Improvement in customers list to add a new filter by active subscriptions count
Fixes ISSUE-1024
=> feat: filter customers by active subscriptions

src/components/customers/overview/CustomerSubscriptionsList.tsx, src/pages/SubscriptionsPage.tsx, translations/base.json
It now shows "Actions" on hover
=> misc: make subscription actions tooltip more generic

src/components/designSystem/Filters/__tests__/utils.test.ts
Add missing tests for `formatFiltersForQuery`
=> feat(filters): add tests for formatFiltersForQuery

src/components/form/ComboBox/ComboBox.tsx
https://github.com/getlago/lago-front/pull/2408
Reopening to run the CI
=> fix(ComboBox): add dependency to useEffect for rawData updates

src/components/designSystem/Table/ChargeTable.tsx
Remove fixed width in favour of percentage width
=> fix: remove fixed width

src/hooks/useDeveloperTool.tsx
Prevent the clearing of search params.
Fixes ISSUE-1037
=> fix: prevent losing the search params

src/components/form/MultipleComboBox/MultipleComboBoxVirtualizedList.tsx
=> misc: add element index in virtualized list

src/App.tsx, src/hooks/aiAgent/aiAgentReducer.ts, src/hooks/aiAgent/useAiAgent.tsx
To prepare ai-agent feature, this PR should create a new ai agent context to handle:
- new ai panel
- chat interaction
This hook is not used yet
=> feat(ai-agent): introduce new ai agent context

src/components/plans/CommitmentsSection.tsx, src/components/plans/UsageChargeAccordion.tsx, src/components/plans/UsageChargesSection.tsx, src/components/plans/__tests__/UsageChargeAccordion.test.tsx, src/components/plans/details/PlanDetailsAdvancedSettingsSection.tsx, src/components/plans/details/PlanDetailsChargesSection.tsx, src/components/plans/types.ts, src/generated/graphql.tsx, src/pages/CreatePlan.tsx, src/pages/subscriptions/CreateSubscription.tsx
Simple renaming to better match usage and prepare future implementations
=> misc: rename usage charge related elements

src/components/designSystem/Table/ChargeTable.tsx
`td` should not be child of another `td`
=> bug: make sure we don't have td in td
