getlago/lago-front

src/components/form/Switch/Switch.tsx, src/components/plans/PlanForm.tsx
Switch now integrate the label and sublabel to avoid redoing it everywhere
=> feat: 🎛 Switch component update

src/components/designSystem/Typography.tsx, src/components/form/ButtonSelector/ButtonSelector.tsx, src/components/form/Radio/Radio.tsx, src/components/form/TextInput/TextInput.tsx, src/styles/muiTheme.ts
The `Typography` component was too permissive regarding colors and not typed according to our design system.
This is a fix to this
=> chore: 🖍 Type Typography colors

src/components/customers/AddCustomerDialog.tsx, src/components/form/ComboBox/ComboBoxField.tsx, src/components/settings/EditOrganizationInformationsDialog.tsx, src/hooks/useCreateEditCustomer.ts
This MR fixes a behaviour of the combobox component.
We agreed on setting either the value or null when using this component.
So there is no need to force null on each usages.
=> chore: refactor combobox to send either value or null

src/components/addOns/AddOnForm.tsx, src/components/billableMetrics/BillableMetricForm.tsx, src/components/coupons/CouponForm.tsx, src/components/customers/AddAddOnToCustomerDialog.tsx, src/components/customers/AddCouponToCustomerDialog.tsx, src/components/customers/AddCustomerDialog.tsx, src/components/plans/PlanForm.tsx, src/pages/auth/Login.tsx
This MR aims to refactor and uniform some of our form usage and the way we display loading spinners on submit buttons.
`Button` components does show loading spinner automatically if the `onClick` function returns a promise.
Which mean we can remove the `async` / `await` usage in the and run the `submitForm` method everywhere.
This refactor was initiated by this comment: https://github.com/getlago/lago-front/pull/194#discussion_r907458657
=> Uniform formik usage 🥋

webpack.dev.js
This MR fixes the websocket in dev env.
It simply sets the websocket port to use the one already allowed by traefik
Fixes https://github.com/getlago/lago-front/issues/142
=> Set webSocketURL for dev env

src/components/plans/ChargeAccordion.tsx
On add/edit plan, a trash icon was displayed next to each charge name.
If the charge was not deletable, the icon was disabled.
This MR simply hide the trash icon when action is disabled instead.
=> refactor: 🗑 Hide Charge trash icon if not clickable

src/components/form/DatePicker/DatePicker.tsx
We can have disabled range of days in DatePicker. 
Disabled days should have a specific color according to design system.
Had to `!important` otherwise won't work
=> bug: update disabled days color in date picker

src/components/form/DatePicker/DatePicker.tsx, src/components/wallets/UpdateCustomerWalletDialog.tsx
This MR fixed the datePicker position in wallet edit modal.
As the picker position is calculated based on the input size and position (not the calendar icon), I had to manually adjust the picker offset when the picker had to be displayed on the left.
It takes the width of the input (`reference.width`) and removes twice the width of the icon "box" (24*2)
Before
After
=> bug: adjust picker position in edit modal

src/components/form/Radio/Radio.tsx, src/components/plans/ChargeAccordion.tsx
https://www.notion.so/getlago/Charge-s-trash-should-be-display-on-the-right-side-of-the-selector-a926555a55cc406e97d4280310d66e72
=> fix: 🐹 Charge accordion display

.eslintrc, src/components/customers/CustomerInvoicesList.tsx
Enable [no-else-return](https://eslint.org/docs/latest/rules/no-else-return) linter rule in our repo
=> chore: Add linter rule no-else-return

src/components/plans/ChargeAccordion.tsx
Fix focus ring cut on plan form
BEFORE
AFTER
=> fix: ✂️ prevent focus ring cut in plan form

.env.sh, .env.template, src/components/addOns/AddOnCodeSnippet.tsx, src/components/billableMetrics/BillableMetricCodeSnippet.tsx, src/components/coupons/CouponCodeSnippet.tsx, src/components/plans/PlanCodeSnippet.tsx, src/core/apolloClient/init.ts, src/core/apolloClient/reactiveVars/envGlobalVar.ts, src/core/apolloClient/reactiveVars/index.ts, src/core/router/index.tsx, src/hooks/core/useInternationalization.ts, src/index.js, src/layouts/SideNavLayout.tsx, src/pages/auth/Login.tsx, webpack.common.js, yarn.lock
Avoid the need to check `window.` vs global variables in the app and get the variables from the `envGlobalVar` reactivevar
=> chore: 🦷 EnvGlobalVar expose env variables

.github/ISSUE_TEMPLATE/bug.md, ditto/base.json, ditto/config.yml, ditto/index.js, src/App.tsx, src/components/DebugInfoDialog.tsx, src/hooks/ui/__tests__/useShortcuts.test.tsx, src/hooks/ui/useShortcuts.tsx
While a UI problem is reported by a user, today we have no way to easily know some informations. An option would be to have a debug dialog with useful informations in it.
- App environnement (Production, Dev, Staging, Qa)
- Api URL
- Current user id (if logged)
- App version (need a loading state and error state)
→ Dialog is openable on Self-hosted and Cloud version
→ Dialog is openable on any page even if a dialog or a drawer is already displayed.
→ By closing the Env. dialog, the dialog or the drawer remains open
Notion : https://www.notion.so/getlago/Dialog-FE-environment-infos-c618f8db22ea42988e4af446c62da890
=> feat: 🪲 Debug dialog

src/components/plans/VolumeChargeTable.tsx
This fixes an amount display being wrongly 100 time lower than expected for a display
=> bug: 💸 fix amount display in disclaimer

.github/workflows/codegen.yml, .github/workflows/cypress.yml
Codegen and E2E Tests will be now triggered when a PR is created or reopened (only if not draft)
=> chore: 🦬 Fix CI Events

src/pages/CustomerDetails.tsx
When no tab specified, display the first route
=> fix: 🫥 Default route customer details

src/components/customers/subscriptions/CustomerSubscriptionsList.tsx, src/components/customers/subscriptions/SubscriptionItem.tsx
This PR does 2 things in customer subscription list:
- Uses the subscription id for all transactions with the backend
- Uses the subscription external id for the copy to clipboard
=> bug: fix usage of subscription id and externalId

.github/workflows/linter.yml, .github/workflows/tests.yml, .github/workflows/translation-check.yml, .github/workflows/typescript.yml
This PR udpates workflows to be run on pull request instead of push, so it can run on forked lago projects
=> chore: workflows to be run on pull_request

.env.sh, .storybook/main.js, globals.d.ts, jest.config.js, src/core/apolloClient/reactiveVars/envGlobalVar.ts, webpack.common.js
This PR renames `LAGO_SIGNUP_DISABLED` env variable into `LAGO_DISABLE_SIGNUP`.
Reason is that the lago docker compose uses `LAGO_DISABLE_SIGNUP` so the signup disabling was never properly working.
We decided to rename the variable on frontend side to prevent any user to update their configuration after this renaming
=> fix: 🫡 rename LAGO_SIGNUP_DISABLED const

webpack.common.js
App renders a blank page when a process env is not defined (default behaviour)
When Webpack runs, it removes all usages of this variable leading to syntax issues
We force the interpretation of an undefined variable to return a boolean. So we always have a value.
Note we'll also put a default value in lago docker-compose
=> fix(webpack): force process env variable to return a boolean

globals.d.ts, jest.config.js, src/core/apolloClient/reactiveVars/envGlobalVar.ts, webpack.common.js
The env const is always a string, It lead to not be able to "read" the variable value properly
This PR changes the env type to string and fixes the fallbacks associated
This this change, `disableSignUp` remains a `boolean` but `LAGO_DISABLE_SIGNUP` is now a string
=> fix(LAGO_DISABLE_SIGNUP): env var should be interpreted as a string

src/components/settings/members/CreateInviteDialog.tsx
If you try to invite a member that has the same email as an existing membership of the organization, a BE error is received but nothing it shown on the FE side 
This PR reads the error payload to check if an email key is present.
Doing so will display the appropriate error message below the field
=> fix(invite): check for email error in details

src/components/form/ComboBox/ComboBox.tsx, src/components/form/ComboBox/ComboBoxInput.tsx, src/components/form/ComboBox/types.ts, src/components/form/TextInput/TextInput.tsx, src/pages/CreateBillableMetric.tsx, src/pages/__devOnly/DesignSystem.tsx, src/stories/Combobox.stories.tsx
We're planning the development of a new feature.
During the scoping, we figured out that combobox that displays values with your losses their context once a value is selecter.
This PR adds the groupe value before the value itself in the input. Its placed in the input `startAdorment` and does not affect the value itself, only the input display.
This "feature" is only enabled if you passe a value to `renderGroupHeader`.
=> feat(combobox): Display group in startAdorment

src/components/customers/subscriptions/AddSubscriptionDrawer.tsx
When overriding a plan, the subscription date was empty
This PR makes the subscription date persistent
=> bug(plan) overriding a plan should keep it's subscription date

src/components/customers/CustomerItem.tsx, src/pages/CustomersList.tsx
On small screen, just before the breakpoint, the customer name is not shown in customer list
This PR reduce the subscriptions column size that don't needs to be that big, in order to give more space to the customer name column.
|before|after|
|-|-|
|<img width="537" alt="image" src="https://user-images.githubusercontent.com/5517077/200530097-5551310e-62ce-4173-a1a1-9dc7f89b829c.png">|<img width="540" alt="image" src="https://user-images.githubusercontent.com/5517077/200529972-185ed65d-51be-45bd-810a-38ec0841865e.png">|
=> chore(column width): adapt customer list column size

src/components/GenericPlaceholder.tsx
We decided, in agreement with product, to change the default margin-top value for all `GenericPlaceholder` components.
This have and impact on both Error and Empty states.
Please note that all custom implementations existing today (`noMargin`) haven't been changed
=> chore: 📏 change the genericPlaceholder default margin-top

src/components/settings/EditOrganizationVatRateDialog.tsx, src/core/apolloClient/reactiveVars/currentUserInfosVar.ts, src/generated/graphql.tsx
When setting a new VAT rate on our organization, the value is not visible in the customer details as the "default vat rate"
This PR creates a new util that updates the `currentOrganization` var and the local storage value.
This util is then used in the fallback after updating an organization vat rate
=> bug: fix vat rate not being udpated in LS and Dynamic vard

src/components/plans/AddChargeDialog.tsx
Users could have a very large numbers of Billable metrics. If they have more than 50 they are currently blocked
This PR is a quick fix. A long term fix will be to implement lazy search when users type value in the input
=> bug: increase fetched BMs limit

src/hooks/customer/useAddSubscription.tsx
This endpoint didn't had any limit
This PR set it's to a large number, until we're able to fetch via the combobox component when no results displays
=> bug: Fix plan limit

src/components/form/TextInput/TextInput.tsx, src/components/plans/ChargePercentage.tsx, src/components/plans/GraduatedChargeTable.tsx, src/components/plans/PackageCharge.tsx, src/components/plans/VolumeChargeTable.tsx, src/components/wallets/WalletTransactionList.tsx, src/formValidationSchemas/chargeSchema.ts, src/formValidationSchemas/feesSchema.ts
Some charges needs to have 15 decimal numbers
This PR increases the limit and some validations for the fields that uses today 5 decimal, to handle 15
Note: the change in `src/formValidationSchemas/chargeSchema.ts` is a bugfix. It' allowed to send big decimal here even tho it was considered as a currency precision before
=> feat: Big decimal

ditto/base.json, ditto/config.yml, ditto/index.js, src/components/CodeSnippet.tsx, src/components/DebugInfoDialog.tsx, src/components/customers/CustomerInvoicesList.tsx, src/components/customers/creditNotes/CreditNotesList.tsx, src/components/customers/subscriptions/SubscriptionLine.tsx, src/components/designSystem/Toasts/Toast.tsx, src/components/settings/members/CreateInviteDialog.tsx, src/components/settings/members/InviteItem.tsx, src/core/utils/copyToClipboard.ts, src/layouts/CustomerInvoiceDetails.tsx, src/pages/CreditNoteDetails.tsx, src/pages/developers/ApiKeys.tsx, src/pages/settings/GocardlessIntegration.tsx
👉 https://github.com/getlago/lago-front/issues/553
Application can be run in [unsecure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts), leading to browser disabling the access to clipboard.
When it happen, users clicking on "Copy to clipboard" buttons all over the app will have a success toast displayed, but the information won't be copied.
Over the past few weeks, some places in the app that were displaying copy buttons with information next to them, improved those places to make sure the information is fully visible on the screen, helping users to get the value to copy even if the copy to clipboard don't work.
It does not fix the issue tho.
In order to improve even more the UX when such bug occur, this PR brings a new `copyToClipboard` helper.
It will …
=> feat: improve copy-to-clipboard behaviour 

src/components/customers/CustomerSettings.tsx, src/components/form/AmountInput/AmountInput.tsx, src/components/form/TextInput/TextInput.tsx, src/components/wallets/TopupWalletDialog.tsx, src/pages/settings/InvoiceSettings.tsx
- By topping up a wallet, there is an error
<aside>
⚠️ **Message**
*"Variable $input of type CreateCustomerWalletTransactionInput! was provided invalid value for grantedCredits (Could not coerce value 10 to String)"*
</aside>
- Frontend is sending an integer while backend expects a ************string************
- For info, when creating a wallet, frontend sends a string
- Frontend must always send a string for **************creating a wallet************** and **************************************topping up a wallet**************************************
- Frontend must accept credit values with decimals as we can send strings (let’s block to 2 decimals)
=> fix: 👵 Wallet top up

src/components/customers/InvoicesList.tsx, src/components/designSystem/Status.tsx
Allow the Status component to hide the status label next to the colored dot.
Bug:
=> bug: allow to hide label on Status

src/layouts/CustomerInvoiceDetails.tsx
Hide credit note tab if invoice is in draft, unless it already has credit notes
=> bug: fix credit note tab display for draft invoice

src/core/serializers/serializePlanInput.ts
We have a regression in plan creation.
If you add a percentage charge while creating a plan. You receive a backend error
This PR fixed the serialization of the plan data sent to BE, hence fixing the error
=> bug: fix plan percentage charge serialization

src/layouts/CustomerInvoiceDetails.tsx
We decided the tabs should not appear in draft invoices, not matter if there is credit notes or not
=> bug: fix tab display logic in invoice overview

src/components/RouteWrapper.tsx
A recent upgrade of react-router-dom updated the way they manage types exported from their package.
For some reason, the ugrade PR did not failed. Hence having this fix now.
=> chore: fix react-router-dom index route type definition

src/core/__tests__/serializeAmount.test.ts, src/core/serializers/serializeAmount.ts
Serialization is wrong on certain amount turned into float. We need to manipulate them differently depending on the operation
Closes https://github.com/getlago/lago/issues/176
=> bug: fix number serialization

package.json, yarn.lock
We do have a PR to update the axios package version, with a large diff https://github.com/getlago/lago-front/pull/495
We do have a package resolution for axios, after we had a dependabot security alert https://github.com/getlago/lago-front/security/dependabot/13
It seems that axios package is used by `dittowords/cli` package internally, with the version `0.27.2`.
As the security concern was for versions `< 0.21.2`, there is no need to keep this resolution anymore
This PR simply remove the version resolution for axios, letting other packages using their own version.
=> chore: remove axios package resolution version

src/generated/graphql.tsx, yarn.lock
Nodes modules are build during tests:e2e CI job.
Those are getting bigger and bigger leading to some command to take a lot of time (here `COPY . .`)
This PR uses [yarn deduplicate](https://github.com/scinos/yarn-deduplicate#readme) to flatten some dependencies definition in the `yarn.lock` leading to have simpler package resolution so smaller `node_modules` fodler.
Here is the diff https://www.diffchecker.com/cV0ShOiM/
I also tested the app manually to make sure we didn't break some parts (even tech ones as translations download)
Everything seems to work well.
=> chore: deduplicate packages versions

package.json, renovate.json
This PR make sure `yarn-deduplicate` is called on package post-install and post-update
=> chore: make sure we deduplicate packages after install and update

src/components/designSystem/Chip.tsx
Update Chip component style in order to adapt if multiple lines are displayed
So it can look like this 
Also took the opportunity to clean some repetitive style such as all `margin-right`
=> chore: update chip styles

yarn.lock
⚠️ **Fixes critical deps issue https://github.com/getlago/lago-front/security/dependabot/29**
Bumps [loader-utils](https://github.com/webpack/loader-utils) from 1.4.0 to 1.4.2.
- [Release notes](https://github.com/webpack/loader-utils/releases)
- [Changelog](https://github.com/webpack/loader-utils/blob/v1.4.2/CHANGELOG.md)
- [Commits](https://github.com/webpack/loader-utils/compare/v1.4.0...v1.4.2)
---
updated-dependencies:
- dependency-name: loader-utils dependency-type: indirect ...
Signed-off-by: dependabot[bot] <support@github.com>
Duplicate of https://github.com/getlago/lago-front/pull/747.
Done because dependabot PRs seems to not pass the expected CI token
=> chore(deps): bump loader-utils from 1.4.0 to 1.4.2

src/hooks/useDebouncedSearch.ts
On large dataset, loading were first showing empty state screen before triggering the loading.
It appear that when debouncing, the default loading state value was false, even tho once the hook is ready we imediatly trigger the query, leading to a blink before first loading.
This PR changes the default state value to be true
=> bug: set loading to true by default

src/components/customers/CustomerCreditNotesList.tsx, src/hooks/useCreateCreditNote.ts, src/layouts/CustomerInvoiceDetails.tsx, src/pages/InvoiceCreditNoteList.tsx
Customers should not have the possibility to issue a credit note when the invoice has no `creditableAmountCents` and `refundableAmountCents`.
This PR does read those values as string, as they are returned by the BE
=> bug: fix amount cents type

src/generated/graphql.tsx, src/styles/muiTheme.ts
Disable checkboxes have a wrong color
This PR fixes the box background color, as other style definition that were working anyway.
BEFORE
AFTER
=> Fix checkbox style

src/generated/graphql.tsx, src/pages/CreateCoupon.tsx
An alert is shown when creating a forever coupon with percentage. Which should not happen as the error mentions a situation with fixed amount
This PR adds a condition to display the alert correctly
=> bug: 🏷️ fix coupons alert wrongly displayed

src/generated/graphql.tsx, src/pages/CreateBillableMetric.tsx, src/pages/CreatePlan.tsx
We had the possibility to edit a plan and BM without draft invoices or active subscription attached
It can cause issues when performing calculation on passed invoices.
This PR changes the rule checking if plan or BM can be edited, based on a new BE attribute checking if any subscription has been attached in the past (or currently attached)
=> feat: disable plan and BM edit if subscription existed

src/components/addOns/AddOnItem.tsx, src/components/coupons/CouponItem.tsx, src/generated/graphql.tsx, src/hooks/useCreateEditAddOn.ts, src/hooks/useCreateEditCoupon.ts, src/pages/CreateAddOn.tsx, src/pages/CreateCoupon.tsx
We change the logic allowing if a user can delete or not an add on or a coupon
Goal is to align with BE logic used too
This PR uses the new `appliedCouponsCount` and `appliedAddOnsCount` attributes to handle disable logic
=> feat: udpate edit coupon and addon disabled logic

src/components/customers/AddCustomerDrawer.tsx, src/pages/settings/OrganizationInformations.tsx
Fix miscellaneous code around timezone
Was first looking how to fix a translation warning, took time to remove an hardcoded value.
This PR does 2 things:
- uses an enum instead of hardcoded value
- fixes a translation warning. We were trying to translate an already translated value, so the `translate` method were returning a warning while prompting the correct value on the screen. User were not impacted and wont see any change after this merge
=> misc: fix timezone usage

src/generated/graphql.tsx, src/pages/CreatePlan.tsx
This rule changed with the recent plan edition being allowed.
If a BM is not attached to a plan yet (the plan has not been saved with this BM yet), the charge does not have and ID yet.
We now rely on the `isNew` condition, that performs a find and pretty much do the job of knowing if the charge has an ID or not
=> bug: 🐟 fix edition rule for BM in plan form

package.json, yarn.lock
Fixed build warning 
```
npm WARN @apollo/client@3.7.6 requires a peer of graphql@^14.0.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @graphql-typed-document-node/core@3.1.1 requires a peer of graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-upload-client@17.0.0 requires a peer of graphql@14 - 16 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-tag@2.12.6 requires a peer of graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
```
This does not changes the …
=> chore: 🚢 fix warning peer deps not installed

src/components/plans/ChargePercentage.tsx
We have a bug when deleting extra attributes on a charge percentage
We were spreading the whole charge into itself, when deleting a line in a percentage charge.
This was leading to have the same object spread with the same structure, so all attributes values were reset (as the .properties was "deeper" so not accessed by the form)
Not we spread the exact same values and just update the expected value, keeping the others' values
=> bug: fix charge percentage delete messing with attributes value

PULL_REQUEST_TEMPLATE.md
We do not rely on Github projects anymore, so this section about a project link in PR template is useless now
This PR removes the section in the `PULL_REQUEST_TEMPLATE.md`
=> chore: remove useless section in PR template

src/components/customers/CustomerSettings.tsx, src/components/customers/DeleteCustomerGracePeriodeDialog.tsx, src/components/customers/DeleteCustomerVatRateDialog.tsx, src/components/customers/EditCustomerInvoiceGracePeriodDialog.tsx, src/components/customers/EditCustomerVatRateDialog.tsx, src/generated/graphql.tsx, src/hooks/useOrganizationInfos.ts, src/pages/CustomerDetails.tsx
We'll add some functionalities to the customer settings very soon.
We noticed that the data management could be improved and decided to perform this refactor first.
This PR does
- prevent customerDetails route to fetch data only used into it's component customerSettings (a tab in the app)
- makes the fragment usage more clear and clean between sub-components
- prevent requesting very specific organization data in global calls
=> Refactor data management

src/components/customers/CustomerCoupons.tsx
When a coupon is terminated, we fetch all customer infos to retrieve back this list without the element
It does
- makes us perform an unnecessary call
- Makes the UI blink as the list is only updated when we receive the data for the query that retrieve back all customer infos. At this stage the "Delete coupon" dialog is already gone so users see the list being updated with a latency
We now evict the item from the cache, making the list update instantaneous
=> chore: update cache when coupon is terminated

src/components/settings/members/RevokeInviteDialog.tsx, src/components/settings/members/RevokeMembershipDialog.tsx
Update cache manually after removing an object from a list to avoid loading glitch
=> chore: ✍️ Manually update cache on revoke object

src/components/settings/members/CreateInviteDialog.tsx, src/generated/graphql.tsx
Manually update cache after invitation creation
Need to reorder list from newest to oldest to avoid wrong order on paginated query
=> chore: 👓 Manually update cache on invite creation

cypress/support/commands.ts
This PR overrides the `cy.type` method to perform the command with a `delay: 0` by default.
All TS errors have been overridden as the command comes from their documentation ans should be safe to use as is.
See https://docs.cypress.io/api/cypress-api/custom-commands#Overwrite-type-command for more infos
We pass from ~3'38 to 2'47, small gain but will prevent to increase too much when adding new tests
---
https://www.youtube.com/embed/Sp5_d6coiqU?start=4&amp;end=5%22
=> test: make cy.type blazingly fast

globals.d.ts, src/hooks/useDebouncedSearch.ts
In a search of improving our test suite, I wanted to reduce the timeout value to 0 in e2e tests
This RP does check on window.Cypress to know if the app is running in e2e test env
[Doc](https://docs.cypress.io/faq/questions/using-cypress-faq#Is-there-any-way-to-detect-if-my-app-is-running-under-Cypress)
Also, we now declare any type for this Cypress object
=> test: set 0ms timeout in cypress env

package.json, src/components/customers/AddCustomerDrawer.tsx, src/components/designSystem/ButtonLink.tsx, src/components/form/Checkbox/Checkbox.tsx, src/components/form/Checkbox/CheckboxField.tsx, src/components/form/ComboBox/ComboBoxPopperFactory.tsx, src/pages/CreateCoupon.tsx, src/pages/__devOnly/DesignSystem.tsx, src/styles/muiTheme.ts, yarn.lock
=> chore: 🥑 Remove material on Checkboxes

.github/workflows/codegen.yml, .github/workflows/cypress.yml, .github/workflows/linter.yml, .github/workflows/stories.yml, .github/workflows/tests.yml, .github/workflows/translation-check.yml, .github/workflows/typescript.yml, Dockerfile, Dockerfile.arm64, Dockerfile.dev, package.json
Since end of last year, [github CI dropped support for node versions olders than v16](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).
We currently ue v14 in all our project
This PR forces usage of v16 in our project
=> breaking(node): minimal node version is now v16

src/components/customers/CustomerInvoicesList.tsx, src/layouts/SideNavLayout.tsx
In some parts of the app, we use `overflow: scroll` that have the disadvantage to [always show the scroll bar](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#syntax)
This PR turn them into `overflow: auto` that fixes this issue
=> bug: fix scrollbar always shown

src/components/creditNote/CreditNoteFormCalculation.tsx
BE changed their round logic, from ceil to round
This PR change the FE manipulations to math with those new rules
=> misc(credit notes): use math round in credit note form calculation

src/components/customers/AddAddOnToCustomerDialog.tsx, src/components/customers/AddCouponToCustomerDialog.tsx, src/generated/graphql.tsx, src/pages/CustomerDetails.tsx
The cache was not set correctly, the whole `CustomerDetailFragment` was re-written which caused the suppression of part of it (missing `typename`).
I made sure we only re-write the right part of the cache for the AddOn, did the same on Coupon
=> fix: 🦆 Error while adding an add-on

src/generated/graphql.tsx
Noticed a unused resolver and type in the GraphQl api
Removed here: https://github.com/getlago/lago-api/pull/878
This PR udpates the autogenerated graph to the last verison
=> chore(graph): update graph to last version

src/components/invoices/InvoiceCreditNotesTable.tsx
Invoices with multiple plan are not displayed in the app
This PR fix the subscription display.
The data was wrongly found within loop. We can simply check on the first item to get the subscription. 
We could otherwise have a missmatch between the object looked at and the array size
=> bug(credit_notes): fix multiple plan display

src/generated/graphql.tsx, src/pages/CreateBillableMetric.tsx
We noticed an empty type on BE side and decided to remove ir
This PR removed the usage of this type and fallbaclks to the common BillableMetrics one 
Related to: https://github.com/getlago/lago-api/pull/897
=> chore: remove BM details type association

src/generated/graphql.tsx, src/hooks/useCreateEditCoupon.ts
We noticed an empty type on BE side and decided to remove it
This PR removed the usage of this type and fallbaclks to the common Coupon one 
Related to: https://github.com/getlago/lago-api/pull/900
=> chore: remove Coupons details type and association

src/generated/graphql.tsx, src/pages/CreatePlan.tsx
We noticed an empty type on BE side and decided to remove it
This PR removed the usage of this type and fallbaclks to the common Plan one 
Related to: https://github.com/getlago/lago-api/pull/902
=> chore: remove Plan details type association

src/components/designSystem/Accordion.tsx, src/components/wallets/WalletAccordion.tsx
We recently added an option to make the accordion content un-mount when the accordion is closed
This can be an issue when accordion is responsible to load data.
This PR make the accordion API accept props to remove this option, as disabling `unmountOnExit` in wallet accordion
=> chore(Accordion): allow transitionProps as props

src/core/documentLocales.ts
For legal reason, some companies had to generate invoices in their own languages.
This PR adds a new option available and handled by BE to generate invoices' PDF in different locale: `Norwegian (Bokmål)`
=> feat(locale): add Norwegian as available value

ditto/base.json, src/components/customers/AddCustomerDrawer.tsx, src/components/invoices/AddMetadataDrawer.tsx, src/components/invoices/Metadatas.tsx, src/formValidationSchemas/metadataSchema.ts
We decided to increase the value length of invoices metadata to 255, while keeping the customer ones to 40
=> feat(metadata): invoice value an be 255 length

src/components/UserIdentifier.tsx
We perform a call to retrieve the currentUser, even tho user is not connected
This PR skips the call until user it authenticated
=> chore(UserIdentifier): prevent query if user is not authenticated

src/components/customers/AddAddOnToCustomerDialog.tsx, src/components/customers/AddCouponToCustomerDialog.tsx, src/components/customers/AddCustomerDrawer.tsx, src/components/customers/CustomerAddOns.tsx, src/components/customers/CustomerCoupons.tsx, src/components/customers/CustomerMainInfos.tsx, src/components/customers/DeleteCustomerDialog.tsx, src/components/customers/DeleteCustomerDocumentLocaleDialog.tsx, src/components/customers/DeleteCustomerGracePeriodeDialog.tsx, src/components/customers/DeleteCustomerVatRateDialog.tsx, src/components/customers/EditCustomerDocumentLocaleDialog.tsx, src/components/customers/EditCustomerInvoiceGracePeriodDialog.tsx, src/components/customers/EditCustomerVatRateDialog.tsx, src/components/customers/subscriptions/CustomerSubscriptionsList.tsx, src/components/customers/subscriptions/TerminateCustomerSubscriptionDialog.tsx, src/components/customers/usage/CustomerUsage.tsx, src/components/customers/usage/UsageItem.tsx, src/components/wallets/AddWalletToCustomerDialog.tsx, src/components/wallets/TerminateCustomerWalletDialog.tsx, src/generated/graphql.tsx, src/hooks/customer/useAddSubscription.tsx, src/hooks/useCreateEditCustomer.ts, src/pages/CustomerDetails.tsx
This is the last item of removing the types `Details` task in app
This one is a bit tricky as it was used a lot on FE side and had different logic for the same attributes depending on the BE type
I tested the app with those changes and I had to add a `refetchQuery` when adding a subscription. This should be fixed in later data and fragment refactor on this part.
This is a good step forward for [cache and fragment improvement](https://github.com/getlago/lago-front/issues/865) for this part of the app
This PR removes all `CustomerDetails` occurrences in the app to stick with the `Customer` one
=> chore(Customer): remove all CustomerDetails occurences

src/hooks/useCurrentUser.ts
If a user is not authenticated yet, we should not perform a call to retrieve the currentUser datas
=> chore(CurrentUser): prevent fetch is user is not authenticated

src/components/customers/subscriptions/AddSubscriptionDrawer.tsx, src/components/customers/subscriptions/EditCustomerSubscriptionDrawer.tsx, src/components/customers/subscriptions/SubscriptionLine.tsx, src/core/apolloClient/reactiveVars/overwritePlanVar.ts, src/generated/graphql.tsx
We decided to always show the external id in those situations.
Note that the input has different behaviours
- Create subscription - input is editable
- Edit subscription - input is disabled and current value is displayed
- Upgrade / downgrade - input is disabled and current value is displayed
=> feat(subscription): display external id if present

src/components/customers/subscriptions/AddSubscriptionDrawer.tsx
When adding a subscription to a customer, the default date should start at the beginning of the day
=> fix(timezone): subscription default date start of day

src/components/billableMetrics/BillableMetricItem.tsx, src/components/billableMetrics/DeleteBillableMetricDialog.tsx, src/pages/BillableMetricsList.tsx
Chasing for perf issues in lists, noticed that bm items (rendered in loop) was rendering a modal multiple time
Moved this modal invocation in parent's DOM to prevent useless re-render.
This modal can now be invoked by passing the BM directly
=> chore(BM-item): move looped modal into parent dom

src/components/plans/DeletePlanDialog.tsx, src/components/plans/PlanItem.tsx, src/pages/PlansList.tsx
Chasing for perf issues in lists, noticed that plan items (rendered in loop) was rendering a modal multiple time
Moved this modal invocation in parent's DOM to prevent useless re-render.
This modal can now be invoked by passing the plan directly
=> chore(plan-item): move looped modal into parent dom

src/components/addOns/AddOnItem.tsx, src/components/addOns/DeleteAddOnDialog.tsx, src/pages/AddOnsList.tsx
Chasing for perf issues in lists, noticed that AddOn items (rendered in loop) was rendering a modal multiple time
Moved this modal invocation in parent's DOM to prevent useless re-render.
This modal can now be invoked by passing the AddOn directly
=> chore(addon-item): move looped modal into parent dom

src/components/coupons/CouponItem.tsx, src/components/coupons/DeleteCouponDialog.tsx, src/components/coupons/TerminateCouponDialog.tsx, src/pages/CouponsList.tsx
Chasing for perf issues in lists, noticed that Coupon items (rendered in loop) was rendering two modal multiple time
Moved this modal invocation in parent's DOM to prevent useless re-render.
Those modal can now be invoked by passing the Coupon directly
=> chore(coupon-item): move looped modal into parent dom

src/components/customers/CustomerInvoicesList.tsx, src/components/invoices/InvoiceListItem.tsx, src/pages/InvoicesList.tsx
Chasing for perf issues in lists, noticed that invoice items (rendered in loop in 2 pages) was rendering two modal multiple time.
Moved this modal invocation in both parent's DOM to prevent useless re-render.
Those modal invocation didn't change as they were already using useImperativeHandle and state to manage their data display
=> chore(invoice): move looped modal into parent dom

src/formValidation/chargeSchema.ts, src/hooks/plans/__tests__/useGraduatedChargeForm.test.tsx, src/hooks/plans/__tests__/useVolumeChargeForm.test.tsx, src/hooks/plans/useGraduatedChargeForm.ts, src/hooks/plans/useVolumeChargeForm.ts
We recently changed some data of graduated and volume charge from float to bigint
Bitint are represented with strings.
I missed this change the first time
This PR fixes the volume and graduated validations by turning strings into number before comparing values.
=> bug(plan-charges): fix validations for volume and graduated

src/core/serializers/serializeAmount.ts
CLP supports 0 decimal but was defined as it in our app.
This PR fixes that
=> bug(currency): CLP supports 0 decimal

src/core/router/SettingRoutes.tsx, src/layouts/Settings.tsx
The `settings/invoice` route was previously named `settings/tax-rate` and been renames since few versions, and is no longer "supporter".
It was mainly to not break potential user bookmarks at by the time.
It's time to let it go 🕊️
=> breaking(router): remove support for old /tax-rate route

src/components/plans/ChargeAccordion.tsx
Adding a minimum amount is not possible when plan is assigned to a customer.
There is no point showing a button user can click but that show disabled actions
This PR makes the first button disabled
=> bug(plan-form): disable add mini amount

src/components/plans/FixedFeeSection.tsx, src/components/plans/PlanSettingsSection.tsx, src/core/formErrors.ts, src/hooks/plans/usePlanForm.tsx, src/hooks/useCreateEditAddOn.ts, src/hooks/useCreateEditBillableMetric.ts, src/hooks/useCreateEditCoupon.ts, src/hooks/useCreateEditTaxRate.ts, src/pages/CreateAddOn.tsx, src/pages/CreateBillableMetric.tsx, src/pages/CreateCoupon.tsx, src/pages/CreatePlan.tsx, src/pages/CreateTaxRate.tsx
Reuse the same exported error form enum all over the app
=> chore(global): export form error enum globally

src/components/designSystem/Button.tsx, src/pages/CreateInvoice.tsx
It's possible to click on a button even tho an async action is running. In the context where the async action is triggered by the button click.
This PR prevents any action to be triggered if the button action is already running
=> bug(button) prevent clicking button if action is already running

src/components/customers/CustomerSettings.tsx, src/pages/CreateInvoice.tsx
As a tax rate can be equal to `0%`, the current check on value is wrong and can lead to unexpected results.
This PR fixed the way we check the customer and orga vat rate value
Also, the customer settings display was having the same kind of issue and it's now fixed
=> bug(one-off) Fix tax rate assignment

src/components/customers/CustomerMainInfos.tsx, src/components/designSystem/Typography.tsx, src/pages/CustomerDetails.tsx
Prevent extra long names to weirdly overflow
=> bug(customer) fix name overflows

src/components/form/TextInput/TextInput.tsx, src/pages/auth/Login.tsx
If you're focused on the mail and press tab, you then focus the forgot password link, and you need to tab again to focus the password input.
We want to change the tab order to have the two inputs with one tab press distance, and then focus on the reset password link in last position, without changing the UI
I preferred the DOM manipulation + elements position rather than applying different `tabindex` values on elements to create a sequence (as adding positive elements to this attribute is deprecated)
The reset password link is now placed after the password input elements but is visually placed above it using position absolute.
=> chore(login) change item DOM order for better tab xp

src/core/router/utils.tsx
Just for me to make sure we properly differentiate those "somehow handled" errors from others that may occur in Sentry.
I could then patch this properly
=> chore: explicit error message for chunk load

cypress/e2e/t6-edit-plan.cy.ts, src/pages/CreatePlan.tsx
If there is no dirty attributes, user should see no warning when closing the plan form
=> bug(plan-form) fix non-dirty form to close easilly

src/components/customers/AddCouponToCustomerDialog.tsx, src/components/customers/CustomerCoupons.tsx
2 issues are fixed here
- while applying a coupon, if you pressed enter while selecting a coupon you had a console warning and the input value became `'undefined'`
- When deleting an applied coupon, after page reload you got a cache issue warning.
Those two are now fixed
=> bug(applied-coupons) fix add and delete behaviours

src/components/customers/subscriptions/AddSubscriptionDrawer.tsx
Simple button text color fix.
Happened because I added an inner typography and the color was not inherited from parent anymore
=> bug(drawer-button): inherit text color from button wrapper

src/core/router/utils.tsx
This PR does
- Silent such errors by not rejecting the error when occurring
- Prevent passing the parent error and reject to recursion. Those were missing the context when called again missing error details in the sentry message
=> chore(sentry): improve chunk loading error management

src/components/plans/ConditionalChargeWrapper.tsx
Group properties display can be messed in plan form
We were assuming that the group and flatGroup values had the same order so we could have situations where we used wrong information for a specific group property
We not get values by their group ID so we are sure to get the correct ones
=> bug(bm-group) fix display order

ditto/base.json, ditto/config.yml, ditto/index.js, src/components/customers/subscriptions/TerminateCustomerSubscriptionDialog.tsx
A copy was given the wrong variable name, resulting in "undefined" being prompted
This PR fixes the copy shown and the variable name given to the translate method.
At some point, in non e2e tests, later, I would love to test copy prompt.
Anyway, let's just fix it for now
=> bug(subscription) fix copy with undefined variable

src/components/invoices/InvoiceDetailsTable.tsx
Invoices can be (among other things) generated when terminating a subscription.
If this subscription is marked as "paid in advance", or received events leading to have 0 as the amount calculated, we can have an invoice generated with either:
- no fees
- fees where all of them have an amountCents equal to 0
Leading to a "not so nice" invoice overview display where only the table header and footer (totals) are visible
This PR makes sure that if any of those happens, we display a "placeholder" line between table's header and footer, containing the subscription name and all other data being 0.
Doing that, looking at those kinds of invoices makes more sense.
A future feature will make sure we handle those better on both BE and FE sides' templates.
=> bug(invoice) better empty invoice display

src/core/apolloClient/cacheUtils.ts
Users can be invited in multiple orga. They can log in and switch between them in the UI interface using the company switcher
The issue is that we clear local storage and don't keep any trace of the previously organization
This PR prevents clearing the local storage on logout
Also on login, we do check if an organ ID is stored and corresponds to any user's orga.
- if yes, we use this orga and logs in the user
- if no, we use the first orga in the list of the user and logs them in
=> bug(auth) keep previously connected orga in cache after logout

src/pages/InvoiceOverview.tsx
User should not be able to add a metadata on a draft invoice.
Adding one result in a BE error.
As metadata is empty at this stage, we hide the whole invoice metadata section if invoice status is draft
=> bug(invoice) hide metadata section if invoice is draft

src/core/serializers/serializeAmount.ts
IDR currency has decimal but was in our 0 decimal list of currencies
This PR removes IDR from this list making it a 2 decimal again
=> bug(currency) IDR has 2 decimal for display

src/components/billableMetrics/BillableMetricCodeSnippet.tsx
N/A
Billable metric code snippet includes a "$" before the api key, which was misleading for a user. Fix this by removing the $ sign
=> fix: bm code snippet bearer token

src/components/plans/ChargePercentage.tsx
We want to allow 15 decimals on percent rather than the current 2 decimal precision.
That will allow users to define more precise pricing
=> feat(charge-percent) allow long decimal on rate

src/pages/CreateInvoice.tsx
We can have an miss calculation in tax value applied on an amount
This PR applies a round on the tax amount value, as we do on Backend
=> bug(invoice) fix tax value rounding

src/components/customers/subscriptions/TerminateCustomerSubscriptionDialog.tsx
When canceling a subscription, the wording was showing "terminate" instead of "cancel"
Due to a wrong attribute reading
=> bug(subscription) fix CTA wording on cancel

ditto/base.json, ditto/de.json, ditto/fr.json, ditto/index.js, ditto/nb.json, src/components/customers/subscriptions/AddSubscriptionDrawer.tsx, src/hooks/customer/useAddSubscription.tsx
If you create a subscription with an already-existing external id, the BE returns an error
This PR uses this error to show an error message bellow the externalId input.
=> feat(subscription) display appropriate message if external id already exists

cypress/e2e/t30-create-one-off-invoice.cy.ts, src/pages/CreateInvoice.tsx
In invoice creation, when editing units, the total amounts were wrongly calculated if tax were presents
This PR fix the calculation and adds a non-regression test on the calculation's value
=> bug(invoice) fix total calculation when editing invoice item's units with tax

.github/workflows/translation-update.yml
We often need to get the last copy version from Ditto.
We must ask a dev to download them and manually create the PR with the changes.
This PR creates a GitHub action that can be manually triggered.
This action will "simply" run the `yarn ditto` command and create a PR with the output of it.
=> chore: add action to create PR with last copy update

src/components/billableMetrics/BillableMetricCodeSnippet.tsx
As snippet is an event payload, we should remove the recurring argument from it
=> fix: remove recurring argument in code snippet

ditto/base.json, ditto/config.yml, ditto/index.js, src/components/billableMetrics/BillableMetricCodeSnippet.tsx, src/components/plans/ChargeAccordion.tsx, src/generated/graphql.tsx, src/pages/CreateBillableMetric.tsx
👉  https://getlago.canny.io/feature-requests/p/billing-based-on-last-event-received
We want to allow having an aggregation type that would get the last event sent's value in order to compute pricing.
This PR allow to select a new "Last" aggregation type when setting up a Billable Metric.
You can then select this BM while creating a plan
=> feat(billable-metric) add Last aggregation type

src/index.js
BrowserTracing have been moved in latest versions https://github.com/getsentry/sentry-javascript/issues/7342
Just updating the import
=> chore(sentry) update deprecated BrowserTracing usage

ditto/base.json, src/components/addOns/AddOnItem.tsx
We can delete any addon nowadays, no matter the context
There is no sense to show this tooltip
=> bug(addon) remove tooltip that does not make sense anymore

nginx/nginx.conf
PR originally created by @nealfennimore
https://github.com/getlago/lago-front/pull/1214
I run lago in a dual-stack environment and i have trouble connecting to the lago frontend sometimes due to there not being a ipv6 listener. lago-api already has a ipv6 listener, so I have no trouble connecting to that. 
Update nginx to support ipv6 on port 80
=> chore(nginx) update config to support IPV6

src/generated/graphql.tsx, src/hooks/plans/usePlanForm.tsx
BE do not needs this ID anymore.
However, we keep using it on FE for the duplicate and override logic (mainly to fetch related plan infos) so I won't remove all the related logic yet.
Incoming feature release will fix that
=> chore(plan-override) prevent sending parentId to BE

src/components/customers/usage/UsageItem.tsx
- Create one Billable Metric (let's call is by it's code `bm_1`). This charge needs to have groups (one or 2 dimensions, not important)
- Create a plan, and add `bm_1` twice. This BM needs to have different `amount_cents` (let's say we use the standard charge model)
- Assign this plan to a customer and send events to this charge (no need to have events for each group/value pair)
- In the usage, open the customer's subscription. You can notice the usage contains two items with a ℹ️ button.
- The price of those usages will be different, but if you open the drawer bu clicking on the ℹ️, the value displayed will be the same (basically the value of the first usage displayed)
This is due to the Apollo cache, relying on the first ID it encounters in the model (Billable Metric) that is the same …
=> bug(usage) fix duplicate usage drawer data

src/core/apolloClient/cache.ts
Some users had the experience of duplicated customer in their list
This change ensures that all cached customers are identified by their ID and External ID
=> bug(cache) fine tune customer cache policy

src/components/form/DatePicker/DatePicker.tsx
Having an "auto" placement makes the DataPicker trigger an error on open
The reason is that we need to enable the `flip` modifier if the `placement: 'auto'` is applied. So it can change the placement "on the flight" if the opened element overflows. 
[Doc link](https://popper.js.org/docs/v2/modifiers/flip/)
This PR enables the `flip` modifier only if the placement prop is `"auto"`
=> bug(DatePicker): apply flip modifier if placement is auto

src/layouts/SideNavLayout.tsx
The Nav link for Plans now has sub-routes.
We must provide the buttonLink the instruction that the link can be clicked again even tho you're into a children's route.
We use this behaviour to redirect to the "main" route of the item (here plan list route)
=> bug(nav) plan sub route should allow nav button click

src/pages/CreateSubscription.tsx
You can create a plan override when creating a subscription.
This means a plan `A` can be assigned to a customer and create a subscription.
If you edit this plan `A` attribute, we create a child plan `A'` behind the scenes, containing those overrides
If you decide to upgrade/downgrade this plan `A'`, the plan parent `A` should not be in the list of available plans to select
=> bug(subscription) hide parent on upgrade/downgrade

src/hooks/useDebouncedSearch.ts
This one is a bit nasty and has not been spotted earlier for some reason.
The main observation is: in some lists, elements on the next pages are duplicated when scrolling.
This means that each time a customer has more than 20 elements in the list and scrolls down to fetch the next page, the current array of items and the incoming are merged twice together and exponentially increase the number of items in the list.
After considering an issue with Apollo cache and the way we flag/merge collections, it appears that the issue is related to some page implementation that uses a search bar at the same time
The bug occurs in lists where
- the `useDebounceSearch` hook is used (used for search)
- the returned loading boolean value of this hook is used to trigger the `fetchMore` method of the list …
=> bug(list) fix duplicated items

src/components/addOns/AddOnItem.tsx, src/components/billableMetrics/BillableMetricItem.tsx, src/components/coupons/CouponItem.tsx, src/components/taxes/TaxItem.tsx, src/core/router/ObjectsRoutes.tsx, src/hooks/useCreateEditAddOn.ts, src/hooks/useCreateEditBillableMetric.ts, src/hooks/useCreateEditCoupon.ts, src/hooks/useCreateEditTax.ts, src/pages/AddOnsList.tsx, src/pages/BillableMetricsList.tsx, src/pages/CouponsList.tsx
Simple router attribute renaming, more to come
Always better to be explicit. I'll follow this PR with one about customer :id attribute similar renaming.
In Customer scope, it started to be a mess with other attribute names collapsing.
=> chore(router) update :id name in router

src/components/customers/CustomerCoupons.tsx, src/components/customers/CustomerInvoicesTab.tsx, src/components/customers/CustomerItem.tsx, src/components/customers/EditCustomerInvoiceGracePeriodDialog.tsx, src/components/customers/creditNotes/CreditNotesList.tsx, src/components/customers/subscriptions/CustomerSubscriptionsList.tsx, src/components/customers/subscriptions/SubscriptionLine.tsx, src/components/customers/usage/CustomerUsage.tsx, src/components/invoices/InvoiceCreditNotesTable.tsx, src/components/invoices/InvoiceCustomerInfos.tsx, src/components/subscriptions/SubscriptionInformations.tsx, src/core/router/CustomerRoutes.tsx, src/core/router/ObjectsRoutes.tsx, src/hooks/customer/useAddSubscription.tsx, src/hooks/useCreateCreditNote.ts, src/hooks/useCreateEditCustomer.ts, src/layouts/CustomerInvoiceDetails.tsx, src/pages/CreateCreditNote.tsx, src/pages/CreateInvoice.tsx, src/pages/CreateSubscription.tsx, src/pages/CreditNoteDetails.tsx, src/pages/CustomerDetails.tsx, src/pages/CustomerDraftInvoicesList.tsx, src/pages/InvoiceCreditNoteList.tsx, src/pages/InvoicesList.tsx, src/pages/SubscriptionDetails.tsx
Followup of [this PR](https://github.com/getlago/lago-front/pull/1274)
Last update to change customer `:id` to be `:customerId` in the router definition
=> chore(router) update customer :id name in router

src/styles/muiTheme.ts
When fields are auto-filed by an external tool (like a password manager for example), the input focus stayed squared even tho all our inputs are rounded with 12px
This PR updated the theme's input definition to round them by default.
Inputs with adornment receive special rounding depending on it's position
|BEFORE|AFTER|
|-|-|
|<img width="542" alt="Monosnap Lago - Cloud 2023-10-19 15-02-19" src="https://github.com/getlago/lago-front/assets/5517077/ad851931-e920-4e3c-853e-75301f7ae074">|<img width="530" alt="Monosnap Lago - Local 2023-10-19 15-03-14" src="https://github.com/getlago/lago-front/assets/5517077/119ae8c2-d14a-4b74-8cdb-46e721e3426e">|
=> chore(input) add default border radius

src/core/apolloClient/cache.ts, src/generated/graphql.tsx
Cache needs a keyArgs definition, even if it's false
=> bug(billable-metrics): fix pagination

src/core/formats/__tests__/intlFormatNumber.test.ts, src/core/formats/intlFormatNumber.ts
Add new helper to format big numbers
Numbers bellow 1_000 are not formated and keep displaying their precision
Numbers above 1_000 use the k, M, B, ... notation
So 1.32 stays 1,32
And 1_000_000 becomes 1M
=> misc: add bigNumberShortenNotationFormater helper

src/core/timezone/__tests__/config.test.ts
We have a test checking some timezone helper values.
But Paris timezone has summer and winter time, leading to this value changing every 6 months and the test to fail.
This PR changes the TZ test to one that does not have this summer/winter time switch
=> bug(test) remove time-shifting TZ test

src/components/plans/ChargeAccordion.tsx
A warning dialog is shown when trying to delete a charge on a plan that is attached to a subscription.
This dialog should not be shown if the form is currently about duplicating a plan
=> bug(remove-charge) don't show delete-charge warning dialog in duplicate

src/core/utils/BMGroupUtils.ts, src/core/utils/__tests__/BMGroupUtils.test.ts
An issue occurred when editing a BM linked to a plan and/or subscription.
We do display a warning modal when the group is changed, but it was always displayed even tho you were changing only the BM name.
This PR adds a case handling empty object and empty object string being wrongly compared and returning a "structural change", leading to show the warning modal every time a BM was saved
=> bug(billable-metric) fix condition when no real change are performed

cypress/e2e/10-resources/t50-edit-plan.cy.ts, src/pages/CreatePlan.tsx
If the user closes the form during a plan duplication, we should redirect it to the plan list and not to the duplicated plan details
=> bug(plan) fix redirection when closing a plan duplication form

cypress/e2e/10-resources/t50-edit-plan.cy.ts, src/components/coupons/AddBillableMetricToCouponDialog.tsx, src/components/coupons/AddPlanToCouponDialog.tsx, src/components/plans/ChargesSection.tsx, src/pages/CreateInvoice.tsx
Same as https://github.com/getlago/lago-front/pull/1295
Fixing some combo box options displays when data is long enough to overlap the container and be wrongly displayed.
=> bug(combobox) fix option display for long values

cypress/e2e/10-resources/t50-edit-plan.cy.ts, src/components/plans/ChargeAccordion.tsx, src/components/plans/ChargesSection.tsx, src/components/plans/PlanSettingsSection.tsx, src/components/plans/details/PlanDetailsChargesSectionAccordion.tsx, src/components/plans/details/PlanDetailsFixedFeeAccordion.tsx, src/hooks/plans/usePlanForm.tsx
We decided to allow the tax edition on a plan and it's charges.
No matted if the plan is already attached to a subscription or not.
=> misc(plan) allow to edit tax on created plan

src/pages/CreateSubscription.tsx
Allowed on BE but not in the UI.
=> bug(subscription) allow edit subscription start date if pending

src/components/customers/CustomerMainInfos.tsx
We can apparently chain them to have multiple mail sent. In such case, let's display each on a different line
=> bug(customer-infos) better display for multiple emails

src/core/apolloClient/cache.ts, src/generated/graphql.tsx
BM are fetched twice in the same page, with two different API calls.
Each differs by looking at different values for `recurring` values.
The cache was melting sometimes when the data could be displayed at the same time.
We need to precise to the cache to make a difference between them based on their `recurring` value
=> bug(BM) fix cache issue when recurring value is used to fetch same resource

package.json, yarn.lock
This upgrade was causing many change in the generated graph.
All those changes includes some that breaks some behaviour in CI, for a reason I don't know today. (the feature works tho, seems like a tests env issue)
Will take care of this upgrade later
=> chore(deps) revert codegen cli v5 update

src/components/designSystem/Dialog.tsx
I need this for an ongoing dev.
Today, the button container is pushed to the right with a margin-left auto. 
That mean the button container cannot really be full width.
I need this to be possible as a button could be introduced to the left side of the actions to add a third action.
Having is placed using justify-content flex-end makes it easier to manipulate on such custom placements, and does not break the current implementation of modals
=> misc(Dialog): update CTA style to allow full width container

src/pages/Analytics.tsx
Some OSS freemium users experience a logout right after they login
It's due to a non expected API call to be performed, that returns in such situation an `unauthorized` response, loggin out the user
This PR updated the condition that lead to perform this call or not
=> bug(analytics) fix condition that prevents unauthorised call

src/components/invoices/details/InvoiceDetailsTableBodyLine.tsx, src/components/invoices/details/InvoiceDetailsTableBodyLinePackage.tsx, src/components/invoices/details/InvoiceDetailsTableBodyLinePercentage.tsx, src/components/invoices/details/InvoiceDetailsTableBodyLineVolume.tsx
In the past, we were optimistic about the values displayed in the invoices' detail page.
Bug since the recent edit-draft-invoice feature, we can have fee lines with 0 units displayed in invoice details.
This PR make sure 1 is not the default value anymore, and let 0 be displayed if needed instead.
We could simply remove the `||` condition but as BE is supposed to always populate those values. But I keep the `OR 0` approach jut in case, to prevent displaying NaN
=> bug(invoices) prevent faking values to wrong number by default

src/components/invoices/details/InvoiceDetailsTable.tsx
The MUI components got the animation better
The implemented animation does have a fixed max height, making the animation weird when few elements are displayed.
On close, the container assume the height is huge, leading to a little delay before the elements hides
This MUI components has build in the JS calculation of the hidden elements's height, leading to a better case by case animation.
It does have max-height 0 when hidden, during the animation, it does set the inner elements' height as the max height values, removing any delay. And once open the max-height is set to auto.
I does the other way around when closing, leading to have an animation with no glitch.
Way better then implementing that by hand.
=> misc(invoice-details) improve hidden fee animation

src/components/plans/ChargesSection.tsx
Using a ref makes the first render not showing any alert at all
Turning it to a useState triggered in the useEffect looking at the charges array's length, fixes any renders
=> bug(plan) fix already used charge alert display logic

src/components/invoices/details/InvoiceDetailsTable.tsx, src/components/invoices/details/InvoiceFeeAdvanceDetailsTable.tsx, src/components/invoices/details/InvoiceFeeArrearsDetailsTable.tsx, src/core/formats/formatInvoiceItemsMap.ts, src/generated/graphql.tsx
The current fee ordering logic is the following.
For each subscription:
- We first render the fees in arrears group
- We then render fees in advance group
Each group having their own periods and showing potentially the fees with 0 unit of the invoice is in draft.
Also note that the subscription fee is always displayed at the top of it's group
However I could lead to have the subscription fee "lost" in the subscription details, as it could be part of the fees in advance group inside an invoice with fees in arrears
I order to make the subscription fee appear at the top of all fees listed in the invoice details, we now packed those two big groups of fees in an array, and reverse this array depending on a flag.
This flag comes from the fee formating login, that looks id the subscription's …
=> misc(invoice-details) show subscription fee group first

src/core/serializers/__tests__/serializePlanInput.test.ts, src/core/serializers/serializePlanInput.ts
We perform some manual operations on this field
We receive it as an array of string, but we manipulate it as a string in the UI.
This value has to be re-transformed before sending it to the BE
All those manipulations makes is less predictable and lead to have the value empty for the charge models that are not standard.
This PR ensure the value is undefined in such case.
=> bug(plan) make sure groupBy is undefined if not defined

src/components/plans/FixedFeeSection.tsx
Currently it is not possible to edit plan amount cents on edit plan page and on edit subscription page.
We want to allow users to edit plan/subscription amount cents so that they don't need to create new plan with each change.
This PR enables `amountCents` field in `FixedFeeSection`
=> feat (edit-plan): allow plan amount cents edition

src/components/billableMetrics/BillableMetricCodeSnippet.tsx
Current snippet is mixing billable metric and events. However, the endpoint listed is the one of the event. I removed all the unnecessary fields, and also pick the first value of each filters
=> fix(bm-snippet): fix billable metric snippet

ditto/base.json, ditto/config.yml, ditto/index.js, src/components/addOns/AddOnItem.tsx, src/components/addOns/DeleteAddOnDialog.tsx, src/components/details/DetailsHeader.tsx, src/components/details/DetailsTableDisplay.tsx, src/components/plans/details/PlanDetailsChargeWrapperSwitch.tsx, src/components/plans/details/PlanDetailsChargesSection.tsx, src/components/plans/details/PlanDetailsCommitmentsSection.tsx, src/components/plans/details/PlanDetailsFixedFeeAccordion.tsx, src/components/plans/details/PlanDetailsOverview.tsx, src/components/subscriptions/SubscriptionInformations.tsx, src/core/router/ObjectsRoutes.tsx, src/generated/graphql.tsx, src/hooks/useCreateEditAddOn.ts, src/pages/AddOnDetails.tsx, src/pages/CreateAddOn.tsx, src/styles/detailsPage.tsx
👉  https://getlago.canny.io/feature-requests/p/{{FEATURE_SLUG}}
This PR should create a new detail page for add-ons
It should:
- refactor plan related code to reuse component and make them agnostic
- redirect to a new detail page by clicking in the list item or after closing the edition form
- create the new page
=> feat(AddOnDetailsPage): new page

src/components/form/TextInput/TextInput.tsx, src/components/form/TextInput/__tests__/FormatValue.test.ts
This PR aims for
- Add two new separators, `trim` and `dashSeparator`
- fix the current implementation of the formatted method
The fix is about fixing the formatter chaining that could be flacky when used in form with Formik
=> misc: add new formatters and fix chaining behaviour

src/components/PremiumWarningDialog.tsx, src/layouts/CustomerInvoiceDetails.tsx, src/pages/InvoiceCreditNoteList.tsx, src/pages/settings/InvoiceSettings.tsx, src/pages/settings/OrganizationInformations.tsx
We often display a warning dialog when non-premium user tried to access to a premium feature
This modal shows text and can open a pre-filled mail with custom text
This PR makes sure the premium warning dialog and the mail copy can be customised during invocation
It's new type definition makes it needed to be specifically called on invocation. It cannot be passed as method to a button onClick anymore for example.
=> misc: Allow customisation of premium warning dialog copy

renovate.json
Renovate does not create PR anymore. Even tho the config seems ok.
Trying to fix it by updating the schedule.
=> chore(renovate) update schedule

src/components/designSystem/Chip.tsx
There was a excess margin on the chip icon. See before/after:
**Before**
**After**
=> fix: remove excess margin on chip icon

src/generated/graphql.tsx, src/pages/WalletForm.tsx
https://linear.app/getlago/issue/DLVRY-311/allow-negative-value-in-recurring-top-up-threshold
Recurring wallet creation/edition
We should be able to submit negative/0/positive threshold.
QA: https://fix-threshold-wallet-app.staging.getlago.com/
=> fix: allow negative threshold

scripts/InspectTranslationKeys.js
While implementing a feature, we often take care of the copy management as a last step.
We often write them in our templates as "TODO: Final Copy wording here", so prefixed with TODO: 
This PR allow to flag the inspectTranslations script to find and replace those copy, and replace them with the value present in base.json, for it's corresponding wording.
NOTE: This script is not fully working yet, and only replace one file.
=> chore(inspectTranslations) add flag to replace TODO: copy

src/core/serializers/__tests__/serializePlanInput.test.ts, src/core/serializers/serializePlanInput.ts
We encountered an error when assigning a plan to a customer because we were trying to parse a json that was already an object on submit.
Removing the `JSON.parse()` should fix the issue.
It seems that GraphQL in returning `customProperties` as json already so we don't need to parse it twice.
=> fix: custom agg json serializer

src/generated/graphql.tsx, src/hooks/useCurrentUser.ts, src/layouts/SideNavLayout.tsx
With the RBAC feature, we now gonna use the exposed membership model and fetch the organizations through it.
This PR brings a minor change to the sidebar and exposes the current membership from the useCurrentUser hook
This architecture respects the data model an organizations should not be exposed from the user directly. This will be removed later on type definition side
=> chore: fetch memberships and their organizations

ditto/base.json, src/core/router/index.tsx, src/core/router/types.ts, src/generated/graphql.tsx, src/hooks/__tests__/usePermissions.test.ts, src/hooks/core/__tests__/useLocationHistory.test.ts, src/hooks/core/useLocationHistory.ts, src/hooks/useCurrentUser.ts, src/hooks/usePermissions.ts, src/layouts/SideNavLayout.tsx, src/pages/Forbidden.tsx, src/pages/Home.tsx
We're about to implement roles in the app. Foundations relies on a Role Based Access Control, that shoud emit a list of permissions depending on multiple factors (role, licence, cloud user, ...)
All this logic is implemented on Backend side and the FE app needs to be prepared to handle those permissions in order to update accordingly the app and the user experience.
This PR is a first step into that direction, and implements the base logic for this project.
This PR is composed of 4 commits that have their own objectives
- https://github.com/getlago/lago-front/commit/ff24e6e6e818cc6ddc0cf39cef4e10021e50cd3a adds a new route that would be the fallback for any user that tries to access a route are are not permitted to …
=> feat: add RBAC core features

src/components/billableMetrics/BillableMetricItem.tsx, src/core/router/ObjectsRoutes.tsx, src/core/router/types.ts, src/layouts/SideNavLayout.tsx
This PR is part of the RBAC feature. 
Add route and action permission logic for the Billable metrics views of the app.
Fixes DLVRY-321
=> feat: add billable metrics role guard

src/components/addOns/AddOnItem.tsx, src/components/plans/PlanItem.tsx, src/core/router/ObjectsRoutes.tsx, src/pages/AddOnDetails.tsx, src/pages/AddOnsList.tsx
This PR is part of the RBAC feature. 
Add route and action permission logic for the Addons views of the app.
Also, an adjustment needed to be performed for plan item list display
Fixes DLVRY-323
=> feat: add addOns route and actions role guard

scripts/InspectTranslationKeys.js
It does
- Make sure the whole string is replaced with the expected key
- Make sure the string to replace is exactly the same as the one targeted (case sentitive)
=> misc: improve replacement regex in script

globals.d.ts, src/core/utils/featureFlags.ts, src/index.js
This PR should create functions to get/list/set object inside local storage with the key `featureFlags` to allow us to dev feature while hiding them to the customer
- How to use in codebase:
```ts
import { FeatureFlags, isFeatureFlagActive } from '~/core/utils/featureFlags'
const isFtrActive = isFeatureFlagActive(FeatureFlags.FTR_ENABLED);
// → true / false
```
- How to use inside browser console:
```ts
// List available flags
window.Lago.listFeatureFlags();
// Set flags (string or array)
window.Lago.setFeatureFlags('ftr_rbac_enabled');
window.Lago.setFeatureFlags(['ftr_rbac_enabled', 'ftr_okta_enabled']);
// Set all available flags
window.Lago.setFeatureFlags('all')
// Get enable flags
window.Lago.getEnableFeatureFlags()
```
=> misc: add front-end feature flags logic using local storage

src/pages/settings/AdyenIntegrationDetails.tsx, src/pages/settings/AdyenIntegrations.tsx, src/pages/settings/GocardlessIntegrationDetails.tsx, src/pages/settings/GocardlessIntegrations.tsx, src/pages/settings/LagoTaxManagementIntegration.tsx, src/pages/settings/StripeIntegrationDetails.tsx, src/pages/settings/StripeIntegrations.tsx
Add permission check for integrations
=> feat: add rbac guards for integrations page

src/core/router/ObjectsRoutes.tsx, src/pages/WalletForm/WalletForm.tsx, src/pages/WalletForm/components/LoadingView.tsx, src/pages/WalletForm/components/SettingsCard.tsx, src/pages/WalletForm/components/TopUpCard.tsx, src/pages/WalletForm/index.ts, src/pages/WalletForm/types.ts
This is a refactor and it should not change any current behaviours.
While working on the wallet top-up improvement feature, I was editing `WalletForm` file and it became so large that it was exceeding 1000 lines. 
I thought that as pre-requisites to this PR, I would split the file into multiple components so it would be easier to code and review. 
Let me know what you think!
=> refactor(WalletForm) - split file into separate components

.vscode/lago.code-snippets
Just a snippet to avoid writing `translate('TODO: ...')` and use `trl tab` instead 🚀 😄
=> misc(vscode): translate snippet

src/components/customers/CustomerCreditNotesList.tsx, src/generated/graphql.tsx
BE refactored this endpoint to 
- have a generic name
- allow to filter by customer id to not break existing behavior
Main reason is that we'll have very soon a credit note list in the app, like the invoices one
Related to https://github.com/getlago/lago-api/pull/2080
=> misc(creditNotes): use the generic query

src/components/form/ButtonSelector/ButtonSelector.tsx, src/components/form/ComboBox/ComboBox.tsx, src/components/form/ComboBox/ComboBoxInput.tsx, src/components/form/ComboBox/types.ts, src/components/form/JsonEditor/JsonEditor.tsx, src/components/form/TextInput/TextInput.tsx, src/pages/__devOnly/DesignSystem.tsx
To prepare the UI migration of plan form page, I'm adding optional `description` props to form components
=> feat: add description props in form components

ditto/base.json, src/components/customers/creditNotes/CreditNotesList.tsx
Add missing empty state
Fixes ISSUE-343
=> misc: add default empty state in credit note list page

src/components/designSystem/NavigationTab.tsx
On some pages, when a component was not given in the tabs array, the MUI tabs component was raison an error. 
This PR fixes this initial state.
The NavigationTab component does init with a state value being null.
This is because the initial state is given by the internal useEffect of this component.
This useEffect does check the url, and decide whether or not the value should be 0 or a different value.
During this moment, the MUI tabs list is rendered but with a value being `null`.
The component is then rendering properly, but the MUI does logs a warning mentioning this unexpected state.
In this PR we make sure the MUI component is not rendered if the value is null, so only once we have the useEffect being triggered it can properly render.
=> misc: make sure initial render does not raise a warning

src/components/designSystem/Selector.tsx
This RP improves and simplify the SelectorSkeleton component.
It now shows the avatar square before the text placeholder.
=> bug: fix selector skeleton loading render

src/components/form/ComboBox/ComboBoxItem.tsx, src/components/form/Radio/Radio.tsx
The recent RBAC feature changed the default variant of the Radio component from `body` to `bodyHl`.
The issue is that this Radio component is used in the combobox item component, to render each options label.
This PR let the `bodyHl` as the default option, but allow to pass a param in order to change this value.
The `ComboboxItem` can now define the variant as `body`
Fixes ISSUE-348
=> bug: default combobox label variant should be body

src/components/settings/integrations/NetsuiteIntegrationSettings.tsx, src/generated/graphql.tsx, src/pages/settings/AdyenIntegrationDetails.tsx, src/pages/settings/GocardlessIntegrationDetails.tsx, src/pages/settings/NetsuiteIntegrationDetails.tsx, src/pages/settings/StripeIntegrationDetails.tsx
While working on the addition of a new integration, I noticed the back redirection logic was clumsy and could fail in some cases
This PR does 2 thing
- fix the condition for all integration back button
- Make sure the integrations fetched to perform this condition only fetch related integration type
=> misc: fix back navigation on integration deletion

src/components/designSystem/NavigationTab.tsx, src/layouts/CustomerInvoiceDetails.tsx
We recently refactored the new tab component in the app
It was containing a condition to not render if there were less than 2 tabs.
But it also precented the children container to render in such case
This PR moves the condition to only hide the tab element in such case, but let the children render in any cases
Also fixes ISSUE-349
=> bug: render nav children even if there is only one tab

src/components/designSystem/NavigationTab.tsx
Tab component have recently been updated.
There is one place in the app where a button outside of the tab component make the url change, and it changes to another tab url (not the one currently selected)
This PR make sure every time the url changes, the tab component check about the selected tab and can update the tabs accordingly if needed.
=> misc: update selected tab when url changes

src/components/customers/CustomerInvoicesTab.tsx, src/components/customers/CustomerMainInfos.tsx, src/components/customers/subscriptions/SubscriptionLine.tsx, src/pages/CustomerDetails.tsx
Related to ftr-overdue-balance
As a prerequisite to this feature, we want to move the customer details to the right side of the screen
| Before | After |
| ------ | ----- |
| ![Lago](https://github.com/getlago/lago-front/assets/17253055/75f52427-68b2-49bb-9deb-063a6925d416) | ![Lago · 10 57am · 06-14](https://github.com/getlago/lago-front/assets/17253055/93f6ff24-985c-44cc-974d-1dc41a8e3c26) |
=> feat: move customer details

src/core/serializers/serializeAmount.ts
Issue #1560 
It was reported that for CVE currency, the unit price amount was incorrect (compared to $)
This PR should allow CVE currency to have 2 decimals (it was 0 initially) and should fix the issue.
**After**
=> fix: remove CVE currency from currencies with 0 decimals

src/components/designSystem/Table/TableDisplay.tsx, src/components/designSystem/Table/index.ts, src/pages/__devOnly/DesignSystem.tsx
Hello! 
While working on `#ftr-overdue-balance`, i thought it would be a good idea to introduced a new table component to display our invoices instead of using `display: grid`. 
The component supports: 
```typescript
<TableDisplay
name="display-table"
data={tableData}
isLoading={false}
columns={[
{
key: 'name',
title: 'Name',
size: 300,
content: (row) => (
<div>
<Avatar variant="user" identifier={row.name} size="small" />
<Typography>{row.name}</Typography>
</div>
),
},
{
key: 'job',
title: 'Job',
content: (row) => row.job,
size: 124,
},
{
key: 'icon',
title: <Typography variant="captionCode">Icon</Typography>,
content: (row) => <Icon color="primary" name={row.icon as IconName} />,
},
]}
onRowAction={(item) => alert(`You clicked on ${item.name}`)}
actionColumn={[
{
title: 'Edit', …
```
=> feat: new display table component

src/components/customers/addDrawer/AddCustomerDrawer.tsx
We improved the way we remove integrations in the customer object on edit
On object deletion, we used to find back the original object, replace it in the customer payload and remove an attribute to "flag" it to be deleted in DB
Now, we can simply remove it in the customer payload and it's will be deleted.
As the UI is already deleting the object for display purpose, we can simply remove all this logic without addition
=> chore: improve integration deletion object serialization

ditto/base.json, src/core/timezone/config.ts, src/core/timezone/utils.ts, src/generated/graphql.tsx
New TZ have been added following Rails upgrade, as the list comes from `ActiveSupport::TimeZone.all`
Our app was optimistically fetching TZ config, hence having an app broke when this new TZ appeared
This PR does 2 things
- Add the support for this new TZ
- Make sure if a TZ config is missing, app does not break (fallback to UTC) and we're warned about it (Sentry custom error)
=> Handle missing TZ

src/generated/graphql.tsx, src/pages/CouponDetails.tsx
ISSUE-360
We displayed currency amount even if the coupon was a percentage type.
It should fix it.
=> fix: percentage display in coupon page

src/components/plans/ChargeAccordion.tsx, src/core/serializers/__tests__/serializePlanInput.test.ts, src/core/serializers/serializePlanInput.ts, src/hooks/plans/usePlanForm.tsx
We have a bug in the subscription form.
Each plan with a charge in advance makes the creatge subscription to create a plan override.
The reason is that FE sent `0` as a value when the field is set to undefined.
This PR does
- Make sure this does not happen anymore, and all '0' values are handled as undefined -> no plan override
- Make sure if the user save a plan with an charge min amount, we dont populate the attribute with `'0'`
=> bug: charge min amount should default to undefined if not set

ditto/base.json, src/components/customers/CustomerMainInfos.tsx
ISSUE-362
Shipping address object was sometimes defined but with empty values so we need to check single field before rendering it. It was causing issues with show more threshold counting.
=> fix: shipping address in show more details

src/hooks/customer/useAddSubscription.tsx
ISSUE-366
Name wasn't updated to initial state when it was removed.
If we set `name: undefined` then it'll not be included in the updated object.
Using `??` instead of `||` should fix the issue as empty string won't longer be considered as false
=> fix: handle falsy value for name

src/generated/graphql.tsx, src/pages/CreateAddOn.tsx
When creating add-ons, we're getting paginated list of taxes and display only first page of 20 taxes. So to get 21st tax we should query it by it's name. we didn't send searchTerm before, now we do
=> fix: search by tax name when getting taxes for add-on

src/components/WarningDialog.tsx, src/components/billableMetrics/BillableMetricItem.tsx, src/components/billableMetrics/DeleteBillableMetricDialog.tsx, src/generated/graphql.tsx, src/hooks/useCreateEditBillableMetric.ts, src/styles/muiTheme.ts
2 attributes on the BM object triggers heavy queries on DB
This PR makes those attribute queried on unique object fetch and not on collection fetch.
There is also some adjustments included here to make this change UX friendly
=> chore(BM): query heavy calculation attribute on uniq object query

src/components/plans/PackageCharge.tsx
ISSUE-395
Free units and Package size was concatenate as strings and not numbers
Converts strings into number before doing maths
=> fix: serialize number in package charge alert 

src/components/plans/ChargeAccordion.tsx
The Minimum spending does not have a label, so the input and the trash button next to it should be aligned horizontally
=> bug: align min spending input and button

src/components/designSystem/Table/ChargeTable.tsx, src/components/designSystem/Table/index.ts, src/components/plans/GraduatedChargeTable.tsx, src/components/plans/GraduatedPercentageChargeTable.tsx, src/components/plans/VolumeChargeTable.tsx, src/pages/__devOnly/DesignSystem.tsx
LAGO-145
Rename Table into `ChargeTable` before introducing the new Table component
=> chore(Table): rename Table component into ChargeTable

src/components/designSystem/Table/Table.tsx, src/components/designSystem/__tests__/Table.test.tsx, src/components/invoices/InvoicesList.tsx
LAGO-182
Currently, our table component can only renders button with popper menu, but we want to be more flexible **and render any kind of button.**
This PR should allow that.
**Dive-in: https://www.notion.so/getlago/Dive-in-Request-payment-for-overdue-balance-d19d73c71c794acfb5dbb22e8415e17b?d=f84c0f8220704d86b873fbb5f73b6be3#6cba8087abe8417591b77ef1d211789d**
Action column can now support custom ReactNode instead of array of `ActionItem`
```typescript
actionColumn={(currentItem) => (
<Button onClick={() => console.log(currentItem)}>Click</Button>
)}
```
=> feat: improve table component action column

src/styles/muiTheme.ts
Was added during some tests for the filters feature, but it not needed and also it adds a bug in some places of the app
=> bug: remove unnecessary zindex rule

src/components/designSystem/Status.tsx
=> fix: no wrapping in status badge

src/components/form/Checkbox/Checkbox.tsx
It makes sure the box and the label's first line are always aligned.
Currently, if it was one line it was looking weirdly not aligned, it's not aligned with the grid
=> bug(Checkbox): align label with box

src/components/designSystem/Alert.tsx, src/pages/__devOnly/DesignSystem.tsx
Improves the Alert API with new props
- fullWidth: allow to change display to width 100% and no border radius
- containerSize: works as for the table component, allows to define vertical padding with fixed value or pass an object for responsive rules
Current display of the Alert will not change until you pass those new props
Fixes LAGO-196
=> misc: Alert can be fullwidth with custom v-padding

src/components/plans/details/PlanDetailsCommitmentsSection.tsx
This PR fixes 2 things
- uses gap instead of spacing. Spacing adds margin top to elements and makes the accordion break when open. Gap fixes that
- use 16px instead of 24, as in other sections of this page
=> bug: better min commitment accordion display

src/components/designSystem/Status.tsx, src/pages/__devOnly/DesignSystem.tsx
LAGO-212
To prepare next feature, I'm adding optional `endIcon` to status component
=> feat: add endIcon to status component

src/components/designSystem/Alert.tsx
Left/Right Padding should not be applied to container itself while in full-width variation, otherwise it counts as `100% + PADDING_LEFT + PADDING_RIGHT` and causes overflow in the app
| |  Screenshots |
| ---- | ---- |
| **Before** | <img width="1237" alt="Capture d’écran 2024-08-16 à 17 00 43" src="https://github.com/user-attachments/assets/75d360dd-d346-4706-8f8c-1476cd599f86"> | 
| **After** | <img width="1237" alt="Capture d’écran 2024-08-16 à 17 01 33" src="https://github.com/user-attachments/assets/0a444425-fb7f-489f-aa95-03cd330a7921"> |
| **Design system** | <img width="1237" alt="Capture d’écran 2024-08-16 à 17 02 01" src="https://github.com/user-attachments/assets/a454ad86-0c38-409e-a7c5-2a8efee78d87"> |
=> fix(alert): full width variation padding issue

src/components/designSystem/NavigationTab.tsx
The component has a min height by default.
However, we don't display the children (tabs elements) if there is only one to display.
But then the min height was still there and the (invisible) parent then took space in the UI.
This PR makes sure ther min-height is applied only if some children are displayed (more than one to display)
=> bug(NagivationTab): prevent min height if no children

translations/base.json
Update to wallet section
N/A
https://getlago.slack.com/archives/C01DKGDLQ6B/p1724664633360509)
Wallet summary includes "total invoiced" that is in fact the consumed credits. Changing to "Total consumed" to avoid confusion.
Thanks!
=> misc: update copy

src/components/plans/ProgressiveBillingSection.tsx, src/generated/graphql.tsx, src/hooks/useOrganizationInfos.ts, src/pages/settings/Authentication/Authentication.tsx, src/pages/settings/Integrations.tsx
Related to LAGO-283
Premium Integrations are becoming more and more important in our codebase, and this PR should fetch them once instead of multiple times throughout the app
=> refactor: fetch integrations inside useOrganizationInfos hook

src/layouts/CustomerInvoiceDetails.tsx, src/pages/InvoiceOverview.tsx, translations/base.json
=> bug: better condition for Anrok sync actions

src/components/plans/details/PlanDetailsChargesSectionAccordion.tsx
=> fix: Fix filter title text overflow

src/core/apolloClient/cacheUtils.ts, src/hooks/core/useLocationHistory.ts, src/pages/Home.tsx
Fixes ISSUE-422
If a user follows a link to Lago and is not redirected, they are asked to login.
Once logged in successfully, their reach their expected destination.
However, if a user logs in using a third party (like google SSO), this redirection logic breaks.
The reason is that during the thirdparty login process, they are redirected out the app and the "memory" of the destination page is lost.
This PR addresses this situation and bring a fix using the browser's local storage.
When ever a user is 
- kicked out the app after following a link (needs to login)
- Logs out the app (couldn't bypass this, this event looks just like a kick out)
they now "register" their last visited page (or destination in the first case) into their local storage.
This data is not lost when they use a …
=> misc: make sure redirection is not lost after outside navigation

src/components/customers/addDrawer/AddCustomerDrawer.tsx
BE allows to have not value there, we should allow creating a customer without one.
Note the UI already react well to this as name is optional on the customer type.
This is just to allow the form to be submit in this case
=> misc: customer name should not be mandatory as on BE

src/components/designSystem/graphs/InlineBarsChart.tsx
Fixes LAGO-300
This PR does add a new API to this component: `tooltipsData`
Once passed, it can show a tooltip on hover, with a specific given message
`tooltipsData` keeps the same data shape as the `data` in this component, which is [dictated by Rechart](https://recharts.org/en-US/api/Bar#data)
=> feat(InlineBarsChart): add new tooltip on hover API

src/components/designSystem/NavigationTab.tsx, src/layouts/CustomerInvoiceDetails.tsx, src/layouts/Developers.tsx, src/pages/CustomerDetails.tsx, src/pages/InvoicesPage.tsx, src/pages/PlanDetails.tsx, src/pages/__devOnly/DesignSystem.tsx, src/pages/settings/AnrokIntegrationDetails.tsx, src/pages/settings/NetsuiteIntegrationDetails.tsx, src/pages/settings/XeroIntegrationDetails.tsx
Working on a feature, I felt limited by the existing `NaviationTab` component API that did not allow flexibility on the spacing rules.
That is something I missed during my dive-in but felt necessary during development phase.
Decided to
- Update the `NaviationTab` API to allow a better spacing definition, following the same rules as the `Table` component
- Update `NaviationTab` invocations all over the app to either hard replace with the exact same spacing rules as before, or slightly adjust them to fix weird renders (IIRC only in the plan details)
=> misc(NavigationTab) update the API to allow leftSpacing object

scripts/translations/add.js
Add a new flag in translation script to allow international keys
```bash
// Only update english language
yarn translations:add {number}
// Updates all files in translation folder with the same key
yarn translations:add {number} --intl
```
=> feat: intl support

src/components/plans/CustomCharge.tsx, src/components/plans/StandardCharge.tsx
Fix typo for interface props in CustomCharge and StandardCharge components
This PR re-opens [the original one](https://github.com/getlago/lago-front/pull/1732) created by [tnlong311](https://github.com/tnlong311) due to private CI token not shared.
=> fix: fix typo for interface props in CustomCharge and StandardCharge

src/pages/CustomerDetails.tsx
Clicking on the Customer portal link wouldn't work on Safari (it would generate a "Pop-up blocked" error).
Fixes LAGO-434
=> Fix opening the customer portal link on Safari

src/pages/Home.tsx
I felt into a random situation multiple time.
After log in, I fall in the home `/` route, and never been redirected to the correct destination (depending on LS or permissions).
Ending in only having the side nav displayed, but a blank screen elsewhere.
I can never reproducing afterward, cleaning LS or using private nav did not help.
I was considering that we had some kind of race condition at app boot (I mean, we probably do), where the expected data was not there, even tho the loading of the data was done.
We have an issue with the app boot but landing a big refactor is not something I wanna start right now 😕 
To try making it more efficient, I make sure the membership is present and the hook is called if so, before triggering the redirection.
This does not solve the deeper issue but …
=> bug: slight improvement for home redirection

src/components/designSystem/graphs/fixtures.ts, src/components/subscriptions/SubscriptionUsageLifetimeGraph.tsx, src/components/subscriptions/SubscriptionUsageTabContent.tsx, src/components/subscriptions/__tests__/utils.test.ts, src/components/subscriptions/utils.ts, src/generated/graphql.tsx, src/hooks/customer/useAddSubscription.tsx, src/hooks/plans/usePlanForm.tsx, src/pages/CreatePlan.tsx, src/pages/CreateSubscription.tsx, src/pages/SubscriptionDetails.tsx, translations/base.json
We've recently moved the current usage to the subscription details > usage tab
This PR adds an additional graph representing the progressive billing evolution.
Some redirections needed to be fixed and have been added in a separate commit.
This it the last part of the progressive billing - Current usage initiative
Fixes LAGO-302
=> feat: add lifetime usage graph to sub details

src/components/plans/ProgressiveBillingSection.tsx
Prevent focus ring to overflow and being cropped by the `overflow: auto` container
Fixes LAGO-338
=> misc: fix focus ring cropped from container

package.json, yarn.lock
Have to be done that way as webpack-dev-server#express version have not been updated yet to the version containing the fix. See https://github.com/getlago/lago-front/security/dependabot/78 and https://github.com/getlago/lago-front/security/dependabot/79
=> deps: bump express resolution

.vscode/lago.code-snippets, package.json, src/components/designSystem/Alert.tsx, src/components/designSystem/Button.tsx, src/components/designSystem/ButtonLink.tsx, src/components/designSystem/Icon/Icon.tsx, src/components/designSystem/Skeleton.tsx, src/components/designSystem/Toasts/Toast.tsx, src/components/form/Checkbox/Checkbox.tsx, src/components/form/ComboBox/ComboBoxInput.tsx, src/components/form/ComboBox/ComboBoxItem.tsx, src/components/form/ComboBox/ComboBoxPopperFactory.tsx, src/components/form/MultipleComboBox/MultipleComboBoxItem.tsx, src/components/form/MultipleComboBox/MultipleComboBoxPopperFactory.tsx, src/components/form/Radio/Radio.tsx, src/components/form/Switch/Switch.tsx, src/styles/utils.ts, yarn.lock
With the introduction of tailwind, and especially **Class Variance Authority** package to handle classes, we no longer need `classnames` lib as cva exports `clsx` already.
Doc : https://cva.style/docs/api-reference#cx
Ref: [Understanding the Differences Between clsx, classnames, and twMerge in React and Tailwind CSS](https://www.linkedin.com/pulse/understanding-differences-between-clsx-classnames-react-terranova-l5dxf/)
This PR removes `classnames` and replace with `cx`
=> misc: remove classnames and use cx feature from cva

src/pages/Home.tsx
Recently added a logic to store the last visited page in LS, and this can be used to redirect the use back to the expected URL even is they are using an external auth like google SSO.
If you visit an url landing on `/`, the redirection will send you then again on Home and prevent the correct redirection to happen.
Here we simply prevent redirection on HOME `/` from HOME 😅
=> bug: fix redirection stuck on home white page

src/components/addOns/AddOnItem.tsx, src/components/coupons/CouponItem.tsx, src/components/customers/CustomerItem.tsx, src/components/customers/overview/CustomerCoupons.tsx, src/components/designSystem/Avatar.tsx, src/components/developers/EventItem.tsx, src/components/developers/WebhookLogItem.tsx, src/components/plans/PlanItem.tsx, src/components/wallets/WalletTransactionListItem/ListItem.tsx, src/layouts/CustomerInvoiceDetails.tsx, src/layouts/SideNavLayout.tsx, src/pages/CreditNoteDetails.tsx, src/pages/settings/AdyenIntegrationDetails.tsx, src/pages/settings/AdyenIntegrations.tsx, src/pages/settings/AnrokIntegrationDetails.tsx, src/pages/settings/AnrokIntegrations.tsx, src/pages/settings/Authentication/OktaAuthenticationDetails.tsx, src/pages/settings/GocardlessIntegrationDetails.tsx, src/pages/settings/GocardlessIntegrationOauthCallback.tsx, src/pages/settings/GocardlessIntegrations.tsx, src/pages/settings/LagoTaxManagementIntegration.tsx, src/pages/settings/NetsuiteIntegrationDetails.tsx, src/pages/settings/NetsuiteIntegrations.tsx, src/pages/settings/OrganizationInformations.tsx, src/pages/settings/StripeIntegrationDetails.tsx, src/pages/settings/StripeIntegrations.tsx, src/pages/settings/XeroIntegrationDetails.tsx, src/pages/settings/XeroIntegrations.tsx, tailwind.config.ts
Tailwind migration
Migrate avatar component and remove usage of `styled(Avatar)` in favor of dedicated classnames
Related to LAGO-329
QA: https://feat-tailwind-app.staging.getlago.com/
=> refactor(avatar): migrate to tailwind

src/components/subscriptions/SubscriptionUsageLifetimeGraph.tsx
This also fixes the loading state that was wrong
=> misc: fix icon alignment and migrate component to tailwind

nginx/nginx.conf
Adding CSP `frame-ancestors` rule to prevent rendering Lago into an unexpected iFrame context.
=> secu: add nginx header config for CSP frame-ancestors

src/layouts/CustomerInvoiceDetails.tsx, src/pages/CreditNoteDetails.tsx, translations/base.json
When syncing invoices with Xero via the UI, the success toast displays a message about NetSuite.
This should display the correct success message.
Fixes ISSUE-444
=> fix: success toast for xero sync

src/main.css
Tailwind displays svg as `block` element and it breaks some of our components.
Set svgs to `inline-block` to fix the issue.
Fixes ISSUE-455
=> fix: set svg to inline-block

src/components/SearchInput.tsx
TW have been setup in our project recently.
Some default css rules have been added to the project.
We now have a `box-sizing: border-box` on all elements. In the search bar, the icon was places using padding, but it made it disappear from the UI, so using margin fixed it
Fixes ISSUE-465
=> bug: make search input's icon visible again

src/public/icons/forms/radio-checked.svg, src/public/icons/forms/radio.svg
Classname wasn't applied to component due to class attributes instead of className in react
=> fix: class into classname

src/components/form/ComboBox/ComboBoxPopperFactory.tsx
Applying content-box to combobox component. It should not impact popper with buttons with this solution.
Fixes ISSUE-464
=> fix: add content-box sizing to combobox popper

src/components/invoices/details/InvoiceDetailsTableBodyLine.tsx, src/generated/graphql.tsx
Makes sure the percentage fee details is correctly handled and has the same display logic as BE
=> misc: show details for all percentage fees

src/components/designSystem/Selector.tsx, src/main.css, src/pages/__devOnly/DesignSystem.tsx, src/pages/settings/Integrations.tsx, tailwind.config.ts
Part of the migration to Tailwind
Migrate selector button and its usage
Related to LAGO-329
=> refactor(selector): tailwind migration

src/pages/CustomerRequestOverduePayment/components/EmailPreview.tsx
If customer net payment term was set to 0 days, it was not taken into account in the email preview and we used the organization settings.
Using `??` fixes the issue instead of `||`
=> fix: manual dunning email preview

translations/fr.json
Added extra space in FR translation for email
There are spaces before double punctuations signs in FR (:;? etc)
Thanks!
=> misc: typo

src/components/settings/LanguageSettingsButton.tsx, src/components/settings/PreviewEmailLayout.tsx, src/pages/settings/EmailScenarioConfig.tsx
To prepare the auto-dunning feature, I'd like to extract some components from email preview page that can be reusable (`/settings/emails/config/invoice_finalized`)
I export the language settings button and the email preview layout.
=> refactor: email preview layout

src/components/creditNote/CreditNotesTable.tsx, src/components/customerPortal/PortalInvoicesList.tsx, src/components/customers/CustomerInvoicesList.tsx, src/components/invoices/InvoicesList.tsx, src/core/utils/downloadFiles.ts, src/layouts/CustomerInvoiceDetails.tsx, src/pages/CreditNoteDetails.tsx, src/pages/CustomerDetails.tsx
As I was fixing some window open logic, decided to tackle this old issue.
This PR makes sure all file download uses the same logic and checks.
So
- Errors are handled the same way
- It works on all browsers
Fixes https://github.com/getlago/lago-front/issues/522
=> misc: regroup download file methods into one util

src/components/settings/integrations/AddGocardlessDialog.tsx, src/core/constants/externalUrls.ts, src/pages/settings/GocardlessIntegrationDetails.tsx
We were not using the same behaviour as modal opening, so it was blocking on Safari.
This PR aligns the behaviour with the rest of the app
Fixes ISSUE-436
=> bug(Gocardless): make sure auth popup opens on any browsers

src/components/designSystem/Drawer.tsx, src/components/settings/dunnings/PreviewCampaignEmailDrawer.tsx, src/generated/graphql.tsx, src/pages/settings/Dunnings/CreateDunning.tsx, translations/base.json, translations/de.json, translations/es.json, translations/fr.json, translations/it.json, translations/nb.json, translations/sv.json
This is related to automatic dunning initiative
It should implement the preview email in the create dunning page.
We use the same dunning email as for the manual payment feature but with fake data.
It can be safely merge as this is not visible in the app directly but only through `/settings/dunnings/create` URL
Fixes LAGO-403
=> feat: preview email in dunning creation form

src/components/developers/DebuggerEventDetails.tsx, src/components/developers/EventItem.tsx, src/generated/graphql.tsx, src/pages/developers/Debugger.tsx, translations/base.json
- Remove the `external_customer_id`  field on events debugger
- Only show some fields if they're present because of new Clickhouse events format
=> chore(events): Remove external_customer_id on events debugger

src/components/settings/integrations/NetsuiteIntegrationMapItemDialog.tsx
We have 2 system of mapping in the same component.
So there  2 payload shape, and spreading the whole values can make the other one having unexpected attribute.
We're already explicit in the payload data build, so there is no reason to spread the rest of the form's values here
Fixes ISSUE-506
=> bug: should manually build payload in mapping

cypress/cypress.config.js, cypress/e2e/t30-create-one-off-invoice.cy.ts
Try to understand why the e2e are failing sometimes
Related to ISSUE-497
Still WIP, PR is open to test e2e on the CI
=> fix: flacky e2e test

src/components/designSystem/Skeleton.tsx
Tailwind migration
Deprecate margin props in favour of tailwind classnames
=> feat: deprecate margin props

src/components/form/ComboBox/ComboBox.tsx, src/components/form/MultipleComboBox/MultipleComboBox.tsx
Remove match from `start` and set it to default (`any` position).
Doc: https://mui.com/material-ui/react-autocomplete/#createfilteroptions-config-filteroptions
Also trim the searched value.
Fixes ISSUE-403
=> feat: allow to search anywhere in the combobox value

src/components/customers/addDrawer/ExternalAppsAccordion.tsx, src/core/utils/featureFlags.ts, src/pages/settings/Integrations.tsx
The dev of Hubspot integration is done and we can now remove the FF logic
This PR removes all logic around `HUBSPOT_INTEGRATION` FF, also put back a default FF otherwise the type checking fails, maybe we could improve this but I find it ok to put back the default. Let me know if you have a better idea
=> misc: enable Hubspot integration feature

src/components/designSystem/Avatar.tsx, src/components/designSystem/Skeleton.tsx, src/pages/__devOnly/DesignSystem.tsx
We introduced Tailwind (TW) and we're migrating all out style to use it.
This PR starts the migration of Skeleton component to TW. 
But it keeps the backward compatibility to the old API.
The reason is that there is ton of invocation to update, and tied to them some component that it could be worth migrating to TW at the same time, and I prefer to do it in multiple PRs
So here, we allow the Skeleton to use TW classes and be migrated over the time, without breaking all loading states of the app.
I'll take care of the migration of all invocations.
=> misc(Skeleton): start TW migration but allow backward compatibility

src/components/settings/integrations/AddNetsuiteDialog.tsx, src/components/settings/integrations/NetsuiteIntegrationMapItemDialog.tsx, src/components/settings/integrations/NetsuiteIntegrationSettings.tsx, src/generated/graphql.tsx, translations/base.json
You can map a Lago item (collection or unique item) to an item in Netsuite.
The Process was the following
- open mapping modal on a Lago item
- Under the hood we fetch Netsuite items
- select a Netsuite mapping item
- save the mapping to attach the two items together (saved in Lago DB)
Main problem, the max amount of item you can fetch on Netsuite is 1000 and there is no pagination. It's a hard limit.
This PR changes the way we enter mapping informations.
Now, you have to fill in manually the informations we were pre-fetching and selecting when picking an item in the Netsuite item list.
We pass from 1 combobox to 3 fields.
Note it was already the case if the item was a tax type.
It almost make this component simpler.
Fixes LAGO-504
=> misc: change Netsuite item mapping UX

cypress/e2e/10-resources/t10-create-taxes.cy.ts, cypress/e2e/10-resources/t20-create-customer.cy.ts, cypress/e2e/10-resources/t30-create-bm.cy.ts, cypress/e2e/10-resources/t40-create-plan.cy.ts, cypress/e2e/10-resources/t50-edit-plan.cy.ts, cypress/e2e/10-resources/t60-coupons-create-edit-apply.cy.ts, cypress/e2e/10-resources/t70-addon-create-edit.cy.ts, cypress/e2e/t10-add-subscription.cy.ts, cypress/e2e/t20-invitations.cy.ts, cypress/e2e/t30-create-one-off-invoice.cy.ts, cypress/support/commands.ts, cypress/support/e2e.ts, cypress/support/index.d.ts
We have an assertion that make the last e2e test fail randomly
Try to simplify the assertion. It not have the correct type applied and those attributes are mandatory.
Also removed the `::preventLogin` check in the title. That's a good idea but it's not used in the app
=> bug(e2e): flaky assertion in beforeEach

src/components/settings/integrations/NetsuiteIntegrationItemsListDefault.tsx
Minor improvement, but it covers some cases with some old data not being properly mapped.
Can be visible in edge cases but better more control than less I guess here
=> misc: make sure Netsuite item's data is fully valid before flagging it as mapped

src/components/subscriptions/SubscriptionCurrentUsageTable.tsx, src/components/subscriptions/SubscriptionUsageLifetimeGraph.tsx, src/generated/graphql.tsx, translations/base.json
If a subscription is pending, the current usage endpoint throw an error if fetched.
This PR make sure the endpoint is not fetched in such situation and adapts the empty state copy.
Also adapt the copy for lifetime usage that kinda have the same problem (without the error) but it still have to fetch the data before, as it's used in 2 placed and have an internal fetch logic.
Fixes ISSUE-536
=> bug: prevent current usage fetch for pending subscriptions

src/pages/CreatePlan.tsx
We recently added a feature to display a warning modal when it impacts a subscription with overrides.
This modal should only be displayed during an edit flow tho
This PR make sure the display condition is respected.
Fixes ISSUE-548
=> bug: only show override modal on edit mode

src/components/customerPortal/common/SectionLoading.tsx, src/components/designSystem/Avatar.tsx, src/components/designSystem/Skeleton.tsx, src/components/form/ComboBox/ComboBox.tsx, src/components/graphs/Invoices.tsx, src/components/graphs/Usage.tsx, src/components/plans/details/PlanSubscriptionListItem.tsx, src/components/settings/PreviewEmailLayout.tsx, src/components/settings/integrations/IntegrationItemLine.tsx, src/layouts/SideNavLayout.tsx, src/pages/InvoiceOverview.tsx, src/pages/SubscriptionDetails.tsx, src/pages/__devOnly/DesignSystem.tsx, src/pages/settings/EmailScenarioConfig.tsx, translations/base.json
Skeleton have a new API enforcing the usage of class name rather than props attributes.
This PR makes the skeleton text all use default height (12px).
Also,  a circular variant should use the size API rather than setting a width and height with same value each time
=> misc: continue one Skeleton api migration

src/components/coupons/CouponItem.tsx
A refactor in the past made this typo component turn into simple div. Hence the color being potentially overriden by the wrapper link, turning text in blue
This PR restore the typography component and define a color
Fixes ISSUE-556
=> bug: use typography component for text display

src/core/apolloClient/cacheUtils.ts, src/hooks/useOrganizationInfos.ts, src/layouts/SideNavLayout.tsx
When switching orga, some "core" data are not renewed. That lead for example to have the orga name not being updated in the sidebar.
This PR make sure the cache is totally reset during an orga switch, just like we do for a log out. 
But keeping the auth token allows to re-trigger all usefull queries.
Note that as the cache is reset, all active queries are still triggered but canceled by apollo (haven't found a better way).
Also added a loading state on the orga name in the sidebar
Fixes ISSUE-565
=> bug: orga switch should reset cache and invalidate all active queries

src/components/invoices/details/InvoiceDetailsTableBodyLineGraduated.tsx, src/components/invoices/details/InvoiceDetailsTableBodyLineGraduatedPercentage.tsx
Graduated and graduated percentage fee can have only one tier defined on plan level.
That mean any amount will be defined of 1 unit and above.
This PR does make sure we mention "above" in the copy, and also align with the BE copy on the PDF.
Note this translation already exist an just need to be used if the array length it 1.
Fixes ISSUE-568
=> misc: adapt fee copy for 1 tier graduated & percentage graduated

src/components/customerPortal/usage/UsagePage.tsx, src/components/customerPortal/usage/UsageSubscriptionItem.tsx, src/components/subscriptions/SubscriptionCurrentUsageTable.tsx, translations/base.json, translations/de.json, translations/es.json, translations/fr.json, translations/it.json, translations/nb.json, translations/sv.json
Some customer found it not clear whereas if a price is display including or excluding taxes
We now display this information when it make sense
Fixes ISSUE-567
=> misc(CustomerPortal): display some excluding tax label when needed

src/components/billableMetrics/CustomExpressionDrawer.tsx, src/components/billableMetrics/utils.ts, translations/base.json
Recently, it was found out that if the event payload doesn't contain a `timestamp`, the whole UI crashes.
It was happening because we were throwing an object Error & React couldn't render it.
Just converting it to a string wouldn't have worked, as the error would be cryptic. Instead, created a list of required properties which are checked before trying to evaluate an expression.
=> (fix): Fix custom expression crashing

src/components/designSystem/Accordion.tsx
Recent Accordion refactor to use tailwind introduces a different behaviour
The previous condition made the `noContentMargin` checked in priority when applying the padding.
```
padding: ${({ $size, $noContentMargin }) =>
$noContentMargin
? 0
: $size === AccordionSizeEnum.medium
? theme.spacing(4)
: theme.spacing(8)};
```
This PR makes the `p-0` important if `noContentMargin` is passed
=> bug(Accordion): make sure noContentMargin condition overrides

package.json, yarn.lock
We have a low CVA to fix about a sub-sub deps called `cookies`.
We use yarn 1.x to the process it usually to remove and re-install packages to upgrade deeper deps.
This was not working due to a resolution fixing an old version of `express` package.
This PR removes all resolutions, re-install packages and upgrade some other that fixed lower versions (fixed previously by the `resolution` def)
App runs and seems ok
Fixes ISSUE-558
=> deps: remove resolutions and update some packages

src/core/apolloClient/init.ts
Just saw this `@ts-expected-error` we could get rid of.
FYI this is what `LagoGQLError` looks like 
```
export interface LagoGQLError extends GraphQLFormattedError {
extensions: {
code: LagoApiError
details: Record<string, string[]>
}
}
```
and the value is of type `GraphQLFormattedError`
=> misc: recast type to remove ts expected error comment

src/components/designSystem/Filters/filtersElements/FiltersItemInvoiceType.tsx, src/components/designSystem/Filters/filtersElements/FiltersItemPaymentStatus.tsx, src/components/designSystem/Filters/filtersElements/FiltersItemStatus.tsx, translations/base.json
We display some invoice status filter values that are internal states for Lago, hence not being relevant for customers
This PR make sure we only display what we want to, also passes on other filters to use proper translations for the filter's label
Fixes ISSUE-572
=> misc: make sure we control filter values displayed

src/components/form/MultipleComboBox/MultipleComboBox.tsx
The chip spacing inside an Autocomplete wasn't right.
It seemed like the `sx` we were passing were getting overridden by some default theme styles. Changed it to a `className` and now it works properly.
Before & after:
Fixes LAGO-573
=> fix(MultipleComboBox): Fix chip spacing

src/components/customers/CustomerInvoicesList.tsx, src/components/invoices/InvoicesList.tsx, src/core/constants/statusInvoiceMapping.ts
A customer has recently requested a new column in the invoices list: Overdue.
- Added the Overdue columns for the invoices page & customer invoices list (the ones that aren't draft)
- Removed a case from the `paymentStatusMapping` function, as it was returning `Overdue` for overdue invoices, and this would have overlapped with the new implementation
Fixes LAGO-575
=> feat: Overdue column in invoices list

src/components/designSystem/Table/Table.tsx, src/core/utils/__tests__/responsiveProps.test.ts, src/core/utils/responsiveProps.ts, tailwind.config.ts
As part of our ongoing journey to migrate from styled components to tailwind, the Table component also needed refactoring.
Few points to note about this migration:
- All styles components are now JSX components written on top of Table definition, in the same file
- Styles are defined in 3 separated manner
- `className` for "default" and toggled styles
- `styles` for "dynamic" styles mapped on variables
- `sx` for "complex" selector (specific classes, pseudo elements, ...)
- Component class names `lago-*` are not in variables. Even tho they are used multiple times, I had to prevent using variables because we cannot use dynamic classe names in `sx` selector. Those are not interpreted during run time but build and "transformed" as static css on the flight. Even with unchanged const it don't …
=> misc(Table): migrate to Tailwind

src/components/customers/addDrawer/AddCustomerDrawer.tsx, src/components/customers/addDrawer/BillingAccordion.tsx, src/components/customers/addDrawer/MetadataAccordion.tsx
`AddCustomerDrawer` component started to be very long (around 750 lines). 
This PR should split it into multiple ones and migrate them to Tailwind
=> refactor: split add customer drawer

src/components/form/TextInput/TextInput.tsx
Another day, another tailwind migration
I simplified the dom, there were an unnecessary wrapper div around the label and infoText 
Fixes LAGO-427
=> misc(TextInput): migrate to Tailwind

package.json, src/components/billableMetrics/CustomExpressionDrawer.tsx, yarn.lock
An example was provided with the wrong kind of quotes which made the evaluating part fail.
Updated to normal single quotes.
Fixes LAGO-584
=> fix(CustomExpressionDrawer): Fix broken example

src/components/creditNote/CreditNotesTable.tsx, src/components/designSystem/Table/Table.tsx
To be able to customize td parent element of a cell
Add `tdCellClassName` support on columns props
=> feat: add tdCellClassName in table columns

src/hooks/plans/__tests__/useGraduatedChargeForm.test.tsx, src/hooks/plans/__tests__/useVolumeChargeForm.test.tsx, src/hooks/plans/useGraduatedChargeForm.ts, src/hooks/plans/useVolumeChargeForm.ts
We had a decimal limitation on the volume and graduated table
Turn the value into a number breaks the input as it turns the value into a scientific notation and after 1e-7 we were not able to add more decimals. Turning into a string should fix the issue.
=> fix: use string instead of number to avoid scientific notation

translations/base.json
Until now, the draft invoices amounts weren't included in the displayed wallet consumption.
Include the new properties defined by the backend in the calculation for the wallet consumption.
Fixes LAGO-569
=> fix: Wallet draft ongoing balance

src/formValidation/metadataSchema.ts
A customer wanted to add more than 40 characters to the metadata.
Increased the limit to the new one.
Fixes LAGO-597
=> feat(metadataSchema): increase max metadata length

src/components/form/Radio/Radio.tsx, src/components/form/Radio/RadioField.tsx, src/components/form/Radio/RadioIcon.tsx, src/public/icons/forms/radio-checked.svg, src/public/icons/forms/radio.svg
Related to tailwind migration
Use SVG in the component itself to avoid passing custom classnames and use tailwind instead
Fixes LAGO-429
=> refactor: migrate radio to tailwind

__mocks__/styleMock.js, jest.config.js, src/components/form/JsonEditor/JsonEditor.tsx, src/components/form/JsonEditor/jsonEditor.css
Related to Tailwind Migration
- Extract custom `react-ace` style into a specific file
- Remove usage of `<Fade>` from MUI in favour of Tailwind
- Remove usage of styled-component
Fixes LAGO-431
=> refactor: migrate json editor component

src/components/customers/CustomerMainInfos.tsx, src/core/constants/externalUrls.ts
Most of our users use Stripe PP and it sounds great to display the linked customer on stripe in the customer sidebar.
Also took the opportunity to uniform the link style in this section
Fixes LAGO-630
=> feat: create hyperlink for stripe customer in sidebar

src/components/customers/CustomerMainInfos.tsx
A link is inlined with other infos, and the focus ring looks kinda broken on click and feels like a but.
I decided to break the internet and remove the focus ring on those link, but it has to be important 😬
=> misc: remove focus on click for inlined link

src/components/designSystem/Filters/filtersElements/FiltersItemPaymentStatus.tsx, src/components/form/MultipleComboBox/MultipleComboBox.tsx
This PR fixes 2 aspects of the Multiple combobox
- Make sure that once selected, we display the item label first THEN the value, in the input's badge
- Fix the uncontrolled state warning, as it was initialised with undefined. Defaulting to empty string fixes this
=> misc: improve multiple combobox behaviour

src/components/coupons/AddBillableMetricToCouponDialog.tsx, src/components/coupons/AddPlanToCouponDialog.tsx, src/components/customers/EditCustomerVatRateDialog.tsx, src/components/customers/addDrawer/ExternalAppsAccordion.tsx, src/components/form/ComboBox/ComboBox.tsx, src/components/form/ComboBox/ComboBoxItem.tsx, src/components/form/ComboBox/ComboBoxItemWrapper.tsx, src/components/form/ComboBox/ComboBoxPopperFactory.tsx, src/components/form/ComboBox/ComboBoxVirtualizedList.tsx, src/components/form/ComboBox/index.tsx, src/components/form/ComboBox/types.ts, src/components/form/MultipleComboBox/MultipleComboBoxItem.tsx, src/components/form/MultipleComboBox/MultipleComboBoxPopperFactory.tsx, src/components/form/MultipleComboBox/MultipleComboBoxVirtualizedList.tsx, src/components/invoices/EditInvoiceItemTaxDialog.tsx, src/components/plans/ChargeAccordion.tsx, src/components/plans/ChargesSection.tsx, src/components/plans/CommitmentsSection.tsx, src/components/plans/PlanSettingsSection.tsx, src/components/settings/invoices/AddOrganizationVatRateDialog.tsx, src/pages/CreateAddOn.tsx, src/pages/CreateInvoice.tsx, src/pages/CreateSubscription.tsx, src/styles/muiTheme.ts, tailwind.config.ts, translations/base.json
We migrate our components to Tailwind.
This PR is about combobox migration and a first part have already been done. Check it out for more details: https://github.com/getlago/lago-front/pull/1942
Migrate last Combobox inner components and rename ones.
Some impacts on the multiple combobox, that should be migrated very soon too.
Fixes LAGO-433
=> misc: migrate combobox to Tailwind

src/components/form/ComboBox/ComboBox.tsx, src/components/form/ComboBox/ComboBoxPopperFactory.tsx, src/components/form/ComboBox/ComboboxList.tsx, src/components/form/MultipleComboBox/MultipleComboBox.tsx, src/components/form/MultipleComboBox/MultipleComboBoxItemWrapper.tsx, src/components/form/MultipleComboBox/MultipleComboBoxList.tsx, src/components/form/MultipleComboBox/MultipleComboBoxPopperFactory.tsx, src/components/form/MultipleComboBox/MultipleComboBoxVirtualizedList.tsx, src/components/form/MultipleComboBox/types.ts
Following TW migration of the Combobox component, it's now the Multiple Combobox show time
Basically take back all changes from those [#1](https://github.com/getlago/lago-front/pull/1942) [#2](https://github.com/getlago/lago-front/pull/1943) PR related to Combobox, and apply the same ones for the multiple one.
Fixes LAGO-430
=> misc: migrate multiple combobox to tailwind

src/pages/Analytics.tsx, src/pages/BillableMetricsList.tsx, src/pages/CouponsList.tsx, src/pages/CreateAddOn.tsx, src/pages/CreateInvoice.tsx, src/pages/CreateSubscription.tsx, src/pages/CreditNoteDetails.tsx, src/pages/CustomerDetails.tsx, src/pages/CustomerDraftInvoicesList.tsx, src/pages/InvoiceCreditNoteList.tsx, src/pages/PlansList.tsx, src/pages/WalletForm/WalletForm.tsx, src/pages/__devOnly/DesignSystem.tsx, src/pages/auth/Login.tsx, src/pages/auth/LoginOkta.tsx, src/pages/developers/Debugger.tsx, src/pages/developers/WebhookLogs.tsx, src/pages/settings/EmailScenarioConfig.tsx, src/pages/settings/GocardlessIntegrationDetails.tsx, src/pages/settings/LagoTaxManagementIntegration.tsx, src/pages/settings/StripeIntegrationDetails.tsx
Same as https://github.com/getlago/lago-front/pull/1948 but for another batch.
Another PR will change some shared component implem, just prefered to separate them
=> misc: migrate styled typography to tailwind part II

src/components/designSystem/Skeleton.tsx
We noticed the Navigation tab Skeleton was too wide
This PR fixes this bug, by making sure the classname defined during invocation is passed to every cases of the conditional wrapper
Fixes ISSUE-609
=> bug: make sure className is passed to all Skeleton cases

src/components/customers/CustomerCreditNotesList.tsx, src/components/customers/overview/CustomerCoupons.tsx, src/components/customers/overview/CustomerOverview.tsx, src/components/customers/overview/CustomerSubscriptionsList.tsx, src/components/wallets/CustomerWalletList.tsx, src/pages/CreateTax.tsx, src/pages/Invitation.tsx, src/pages/auth/ForgotPassword.tsx, src/pages/auth/ResetPassword.tsx, src/pages/auth/SignUp.tsx, src/styles/auth.tsx, src/styles/customer.tsx, src/styles/detailsPage.tsx, src/styles/mainObjectsForm.tsx
Last but not least  PR to remove all `styled(Typogaphy)` in our codebase.
This PR turns styles components into Functional components that returns a Typography element using tailwind
Note I removed `SectionTitle` exported styled component as it was only used once, to use TW in place instead
=> misc: refactor shared styled typography to render FC with TW

src/components/plans/ChargeAccordion.tsx, src/components/plans/ChargeBillingRadioGroup.tsx, src/components/plans/CommitmentsSection.tsx, src/components/plans/ProgressiveBillingSection.tsx, src/layouts/SideNavLayout.tsx
Another styled component usage migrated to TW.
This time for `styled(Icon)` occurrences
=> misc: migrate all styled icon to use tailwind

src/components/designSystem/Table/Table.tsx
The table header is sticky, however the row elements coud overlap on it on scroll.
I'm not sure yet why the header is not sticky in invoice page tho, probably because of upper sticky header
=> bug: make sure table sticky action column is visible on scroll

cypress/e2e/t30-create-one-off-invoice.cy.ts, src/pages/CreateInvoice.tsx
The API allows multiple decimal for units in one-off creation.
This allows to do the same from the UI
=> misc(OneOffInvoice): allow 3 decimal value for units

src/pages/settings/Integrations.tsx
This feature have been released. It needs to be displayed all the time in the integration list
=> misc: remove feature flag on salesforce integration display

src/styles/customer.tsx, src/styles/mainObjectsForm.tsx
If we don't pass explicitly the classname to the `tw` helper, it's overridden instead of combined.
Fixes ISSUE-621
=> bug: make sure classname is merge with existing one

src/components/creditNote/CreditNotesTable.tsx, src/components/customers/CustomerInvoicesList.tsx, src/components/designSystem/Table/Table.tsx, src/components/designSystem/__tests__/Table.test.tsx, src/components/invoices/InvoicesList.tsx, src/pages/AddOnsList.tsx, src/pages/BillableMetricsList.tsx, src/pages/CouponsList.tsx, src/pages/CustomersList.tsx, src/pages/PlansList.tsx, src/pages/__devOnly/DesignSystem.tsx, src/pages/developers/Webhooks.tsx, src/pages/settings/EmailSettings.tsx
A customer asked to be able to open row link redirection in a new tab.
We're not the best in term of accessibility and it's kinda hard to have a native `a` link into a table structure without increasing the complexity of the Table component.
I noticed we only use the `onRowAction` to execute a navigate all over the app, so decided to rename it and for it to return a string.
So we can check if meta or ctrl key are pressed to open in new tab, otherwise use the navigate from `rect-router-dom` as usual.
Put that into the same commit as pretty tied
Fixes ISSUE-615
=> misc(Table): allow to open row link in new tab

src/components/form/ComboBox/ComboBoxVirtualizedList.tsx
Fixes the Combobox element height if it contains a description.
Note: I'm tired of those shenanigans and random calculation values there and in the multiple combobox. I think we should (i) upgrade MUI to v6, (ii) negociate to have a combobox looking like the MUI doc with design, (iii) remove all our custom implementation to get something simpler that works without all this magic and the world would be much safer place.
Fixes ISSUE-619
=> bug(Combobox): fix element height with description

package.json, src/hooks/plans/__tests__/useVolumeChargeForm.test.tsx, src/hooks/plans/useVolumeChargeForm.ts, yarn.lock
We have a precision issue in volume alert.
Using value `1*10` + `value 2 * 10` later `/100` hack does have limitations as we allow 15 decimals in this field and we never end up having a correct rounding
End up adding mathjs in the project for those situations. The `precision: 14,` is there [specifically cause it detect there is a rounding error and it must ignore them in the returned value](https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors).
Also, we can surely use mathJs elsewhere in the app
Fixes ISSUE-629
=> bug(Volume charge): make sure amount calculation precision is correct

src/components/designSystem/Filters/utils.ts
Looks like after the credit note export/filters functionality, the invoice export wouldn't work with an issuing date because it wasn't flattened. This would have been fixed as part of the new amount filter PR, but this needs to be urgently fixed, so it was cherry-picked from that branch.
Uniformize the filter parsing.
Fixes ISSUE-630
=> fix(InvoicesPage): Fix export while having a issuing date filter enabled

eslint.config.mjs
Enabled some extra eslint rules that will improve the readability and maintenance of our codebase.
Current count of nested ternaries: 285
Current count of unneeded ternaries: 1
=> feat(eslint): enable no-nested-ternary and no-unneeded-ternary

src/components/designSystem/Filters/filtersElements/FiltersItemAmount.tsx, src/components/designSystem/Filters/types.ts, src/components/designSystem/Filters/utils.ts, src/components/invoices/InvoicesList.tsx, src/generated/graphql.tsx, src/pages/InvoicesPage.tsx
This PR enables filtering invoices by amount. A big chunk of the work was done previously for the Credit notes export feature.
Most of the change is just including the amount filter in invoice-related logic.
This change also includes an improvement to the query filtering logic, by making it consistent between credit notes and invoices. This should help us in the future if we want to also filter other entities.
=> feat: Invoice amount filter

src/pages/settings/CashfreeIntegrationDetails.tsx, src/pages/settings/CashfreeIntegrations.tsx
PageHeader internal implementation changed recently.
Another feature came on top and we missed some update there.
This is causing the app not to build anymore on cloud deploy.
This PR updates those missing implementations
=> bug: update missed page header implementations

vite.config.ts
A recent [update of vite](https://github.com/getlago/lago-front/pull/1998) package requires us to configure the allowed hosts for local dev, in order to whitelist the proxy.
=> bug: define allowedHosts in vite config

renovate.json
A bit sad, but not everyone respect strict semver for their package tags. 
Prevent having issues after an automatic merge like this morning.
=> chore: prevent dependabot auto merge

src/components/creditNote/CreditNotesTable.tsx, src/components/customers/CustomerCreditNotesList.tsx, src/pages/InvoiceCreditNoteList.tsx
Removes the filters from customer/invoice credit notes. We will introduce them at a later point, together with invoice filtering.
Fixes LAGO-660
=> hotfix: Remove filters from credit notes

src/components/customers/CustomerMainInfos.tsx, src/components/customers/createCustomer/ExternalAppsAccordion/PaymentProvidersAccordion.tsx, src/core/utils/featureFlags.ts, src/generated/graphql.tsx, translations/base.json
Boleto is an important payment method in Brasil. Some of our customers needs this to be enabled in their Stripe setup to bill over there.
FE changes is is only about adding this new option in the list.
I also fixed an unexpected behaviour when unchecking Card option, that was caused by having 2 slice on the same array next to each other.
I used the filter approach on other options too.
Fixes LAGO-714
=> feat: add Boleto as Stripe payment method

src/pages/developers/Webhooks.tsx
We recently updated the webhook limit to be 10 but forgot to update the FE limit.
And here it is.
=> misc: change webhook limit to 10

src/components/form/JsonEditor/JsonEditor.tsx
Users shouldn't be able to edit the value of a disabled editor
It seems like the only property that properly handles the disabled case is the `readonly` flag. Made that take into account the value of the `disabled` prop.
Fixes ISSUE-674
=> fix(JsonEditor): prevent user from changing the value of a disabled editor

src/components/creditNote/CreditNoteActions.tsx, src/components/creditNote/CreditNoteActionsLine.tsx, src/components/creditNote/CreditNoteEstimationLine.tsx, src/components/creditNote/CreditNoteFormCalculation.tsx, src/components/creditNote/CreditNoteItemsForm.tsx, src/components/form/TextInput/TextInput.tsx, src/pages/CreateCreditNote.tsx
To prepare Partial Payment feature, I refactored this component that was very hard to read (and to maintain)
This PR essentially separate the `CreateCreditNote` page into specific components :
- `<CreditNoteItemsForm/>` :
- `<CreditNoteFormCalculation/>` uses now a `<CreditNoteEstimationLine/>` component to avoid repeating ourselves :
- `<CreditNoteActions/>` 
It also introduces a new component called `<CreditNoteActionsLine/>` that is not used for the moment but will be in the next feature.
**Note: I didn't migrate CreditNoteActions to tailwind as the UI will change in the next feature.**
=> refactor: create credit note

src/components/customers/CustomerInvoicesList.tsx, src/components/invoices/InvoicesList.tsx, src/core/constants/NavigationEnum.ts, src/pages/CreateCreditNote.tsx, src/pages/CreditNoteDetails.tsx, src/pages/CustomerInvoiceDetails.tsx
Noticed `NavigationEnum` exported the exact same enum as in `tabsOptions` file.
Also `tabsOptions` contains more exported constants so it's the winner that deserved to stay in the app ⚔️
=> chore: unify imports and remove unused NavigationEnum

src/components/customerPortal/common/CustomerPortalSections.tsx, src/components/customerPortal/common/CustomerPortalSidebar.tsx, src/components/settings/PreviewEmailLayout.tsx, src/components/settings/invoices/PreviewCustomSectionDrawer.tsx, src/generated/graphql.tsx, src/hooks/useOrganizationInfos.ts, src/pages/CustomerRequestOverduePayment/components/EmailPreview.tsx, src/pages/customerPortal/CustomerPortal.tsx
We should hide the watermarks for organizations that have the premium `RemoveBrandingWatermark` addon.
- Improve the `useOrganizationInfos` hook so that it also exports the addons that are enabled (this will improve reusability) 
- Hide watermarks based on this new addon (note: we need to `!` it, because we show the watermarks by default)
- Hide customer portal watermarks
Note: The build will currently fail since backend didn't implement `PremiumIntegrationTypeEnum.RemoveBrandingWatermark`. Once that's on main, I'll regenerate the types.
=> feat: Remove watermarks

src/components/designSystem/Table/HorizontalDataTable.tsx, src/pages/__devOnly/DesignSystem.tsx
This component is not used on production yet.
It had a columns approach in it's way to draw elements in the dom. But in each columns, we display multiple rows.
And this columns props should be named rows to be more accurate here.
=> chore: rename horizontalDataTable column props into rows

src/components/RouteWrapper.tsx, src/core/apolloClient/reactiveVars/locationHistoryVar.ts
Route wasn't added to the history when using quick filters because de pathname was the same and we didn't check for search params changes.
Fixes ISSUE-683
=> fix: add location when search params changes to history

src/components/creditNote/CreditNoteFormCalculation.tsx
Regarding the issue we got recently with one of our customer
Before
After
=> fix: compare numbers with same precision

src/components/analytics/RevenueStreamsBreakdownSection.tsx, src/components/analytics/RevenueStreamsOverviewSection.tsx, src/components/layouts/FullscreenPage.tsx, src/generated/graphql.tsx, src/pages/analytics/NewAnalytics.tsx, src/pages/analytics/RevenueStreams.tsx, translations/base.json
We're building a new analytics page.
Goal is to slowly implement those pages without letting users access it.
Those will be part of the build and available on prod if you modify url tho. We decided not to worry about that during development phase.
This PR implements the revenue streams overview part, without the filters.
Later I will add a PR to add filters and the breakdown part of the page
I prefer to merge this before going further into complexity. I think it contain a good chunk of functionality and code that work well together.
=> misc: improve new analytics page skeleton

src/components/creditNote/CreditNotesTable.tsx, src/components/designSystem/Filters/__tests__/useFilters.test.tsx, src/components/designSystem/Filters/context.tsx, src/components/designSystem/Filters/useFilters.ts, src/components/designSystem/Filters/utils.ts, src/components/invoices/InvoicesList.tsx, src/core/constants/filters.ts, src/pages/CustomersList.tsx, src/pages/InvoicesPage.tsx
The current Filters architecture makes it impossible to have 2 sets of filters on the same page, because of how the filters are stored in the URL params.
Added a new prop `filtersNamePrefix` which enables us to have multiple Filters on the same page by prefixing their name:
```
https://app.lago.dev/invoices/invoices?
in_amount=isBetween%2C5%2C100
&in_currency=USD
&cn_amount=isBetween%2C5%2C6
&cn_creditNoteCreditStatus=voided
```
To use this functionality, we need to pass the new prop in two places:
- The Filters.Provider
```
<Filters.Provider
quickFiltersType={AvailableQuickFilters.InvoiceStatus}
filtersNamePrefix="in"
...
```
- When calling the `formatFiltersForQuery` function
```
return formatFiltersForQuery({
searchParams,
availableFilters: InvoiceAvailableFilters,
filtersNamePrefix: …
```
=> feat: Filters prefix

src/components/designSystem/Filters/ActiveFiltersList.tsx, src/components/designSystem/Filters/useFilters.ts
We recently added the ability to add a prefix on filters.
This was breaking their display in the active filter component.
This PR takes prefix into consideration and display them accordingly
=> bug: display applied filters if they contain a prefix

src/components/analytics/RevenueStreamsOverviewSection.tsx, src/components/designSystem/Table/HorizontalDataTable.tsx, src/components/designSystem/graphs/MultipleLineChart.tsx
This PR improves look and feel for the revenue streams graph.
1. You can now see the tooltip when hovering an element in the table bellow.
2. The tooltip animation is restored and it's position now stick with the bar cursor
=> misc: revenue streams UX improvements

translations/base.json
I was working on the stripe integration and found some dead code about updating stripe secret keys. I went to the frontend to confirm you couldn't update the key and I realized the button label was probably left from before.
the key is the only thing we can't update ^^
https://github.com/getlago/lago-api/pull/3300/files/f513ce745949c87fa7c31aaa2af185d2249ae42a#diff-0bfe4ac658f027888fa85c15375149c307d2ef0efa389f2527c9070be8970a48
=> fix(text): updating stripe connection button

src/components/analytics/RevenueStreamsOverviewSection.tsx, src/components/analytics/useRevenueAnalyticsOverview.ts, src/components/analytics/utils.ts, src/generated/graphql.tsx
This PR simply move revenue streams overview logic into a hook, that will later have it's own tests. Also, a util have been created for the data padding logic and I'll implement it in a following PR
=> misc: move revenue streams overview logic into hook

src/components/designSystem/Table/Table.tsx, tailwind.config.ts
We've made an attempt to fix the table shadows earlier. This was improving the chromium users' experience while others get a deteriorated one.
This PR fixes look and feel for all users.
It reverts previous approach and uses a better one.
Also makes sure scrollbar is placed above inner `position: fixed` inner elements on Safari
Fixes ISSUE-727
=> bug: fix table action column shadow

src/components/analytics/RevenueStreamsOverviewSection.tsx, src/components/analytics/RevenueStreamsStateContext.tsx, src/components/analytics/__tests__/utils.test.ts, src/components/analytics/useRevenueAnalyticsOverview.ts, src/components/designSystem/Filters/FiltersPanelPopper.tsx, src/components/designSystem/Filters/context.tsx, src/components/designSystem/Popper.tsx, src/components/designSystem/Table/HorizontalDataTable.tsx, src/components/designSystem/graphs/MultipleLineChart.tsx, src/pages/analytics/RevenueStreams.tsx
This PR brings 2 changes
- Better performances on the graph hover. Allowing better experience on larger dataset
- Update the Popper to allow passing a custom opener
Also add some tests
Better review commit by commit
=> misc: improve analytics perf and handle premium filters

src/components/invoices/details/InvoiceDetailsTableBodyLine.tsx
We changed this rule on the PDF hence reflecting it here.
The units sent on events can be huge, and we are making them more "digest" visually.
Fixes ISSUE-679
=> misc(invoice-details): allow 6 max fractional digits on units

src/components/analytics/RevenueStreamsOverviewSection.tsx, src/components/analytics/useRevenueAnalyticsOverview.ts
This PR fixed the reset filter behaviour by reseting the currency to the default one.
=> misc(revenue-streams) ensure reset filters restores default currency

src/components/designSystem/graphs/MultipleLineChart.tsx
While building the multiple line chart, I ended up pre-optimising some perf for the graph hover debounce function.
While they provide good directions, the `maxWait` was too flaky and let to slower rendering in the end. I may have to adapt the math here bure realised just removing it improved drastically perfs here.
We still have some fps drop when dataset is above 1k elements but it's mostly renders well.
Also `trailing` default value is `true` so no need to have it here.
=> misc(multipleLineChart): Remove over optimisations that led to slow performances

src/components/customers/CustomerInvoicesList.tsx, src/components/invoices/InvoicesList.tsx, src/hooks/usePermissionsInvoiceActions.ts, src/pages/CustomerInvoiceDetails.tsx
Related to our discussions on whitelisting and blacklisting. As @stephenlago99 mentioned, having reusable functions first will make it easier to refactor our checks.
- Introduce `usePermissionsInvoiceActions`
Note: In several places, the checks for `canDownload`, `canFinalize`, and `canRetryCollect` are not the same. It’s worth flagging this to the product team to ensure these differences are intentional.
=> refactor: invoices actions

src/generated/graphql.tsx
Was doing some tests with pagination, and forgot to remove the not-yet-implemented metadata field in query result.
It should be ready soon on BE, but having it today makes the query fail, hence having a broken QA/dev env
=> bug(revenueStreams): remove forgotten yet-unexisting metadata

src/components/analytics/revenueStreams/RevenueStreamsOverviewSection.tsx, src/components/designSystem/graphs/MultipleLineChart.tsx
We're testing ths revenue streams and performing some adjustments before it's official release.
The multiple line chart x axis ticks displays dates. Those were initially showing the `xAxisDataKey` attribute of the data, here set to the start period value of each object.
What we want in the end is to display the first items' start date, and the last item's end date in this graph's ticks
To do so, we passes an array of size 2 describing what attributes to show based on the data attributes.
I'll create another PR for the area chart component with similar intent. But the change is different and implies more QA on my side.
=> misc(RevenueStreams): improve XAxis tick display logic

src/components/analytics/mrr/useMrrAnalyticsOverview.ts, src/components/analytics/revenueStreams/useRevenueAnalyticsOverview.ts, src/components/designSystem/Filters/FiltersPanelPopper.tsx, src/components/designSystem/Filters/__tests__/useFilters.test.tsx, src/components/designSystem/Filters/filtersElements/FiltersItemDate.tsx, src/components/designSystem/Filters/useFilters.ts
New analytics graphs are in their late QA phase. We're performing more tests and discovered an inconsistency around dates
3 changes:
- All dates handled there should be handled as UTC dates. Data is interpreting them as utc anyway.
- Fix an issue with search params manipulation. Changing it as string didn't applied the encoded format. Using the `searchParams` directly fixes that as it's done under the hood 
- I also added a missing form validation for the date filter that have been recently added.
Better reviewed commit by commit
=> bug(new-analytics): make sure dates are correctly handled

src/components/analytics/mrr/MrrBreakdownSection.tsx, src/components/analytics/revenueStreams/RevenueStreamsCustomerBreakdownSection.tsx, src/components/analytics/revenueStreams/RevenueStreamsPlanBreakdownSection.tsx
No typography noWrap attributes should be used inside rows of a Table component.
The Table grows depending on the children content's width, so we don't want to crop it!
=> bug: no text should be wrapped in table rows

src/pages/PaymentDetails.tsx
Fix badge alignment
BEFORE
AFTER
I tested with a link displayed above, works well
=> misc: fix badge alignment

src/main.tsx
It costs a lot, better not get a record for all of them.
I've tested with "manual" error and I'm satisfied with the record, Sentry do not record sensitive data by default
=> chore(Sentry): record replay for 30% of errors

src/core/timezone/__tests__/utils.test.ts, src/core/timezone/utils.ts
While migrating the formatDateToTZ function, I noticed that there's already an existing utility to get the UTC offset, which can be reused directly instead of duplicating the logic.
I also found that there's another function, formatTimeOrgaTZ, which formats dates using the organization's timezone internally. In my opinion, we should favor using this function more consistently, rather than relying on the default UTC timezone.
=> fix: dates util function

.github/workflows/codegen.yml
PNPM and Vite now makes the CI too fast, and sometimes we need to wait for the API wi be ready to perform some actions (here the codegen)
The wait done maybe too early tho
=> misc: delay the API wait until last moment in CI

src/main.tsx
Removing for now, it catches some query retry and auth error that does not affect UX.
Let's hide them for now
=> misc(Sentry): remove too noisy error catch

src/components/settings/integrations/AnrokIntegrationSettings.tsx, translations/base.json
The default copy was showing "sync in progress" even tho the call was not triggered.
This fixed the copy depending on the loading state
Fixes ISSUE-843
=> bug: prevent wrong copy displayed for invoice sync

src/components/designSystem/graphs/StackedBarChart.tsx
=> fix(PrepaidCreditsAnalytics): fix formatting ticks with big number short notation

src/components/designSystem/Filters/FiltersPanelPopper.tsx
`staticFiltersFormValues` array was still defined even if it was empty.
Fixes issue-851
=> fix: clear filters nullish value

src/hooks/core/useLocationHistory.ts, src/pages/Home.tsx, src/pages/Invitation.tsx
We're experiencing many 404 errors on Sentry.
It cames to conclusion that most of them are due to a wrong redirection after login.
Today, we have 2 ways to manage location history and redirections:
- The react router one, handled in a reactive var called `locationHistory`
- The Local Storage (LS) one, handled by the value stored in `LAST_PRIVATE_VISITED_ROUTE_WHILE_NOT_CONNECTED_LS_KEY`
This PR makes sure redirection logics are not conflicting and don't lead to wrong redirections anymore.
On logout (or JWT expiration), we not only rely on the LS logic, and we also store the organization ID there.
So on login we can compare the orga ID and determine if the redirection should occur or of we should rely on the default one (done in `Home.tsx`).
LS key should also be removed in the invitation …
=> bug: fix wrong redirections

.gitignore, package.json
We have some packages in the app. Only the design system one need to be build to be used.
We have to build also when working locally, at least once.
I've added a `postinstall` to build the packages too, so the `start.dev.sh` commands don't have to be updated and developers/contributors don't have to find out how to run the app locally for the first time and don't face this error.
I had to add some new ignored files in the list tho. For some reasons, building through docker generated other folders that were not listed there.
Fixes ISSUE-856
=> misc: make sure to build packages on install

babel.config.cjs, jest.config.ts, package.json, pnpm-lock.yaml
Related to this issue https://github.com/getlago/lago-front/actions/runs/14728160893/job/41335728042?pr=2149 since the migration to the monorepo
The issue was caused by `lago-design-system` being an ESM Modules in the Jest Environment (that does not support it).
We switched from ts-jest to babel-jest for transpilation because it is more straightforward to setup the compilation from esm to commonjs.
=> fix: add babel to jest

src/pages/Home.tsx
I changed the LS value shape but customer can still have the old value type there (just a string)
This PR makes sure we check on the shape before entering the if.
Thankfully, the Sentry error just mean it was raising a console error but redirection still hapened
=> misc: fix LS old data shape wrong access

src/components/addOns/DeleteAddOnDialog.tsx, src/components/customers/DeleteCustomerDialog.tsx, src/components/plans/DeletePlanDialog.tsx
Manually manipulating the cache makes apollo re-trigger active queries. 
We should instead let him handle re-fetch and cache update.
Did that for 3 different resources
Fixes ISSUE-857
=> bug: prevent cache manipulation after deletion

src/components/customers/overview/CustomerSubscriptionsList.tsx, src/core/constants/statusSubscriptionMapping.ts, src/pages/SubscriptionDetails.tsx
- Usage tab should be hidden for certain subscription statuses. 
- The status badge was not the same on different pages of the app. It's now unified and uses the same logic in the list and in the details page. 
Fixes ISSUE-858
=> misc: fix and improve subscription details

src/hooks/core/useLocationHistory.ts, src/layouts/Settings.tsx
This is a hairy one.
If you get kicked out the app (e.g. JWT expiration), we set the last visited route to LS.
If you do it on any settings page, 404 or forbidden one, you will face a bug when clicking on "back" or "Back to the app" button.
They all use the goBack method, and in those 3 pages it sets the home page as a fallback.
Issue is that if you navigate this route, you will perform the home hook logic that checks the LS last visited route, hence being redirected to your LS last visited route, again.
This is edge but can happen.
As we still live with the custom navigation LS and the localHistory var, this is more a patch than a real fix.
And going back with HOME as a fallback is deterministic, users intentionally know where he'll be redirected so we can clear this LS place.
Also …
=> misc: clear LS last visited route before goBack on home

src/core/apolloClient/init.ts
We receive a lot of sentries but message is not explicit.
This is because the error type is not an JS error type but a GQL serialized one.
This PR makes sure we pass the message to the error, and all the value as additional data so we don't miss anything.
So error willl now be like `Resource not found` instead of the autogenerated random letters we got
=> misc: improve sentry error messages

package.json, packages/design-system/package.json, packages/design-system/vite.config.ts, pnpm-lock.yaml
We have different version of vite package in our "main" package and the `design-system` one.
We should use the same, hence this bump to latest version.
Note the migration from v4 to v6 changes the design-system `assetFileNames` config. As it's a single package imported to another app, it's recommended to defined to a "simple" name. 
The previous implementation was deprecated
Closes https://github.com/getlago/lago-front/pull/2160
=> deps: unify vite version accros packages

src/components/customers/overview/CustomerSubscriptionsList.tsx
Make sure we don't displayed unnecessary children sub if the parent one is terminated. It happen when we perform a downgrade.
Occurs since we removed the sub filter by status 
Fixes ISSUE-866
=> bug: prevent sub display if parent is terminated

src/components/invoices/EditInvoiceDisplayName.tsx
Noticed we were not able to submit after reseting the invoice display name input value
=> bug: allow to reset invoice display name value

package.json, pnpm-lock.yaml
2 CVE issues on babel version of `"@babel/helpers"` and `"@babel/runtime"` which are `"<=7.26.10"` is opened since almost 2 months now. This is a moderate issue so we have 90 days to fix but none of the concerned packages seems to have an open PR or discussion for that.
The package version fix is on a minor version bump so decided to manually fix the version. This does not seem to break or alter the app in any ways.
Fixes https://github.com/getlago/lago-front/security/dependabot/102 and https://github.com/getlago/lago-front/security/dependabot/103
=> deps: fix some babel deps to fix CVE

src/pages/CustomerInvoiceDetails.tsx, translations/base.json
This PR does 2 things
- use the same LocalTaxProviderErrorsEnum to manage translations in all places of the app
- make `text_1723831881130g8hv6qzqe57` translation more generic, se we can use it for both Anrok and (next to come) Alavara tax providers
=> misc: unify tax error translations

src/pages/CreateInvoice.tsx
Placing this alert tag above makes it part of the parent div using a gap spacing. Hence fixing it's position in the page
=> misc: move alert tag to enter the correct spacing parent

src/components/analytics/usage/UsageBreakdownBillableMetrics.tsx, src/components/analytics/usage/UsageBreakdownIndividualSection.tsx, src/components/analytics/usage/UsageBreakdownSection.tsx, src/components/analytics/usage/UsageOverviewSection.tsx, src/components/analytics/usage/useUsageAnalyticsBreakdown.ts, src/components/designSystem/graphs/StackedBarChart.tsx, src/pages/analytics/UsageBillableMetric.tsx, translations/base.json
After using the new usage section in prod, found some small UI issues.
- Recurring metric is included in the metered section
- Units / Amount button size should be small
- No empty state for the breakdown section, when there aren't any metrics returned
- Main tooltip text needs to be updated
- Hover state should be simpler, just date and amount
=> feat(Analytics): Daily usage - fixes

src/pages/auth/PortalInit.tsx
Many customers faces errors when opening the customer portal from the "main" application. Leading to see only error states.
Also, most of the time when you open the customer portal, you're disconnected from the "main" app.
While those 2 issues seems non related they have the same root cause and can be mitigated.
This PR adds an instruction when opening the customer portal that will prevent any "active" queries to be re-triggered.
That was the root cause of the 2 error described above.
This was the flow:
1. I log in my Lago app
2. I go to a customer details page and click on the "Customer Portal" button to open it
3. Once open in a new window, this app starts to fire new queries needed for the portal to init, but also re-sync the previous active queries
4. This causes the first portal …
=> bug(customerPortal): prevent unexpected calls to be triggered

src/core/utils/__tests__/dateUtils.test.ts, src/core/utils/dateUtils.ts, src/pages/CreateCoupon.tsx
When creating a coupon, you can set a date so it expires.
You can set this date to the current day (expected). However the BE checks the date is in the future.
When clicking on a date with the DatePicker, it set's it with the current datetime. Hence the date sent to the BE for today never valid.
This PR transforms the date set to be at the endOf day time. 
Fixes ISSUE-894
=> bug(coupons): expirationAt should be set at end of day

src/components/developers/events/EventTable.tsx, src/components/developers/events/Events.tsx, src/components/developers/webhooks/WebhookLogs.tsx
- When using transactionId instead of eventId, i've forgotten a logic to set the active row that was still using eventId.
- I've also fixed the webhook active row that was having an issue on closing/opening the console
=> fix(console): set active row

src/core/apolloClient/cacheUtils.ts
When switching organization, we should called the same method as in `logOut` to prevent active queries from running
=> fix: prevent active queries

src/pages/developers/ApiKeysForm.tsx
Checkboxes' focus ring is cropped in the API keys form. Those elements are part of a Table.
This is not an ideal fix however any other approach won't be as short or easy to implement.
The root issue is the Table's internal cell that renders the content, which wraps the content within a Typography that uses a `noWrap` props, adding an overflow hidden. Hence cropping the ring.
Removing the `noWrap` does break an expected behaviour, that forces the cell to expend if the content goes beyond it's "default" width. leading to the table to expend and it's content to be reachable with an horizontal scroll.
So it's kinda what we want.
I would love to avoid adding an extra attribute to the table's cell. Reason is that while investigating I discovered some, and I felt adding more could lead to extend …
=> bug(ApiKeysForm): prevent checkbox's focus ring crop

src/pages/settings/SettingsHomePage.tsx
When navigating to the settings route, we land on a first page that builds the route to be redirected to.
This page holding a redirection logic and part of the history, if you decide to navigate back to it, the redirection logic fires again.
This PR makes sure this redirection replaces the current history, so it's no longer there if you navigate back.
Doing so will now bring you back to the main app.
Fixes ISSUE-897
=> bug: prevent redirection route to be in history

src/pages/CustomerInvoiceDetails.tsx
It seems like we shouldn't be able to create manual payment for draft invoice, so we should remove it from the navigation tab when navigating to invoice details
=> fix: remove payment tab for draft invoice

src/pages/CustomerRequestOverduePayment/index.tsx
We're displaying an alert in the "request payment" form if user does not have access to the feature.
This same check is used in the same component as `!hasDunningIntegration` but not the one about displaying this alert
Fixing the check for displaying alert so it uses the exact same condition all over the places
=> bug: display alert if no access to feature

src/pages/CreatePlan.tsx
Those extra rules made the bar broken on responsive screens.
Removing them allows the div to naturally takes full width.
It still need to hold the `!max-w-none` as it's part of a shared component `Main` that applied this max-w to all it's children div
Fixes ISSUE-935
=> bug: make sure the button bar takes full width

src/components/creditNote/CreditNoteDetailsOverviewTable.tsx, src/components/invoices/InvoiceCreditNotesTable.tsx, src/components/invoices/details/InvoiceDetailsTable.tsx
Still aiming to remove styled-components (SC) from the app and migrate to Tailwind.
This PR does
- change some spacing in the invoice overview, so they match with the spacing in the credit note (CN) overview and in the invoice->CN list
- Fix some styles previously done in the credit note list
- Use this same component across both CN details pages so we unify style and can remove SC from one of them
Bringing our remaining places with SC to 2
=> misc: use shared component for CN details

cypress/e2e/10-resources/t10-create-taxes.cy.ts, cypress/e2e/10-resources/t30-create-bm.cy.ts, cypress/e2e/10-resources/t40-create-plan.cy.ts, cypress/e2e/10-resources/t60-coupons-create-edit-apply.cy.ts, cypress/e2e/10-resources/t70-addon-create-edit.cy.ts, cypress/support/reusableConstants.ts, src/components/form/TextInput/TextInput.tsx, src/components/plans/PlanSettingsSection.tsx, src/core/utils/__tests__/updateNameAndMaybeCode.test.tsx, src/core/utils/updateNameAndMaybeCode.ts, src/pages/AlertForm.tsx, src/pages/CreateAddOn.tsx, src/pages/CreateBillableMetric.tsx, src/pages/CreateCoupon.tsx, src/pages/CreateTax.tsx, src/pages/settings/BillingEntity/sections/BillingEntityCreateEdit.tsx, src/pages/settings/Dunnings/CreateDunning.tsx, src/pages/settings/Invoices/CreateCustomSection.tsx
We want to improve the experience in forms, when typing the name to be able to pre-fill the code.
It makes sure the code is not updated on edit (if form has initial props) and if the user manually edited the code in the meantime (if the field is touched)
Fixes ISSUE-939
=> misc: autofill code on name update in form

.vscode/extensions.json, package.json, packages/design-system/package.json, packages/design-system/tsconfig.json, packages/design-system/tsconfig.playground.json, packages/design-system/vite.config.ts, pnpm-lock.yaml, tsconfig.json, vite.config.ts
We're aiming to remove styled-components (SC) in favour of Tailwind.
The last component was migrated a few days ago.
This is a wrap! 
Removing all SC related dependencies from our app and packages.
Note that the `styled-engine-sc` package was needed to link SC with MUI styles. We were not really using it initially but now it's not used at all.
This is the last step of the migration 🥳 
Fixes LAGO-878 and LAGO-327
=> deps: remove styled-components

src/pages/CreateAddOn.tsx
If there is an error, the inputs on the same line are not aligned anymore with an `items-start` rule.
Had to align top and push the second input with a margin as it does not have a label.
Fixes ISSUE-945
=> bug: make sure inputs are aligned when error is displayed

src/components/developers/apiLogs/ApiLogsTable.tsx
A bug was reported where navigating to audit log details causes the current filters to be lost
=> fix: include search params when navigate to api logs

packages/design-system/src/components/Skeleton.tsx, src/components/designSystem/Skeleton.tsx
Skeletons sometimes overflow their container when they have a width defined.
This PR makes sure that even if a `className` gives a precise width to a skeleton, it won't overflow size of it's container.
Fixes ISSUE-966
=> bug: prevent skeleton to overflow

package.json, pnpm-lock.yaml
We're handling this package version carefully cause it can have large impact and we discuss directly with Nango team to bump versions.
For this time there is no breaking change on our current usage of the package.
=> deps: bump @nangohq/frontend

src/components/wallets/WalletAccordion.tsx, src/components/wallets/WalletDetailsDrawer.tsx, src/components/wallets/WalletTransactionListItem/ListItem.tsx, src/components/wallets/WalletTransactionListItem/__tests__/index.test.tsx, src/components/wallets/WalletTransactionListItem/index.tsx, src/generated/graphql.tsx, translations/base.json
The goal of this PR is to expose the `wallet_transactions.sources` in the GQL schemas. This source is going to be used on the UI to segregate the type of transaction:
- If source = manual -> Manual credits
- If source = threshold -> Automatic credits
- If source = interval -> Automatic credits
The source has been added to:
1. The wallet transactions view of a customer's wallet
- If source = manual -> Manual credits
- If source = threshold -> Automatic credits
- If source = interval -> Automatic credits
2. The wallet transaction details drawer
Source: 
- Automatic threshold
- Automatic interval
- Manual
=> feat(wallet_transactions): add wallet transaction sources

nginx/nginx.conf, src/core/apolloClient/cache.ts
- frame-ancestors does not support * in the middle of a domain.
```
The Content-Security-Policy directive 'frame-ancestors' does not support the source expression 'ojin-staging*.web.app'
eyJfcmFpbHMiOnsiZGF0…a84596ee851ff3a14:1 The Content-Security-Policy directive 'frame-ancestors' does not support the source expression 'ojin-staging*.web.app'
```
- Cache isssue
```Cache data may be lost when replacing the customerPortalUser field of a Query object.
This could cause additional (usually avoidable) network requests to fetch data that were otherwise cached.
To address this problem (which is not a bug in Apollo Client), either ensure all objects of type CustomerPortalCustomer have an ID or a custom merge function, or define a custom merge function for the Query.customerPortalUser field, so …
```
=> fix: some warnings on runtime

src/pages/wallet/CreateWalletTopUp.tsx
In wallet top-up page, you have 2 level of scroll, one for the content and one for the whole container.
This second should not be there as it hides/show topbar when happening.
The scroll should only be for content
Reorder DOM to make the sticky footer part of the `CenteredPage.Wrapper`
This is the case on all other pages, was miss-placed here
Fixes ISSUE-977
=> bug: prevent double scroll in wallet topup page

src/components/coupons/AddBillableMetricToCouponDialog.tsx, src/components/coupons/AddPlanToCouponDialog.tsx, src/components/customers/AddCouponToCustomerDialog.tsx, src/components/customers/createCustomer/ExternalAppsAccordion/ExternalAppsAccordionLayout.tsx, src/components/form/ComboBox/ComboBoxItem.tsx, src/components/form/ComboBox/ComboBoxItemWrapper.tsx, src/components/form/MultipleComboBox/MultipleComboBoxItemWrapper.tsx, src/pages/AlertForm.tsx, src/pages/CreateBillableMetric.tsx
Recently updated the ComboboxItem internal classes and unified invocation.
Missed some cases
This PR make sure ALL invocations respects the same pattern and fixes the alignment if only one value is displayed in the dropdown.
Had to use important tailwind classes to prevent UI to mess with display
=> bug: fixing missed combobox invocation updates

src/components/designSystem/VerticalMenu.tsx
Recently reworked the nav and today noticed the loading skeleton was off and contained an extra margin on elements
=> misc: better nav loading skeleton

src/pages/settings/BillingEntity/sections/BillingEntityMain.tsx
Recently updated the copy size in the app.
Wrongly changed this part, hence adjusting it
=> misc: adjust settings copy size

src/components/subscriptions/SubscriptionCurrentUsageTable.tsx
I'm working around current usage and found it nice if the reload icon was spinning during refetch
spin icon and disable button during current usage fetch
=> misc: spin the reload icon on data fetch

package.json, pnpm-lock.yaml
Migration guide: https://docs.cypress.io/app/references/migration-guide
=> deps: migrate cypress to latest v14

src/pages/SubscriptionsPage.tsx
Forgot to add this props to update the loading state on subscription page
=> fix: display loading state on subscription page

package.json, pnpm-lock.yaml
Just deployed the `v0.1.6` of it
=> deps: get last lago-expression version

src/components/layouts/Section.tsx, src/components/layouts/Settings.tsx, src/components/settings/integrations/AnrokIntegrationSettings.tsx, src/components/settings/integrations/AvalaraIntegrationSettings.tsx
Recently changes most of the actions in pages to be inline buttons.
We decided to align the button with the baseline, making it aligned with the title next to it in all cases.
More natural and elegant placement
Fixes ISSUE-1004
=> misc: align action with label baseline

packages/design-system/tsconfig.build.json
When `CMD + Click` on a component from the `/package/design-system` (path named `lago-design-system`), the components opens on the `dist/` file export. Not showing the exact/complete code of the component. 
This change make sure the source map is generated for `/package/design-system` components, so TS understand where to find the component code's location itself.
Reference: https://www.typescriptlang.org/tsconfig/#declarationMap
=> misc: make CMD + click redirects to the package component

src/layouts/MainNavLayout.tsx
Manager could see empty `Reports` section because they don't have access to `analyticsView` permission
This PR should fix the issue
=> fix: avoid rendering empty section on navigation

src/core/constants/form.ts, src/generated/graphql.tsx, src/pages/wallet/CreateWallet.tsx, src/pages/wallet/components/ScopeSection.tsx, src/pages/wallet/components/SettingsSection.tsx, src/pages/wallet/types.ts, translations/base.json
We would love to add a limitation on the wallet where you can only apply the amount on certain fees related to certain billable metrics. 
This pull request refactors the wallet form to add a new section.
This new section contains the expiration dates that were already present on the different places of the form.
This new section also adds the possibility to select billable metrics on your wallet, so the amount will be only scoped to them. 
Fixes LAGO-918
=> feat: add billable metric limitation on wallet

src/pages/CustomerInvoiceDetails.tsx
We're fetching customer informations on the invoice preview, for display purpose.
It can happen the customer is deleted hence cannot be fetched, resulting in a not_found error and triggering an alert toast + sentry error.
This customer fetch is expected to potentially fetch and should not raise "visual" error. We can then silent it!
=> bug: make sure expected not found error don't raise alert

src/pages/features/FeatureForm.tsx, src/pages/features/FeaturesList.tsx, src/styles/designSystem/PageHeader.tsx
I'm working on a new feature "Feature and entitlement" and the List and Form are already on main, hidden a feature flag.
We decided to flag this feature as `Beta` for it's firs first weeks.
This PR adds the `Beta` chips on those pages.
Also fix default spacing between elements in the page header layout.
=> misc: add beta chip on feature pages

src/components/designSystem/Table/Table.tsx, src/pages/features/FeaturesList.tsx
Recently fixed the customer list to prevent name too long to create extra space.
This should be the case everywhere if the `maxSpace` is true IMO.
=> misc: set column maxWidth on maxSpace columns

src/pages/InvoicesPage.tsx
Attempt to fix these kind of errors: https://lago.sentry.io/issues/6581756497/events/7798dea65999490c80b47d48db013558/?project=6458937&referrer=replay-errors
In invoice list, we're fetching all invoices depending on their status including generating invoices which could be the reason of `Resource not found` type of error as the invoice is not completely "closed". 
This is an attempt to resolve the issue by only fetching finalized+draft invoices by default, and still be able to overwrite them with the filters object.
=> fix: fetch finalized or draft invoices only

src/components/activityLogs/utils.tsx, src/generated/graphql.tsx
We have an enum of activity type and their related copies dispayed in the logs are also listed.
A new type was added and it should uses the same copy as the generated case
=> misc: handle copy for InvoiceRegenerated activity type

src/components/designSystem/Filters/ActiveFiltersList.tsx, src/components/form/ComboBox/ComboBoxVirtualizedList.tsx
Should addressed these warnings
=> fix: warning filters

src/components/customerPortal/usage/UsagePage.tsx, src/components/customers/usage/SubscriptionUsageDetailDrawer.tsx, src/components/subscriptions/SubscriptionCurrentUsageTable.tsx, src/core/formats/formatInvoiceItemsMap.ts, src/generated/graphql.tsx, translations/base.json
We've decided to split the current usage query into two (default usage / projected usage). This means that, based on the fact if projected usage is enabled or not (premium integration), we call one of the two queries.
Re-added the changes we reverted. Most of the work went into fitting the types together. At one point, in the future, we will re-join the queries.
=> feat: Projected usage

src/components/customers/CustomerInvoicesList.tsx, src/components/invoices/InvoicesList.tsx, src/core/apolloClient/graphqlResolvers.tsx, src/core/utils/downloadFiles.ts, src/generated/graphql.tsx, src/pages/CustomerInvoiceDetails.tsx, translations/base.json
On Safari, the copy to clipboard should follow a direct user interaction.
But in this case we're waiting for the BE to answer with the call. It's called transient user activation
When the url is fetched, open a new tab with the URL.
That will allow to manually copy the URL and fix the issue with Safari users
I've also add an error catching in case we're flagging an error with the PSP to display relevant toast message to the customer
Fixes issue-1044
=> fix: generate payment link tab

src/pages/settings/BillingEntity/sections/BillingEntityEmailScenariosConfig.tsx
Fix email preview header size.
Made sure the scroll is preserved on smaller or bigger screens using `min-height-minus-nav` class helper
| BEFORE | AFTER |
|-|-|
| <img width="1512" height="862" alt="image" src="https://github.com/user-attachments/assets/4ab35563-0594-4f5c-b0d3-39aa30aa6a4c" /> | <img width="1506" height="862" alt="image" src="https://github.com/user-attachments/assets/83c8f248-8065-4a7b-a01f-3950d2b93065" /> |
=> bug: email preview header wrong height

src/components/designSystem/Table/ChargeTable.tsx
Reverts the change done in https://github.com/getlago/lago-front/pull/2415 and moves the delete button into the first cell.
The fluid width was breaking the table in some screens (progressive billing recurring thresholds, alert thresholds), because the first cell was being width-greedy. Reverted the change, and fixed the initial issue (the delete button making the table render and extra cell, thus making it jump around).
Fixes LAGO-1098
=> fix: undo dynamic width / move delete button in td

src/components/analytics/revenueStreams/RevenueStreamsCustomerBreakdownSection.tsx, src/generated/graphql.tsx
We need to show the gross amounts instead of the net ones.
- Updated graphql query
- Updated rendering
=> fix: Revenue streams - Show customers gross instead of net

src/components/customerPortal/usage/UsagePage.tsx, src/components/customers/usage/SubscriptionUsageDetailDrawer.tsx, src/components/subscriptions/SubscriptionCurrentUsageTable.tsx
Jeremy suggested that we should only call the projected usage endpoint after switching tabs. This is to prevent an extra heavy call going to the API.
Since the initial implementation assumed that we either call the regular query or the projected one, we had to do some changes:
- Hoist tab state
- Make sure to call the projected usage query only once (no matter how many times the user switches the tab)
- Enable drawer to call projected refetch directly
Fixes LAGO-964
=> feat: Only call projected usage on tab switch

src/components/designSystem/Filters/__tests__/utils.test.ts, src/components/designSystem/Filters/filtersElements/FiltersItemLoggedDate.tsx, src/components/designSystem/Filters/types.ts, src/components/designSystem/Filters/useFilters.ts, src/components/designSystem/Filters/utils.ts, src/components/developers/activityLogs/ActivityLogs.tsx, src/components/developers/apiLogs/ApiLogs.tsx
We have a bug when within a log list you fetch some collection, then a lot of items are added in the database, and you keep scrolling the page. The bug is about the fact that those new database elements will be fetched and displayed after the old elements even though they are earlier in the history. 
This is due to our pagination system that is not using cursor-based pagination but page-based pagination. 
This pull request aims to fix this behavior by setting a default to date with the value either to now or to the selected date by the customer.
Fixes ISSUE-1071
=> bug: define default dateTo on some logs queries

src/components/creditNote/__tests__/utils.test.ts, src/components/creditNote/utils.ts, src/pages/CreateCreditNote.tsx
When creating a credit note, you can subit the form after unchecking all fees.
Recently, Backend made a bugfix to return an error un such case, but it's still allowed to submit the form like this and receive an error.
This form can accept 3 "shapes" of fee.
Classic ones for addOn and credit fees. And more "complex" ones that has a different level of "checked" attribute.
This PR creates a check to prevent submitting the form if no fees are selected.
Had to make a different function is used at the submit button level. As it's checking on different attributes of the form, it was creating a complex code there and was hard to test that way.
Preferred to extract the logic in the existing util and test the method there.
Fixes ISSUE-1108
=> misc(creditNotes): validate form has at least one fee checked

src/components/plans/details/PlanDetailsAdvancedSettingsSection.tsx, src/components/plans/details/PlanDetailsOverview.tsx, src/components/subscriptions/SubscriptionDetailsOverview.tsx
A plan can hold entitlements.
You can override this at the subscription level, and they are visible on a dedicated tab, outside of the `Overview` details of the subscription, that mainly display the plan's details.
Historically, this overview section uses the `EditPlan` fragment, that todays fetches the plan's entitlements.
And we use the same components to display the plan details in the plan details page and the subscription's>plan details.
So we have the "original" entitlements of the plan displayed in the `Overview` tab, and the overriden ones in the `Entitlements` tab in the subscription details.
This pull request adds a new attribute to this plan details components, and you can now manually say if you want the entitlements section to be hidden or not (default to shown).
So the …
=> bug: always hide entitlements on subscription details overview

package.json, pnpm-lock.yaml
This PR bumps a package that fixes an internal one (axios) flagged containing a high severity CVE
Dependabot alert: https://github.com/getlago/lago-front/security/dependabot/116
PR on nango: https://github.com/NangoHQ/nango/pull/4664
=> deps: bumb nangohq to fix a high severity CVE on axios

src/hooks/__tests__/usePermissionsInvoiceActions.test.ts, src/hooks/usePermissionsInvoiceActions.ts
Noticed that we cannot dispute an invoice anymore.
It's been broken during a refactor and to make sure we don't miss that again i'm adding test for this permission file
Fixes ISSUE-1147
=> bug: restore the canDispute action

src/components/invoices/InvoicesList.tsx, src/hooks/__tests__/usePermissionsInvoiceActions.test.ts, src/hooks/usePermissionsInvoiceActions.ts, src/pages/CustomerInvoiceDetails.tsx
Taking the opportunity to remove the `TODO: Compare this with src/hooks/usePermissionsInvoiceActions.ts:` comments in the app.
I've come to the conclusion that `canFinalize` should check for an additional permission so i changed it and adapted the related test
=> misc: make invoice related permissions relies on the same logic

package.json, pnpm-lock.yaml
We have a [low severity CVE](https://github.com/getlago/lago-front/security/dependabot/113) on a sub deps of cypress.
It's fixed in their `15.0.0` so let's upgrade to the latest.
This `v15` brings the cypress studio and would be great to test it soon!
Other packages needs to be updated to have the CVE totally fixed on our repo but they are not there yet.
=> deps: bump cypress version to latest

src/components/subscriptions/SubscriptionCurrentUsageTable.tsx
The usage query was caching the first values received, making the drawer data innacurate.
Prevent caching of the usage query.
Fixes ISSUE-1148
=> [ISSUE-1148] Prevent cached usage data

src/components/designSystem/Filters/filtersElements/FiltersItemCustomer.tsx
When filtering on invoices page or any page allowing to filter per Customer, a Customer with a name too long may have it's content spill from the option. We want to improve readability by fixing this behaviour.
Uses the list wrapper to force content to be on one line. This improves readability of all other options but may hinder the readability of the long element
Fixes [ISSUE-1176](https://linear.app/getlago/issue/ISSUE-1176/customer-filter-is-broken-if-name-is-too-long)
=> fix(filters): fix customer filters when names are too long
